### ISSUE TITLE
Unable to find configure.....

### ISSUE THREAD

**Issue by ghost** [HDFGroup/hdf5#1053]
Hello together,
today I want to install your new hdf5 for testing, etc. - but I can't find the configure - file in this package. So it is possible to integrate this in this package?

Best regards

Z. Matthias

**Comment by lrknox** [comment]
What version of HDF5 do you have? Official releases should have a configure file, but otherwise you will need to run the autogen.sh script in the top level source directory to generate configure and other files for building HDF5.

**Comment by derobins** [comment]
We don't check in Autotools generated files like configure and Makefile.in until we prepare a release. As Larry indicated, you'll need to run autogen.sh if you check out a development branch.
