### ISSUE TITLE
H5Z-ZFP cannot be registered

### ISSUE THREAD

**Issue by jw447** [HDFGroup/hdf5#1055]
Hi,

I've been playing with parallel HDF5 with H5Z-ZFP when I encountered the error

"#016: H5Z.c line 1264 in H5Z_find(): required filter 32013 is not registered"

when I tried to set up the filter. Seems like ZFP filter cannot be loaded while the built-in GZIP work.

Could you please help me with the issue or should I raise this issue at H5Z-ZFP repo?

My configuration is as follows:

gcc/9.3.0
openmpi/4.0.4
HDF5/1.12
H5Z-ZFP/v1.0.1

Thanks in  advance,

**Comment by byrnHDF** [comment]
We have the ZFP plugin successfully building and testing standard hdf5, including parallel hdf5.
Do have any other plugins and are they working?
Have you used plugins before?
Is the enviroment variable, HDF5_PLUGIN_PATH, correct?
Allen

**Comment by jw447** [comment]
Thanks, @byrnHDF I've resolved this issue. It was indeed caused by the env variable HDF5_PLUGIN_PATH. I fixed it by adding H5PLappend(). Sorry that I forgot to close this in time.

**Comment by byrnHDF** [comment]
Great!
