### ISSUE TITLE
Doxygenize the high-level APIs

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#1108]
- [ ] [H5LT](https://portal.hdfgroup.org/display/HDF5/Lite)
- [ ] [H5IM](https://portal.hdfgroup.org/display/HDF5/Images)
- [ ] [H5TB](https://portal.hdfgroup.org/display/HDF5/Tables)
- [ ] [H5PT](https://portal.hdfgroup.org/display/HDF5/Packet+Tables)
- [ ] [H5DS](https://portal.hdfgroup.org/display/HDF5/Dimension+Scales)

**Comment by derobins** [comment]
Committed to develop, will be merged downstream.
