### ISSUE TITLE
possible inconsistent argument 'size' used in MPI_File_set_size

### ISSUE THREAD

**Issue by wkliao** [HDFGroup/hdf5#1155]
https://github.com/HDFGroup/hdf5/blob/9e0f68b967f3e28b6d052ccc45556aedae616d7a/src/H5FDmpio.c#L1749-L1751

The value of argument `needed_eof` passed into the call of MPI_File_set_size at line 1751
may not be consistent among MPI processes. Shouldn't it use `size` instead of `needed_eof`?
Note `size` is broadcast at line 1742 and thus definitely consistent among MPI processes.
https://github.com/HDFGroup/hdf5/blob/9e0f68b967f3e28b6d052ccc45556aedae616d7a/src/H5FDmpio.c#L1742

Note in MPI standard, it states "MPI_FILE_SET_SIZE is collective; all processes in the group must pass identical values for size."

**Comment by derobins** [comment]
H5FD_mpi_haddr_to_MPIOff() just basically casts the EOA to an MPI_Offset value and the EOA is the same in all processes, so the code is in question is correct.
