### ISSUE TITLE
Clang throws cast-align warning.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#1167]
Warning message pattern:

warning: cast from **'Type A***' to '**Type B***' increases required alignment from **C** to **D** [-Wcast-align]

Affected files:

test/h5test.h
tools/lib/h5tools.c

See also PR #1129 and PR #1130.

**Comment by seanm** [comment]
There are many such warnings. I fixed a bunch long ago, but the remaining ones are non trivial, require API change, etc.

Would be really nice to see them finally fixed though!

**Comment by derobins** [comment]
There are no more cast-align warnings in the library w/ clang 14 in either debug or production builds
