### ISSUE TITLE
JHI5 JavaDoc missing for hdf.hdf5lib.exceptions 

### ISSUE THREAD

**Issue by mkitti** [HDFGroup/hdf5#1185]
The JavaDoc for [`hdf.hdf5lib.exceptions`](https://github.com/HDFGroup/hdf5/tree/develop/java/src/hdf/hdf5lib/exceptions) is missing:
https://bitbucket.hdfgroup.org/pages/HDFFV/hdf5doc/master/browse/html/javadoc/index.html?overview-summary.html

The only place to find it is in the JHDF5 19.04 package documentation, but I understand correctly, the canonical source is actually from HDF5 Group.
https://svnsis.ethz.ch/doc/hdf5/hdf5-19.04/index.html?hdf/hdf5lib/exceptions/package-summary.html

**Comment by byrnHDF** [comment]
PR #1197 created for review.

**Comment by byrnHDF** [comment]
javadoc updated in current source since #1197 was merged.

**Comment by mkitti** [comment]
Thank you
