### ISSUE TITLE
Parallel Write Hangs with OpenMPI 4.0.3

### ISSUE THREAD

**Issue by houjun** [HDFGroup/hdf5#1227]
@tpg2114 and I discovered a [deadlock/hang issue](https://github.com/AMReX-Codes/amrex/issues/2491) when writing a dataset in parallel with collective I/O turned on while using OpenMPI with ompio driver. Here is a simple [reproducer code ](https://gist.github.com/houjun/fb6179af24c2f58e8ea4ad2191f7ca90) that hangs when running with 31 MPI ranks with OpenMPI 4.0.3, HDF5 1.12.1 and HDF5 1.10.8. 

@tpg2114 found that:

> It does hang with mpirun --mca io ompio -np 31, and looking at the documentation, the io ompio option is the default driver for my build. So I tried it with mpirun --mca io romio321 -np 31, which is the only other IO MCA my build has.
> 
> That does not hang.
> 
> So the problem seems to be in the OMPIO driver specifically, whereas the ROMIO driver works correctly.
> Further testing reveals it is the fcoll MCA that is the problem. With the OMPIO driver, it defaults to the vulcan fcoll parameter. When I run with the OMPIO driver with --mca fcoll dynamic_gen2, --mca fcoll individual, or --mca fcoll two_phase, it works fine and doesn't hang. If I run with --mca fcoll vulcan, it hangs.

and 
> And with those search terms in hand, it looks like this is a known bug in OpenMPI:
> https://www.mail-archive.com/users@lists.open-mpi.org/msg33511.html
> although it was marked fixed in 4.0.3 [here](https://github.com/open-mpi/ompi/issues/7109), but it doesn't seem to be fixed for me.

**Comment by derobins** [comment]
This can be reopened if more information comes to light, but 4.0.3 is a known buggy version of OpenMPI w/ 1.14 and this looks like an MPI issue.
