### ISSUE TITLE
gcc compile the hdf5 grow a error: does not give a valid preprocessing token

### ISSUE THREAD

**Issue by summerccc** [HDFGroup/hdf5#1266]
I use the command: ./configure .next I use the command : make . the process appear a error: H5B.C:153:1: error: pastinq ""H5B key t" and  arr" does not qive a valid pre processinq token

**Comment by derobins** [comment]
We would need to know more about your system, compiler, and build to answer this. With the Autotools, config.log will be very helpful.

Also, questions like this are best asked on the HDF Forum:

https://forum.hdfgroup.org/
