### ISSUE TITLE
test/accum.c  CTest fails on macOS Monterey

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#1289]
```
19: Testing SWMR write of large metadata: with latest format              *FAILED*
19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: Testing SWMR write of large metadata: with non-latest-format          *FAILED*
19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
19: child process exited abnormally
19: *** TESTS FAILED ***
```

**Comment by seanm** [comment]
What are the test names exactly?

I've just tried on older macOS 10.14:

```
$ ctest -R swmr
Test project /Users/sean/external/hdf5-bin
    Start  6: H5TEST-clear-objects
1/4 Test  #6: H5TEST-clear-objects .............   Passed    0.02 sec
    Start 65: H5TEST-swmr
2/4 Test #65: H5TEST-swmr ......................   Passed    0.33 sec
    Start 96: H5SHELL-testswmr
3/4 Test #96: H5SHELL-testswmr .................   Passed  154.97 sec
    Start 97: H5SHELL-testvdsswmr
4/4 Test #97: H5SHELL-testvdsswmr ..............   Passed   24.44 sec

100% tests passed, 0 tests failed out of 4
```

**Comment by hyoklee** [comment]
19 - H5TEST-accum (Failed)

**Comment by seanm** [comment]
I don't reproduce on my Intel Mac with macOS 10.14

I do reproduce with my ARM Mac with macOS 12.1.

I wonder if it's ARM vs Intel or 10.14 vs 12.1....

**Comment by hyoklee** [comment]
No. My Mac is x86_64:
```Darwin nene.ad.hdfgroup.org 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64```

**Comment by seanm** [comment]
OK, let me try on my macOS 11.6.1 bot then...

**Comment by seanm** [comment]
Passes on 11.6.2 (on Intel):

```
builder@builder20 hdf5-bin % sw_vers
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314

builder@builder20 hdf5-bin % uname -a
Darwin builder20.rogue-research.com 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
```

So I guess the difference is macOS 11 to 12.

**Comment by seanm** [comment]
I don't know HDF well, but I know macOS well.  Let me know if I can help.

**Comment by gnuoyd** [comment]
On Mon, Dec 13, 2021 at 06:27:48AM -0800, H. Joe Lee wrote:
> ```
> 19: Testing SWMR write of large metadata: with latest format              *FAILED*
> 19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
> 19: child process exited abnormally
> 19: Testing SWMR write of large metadata: with non-latest-format          *FAILED*
> 19:    at /Users/hyoklee/src/hdf5/test/accum.c:2291 in test_swmr_write_big()...
> 19: child process exited abnormally
> 19: *** TESTS FAILED ***
> ```

What does the test output say about how/why the child process exits?

Dave

**Comment by hyoklee** [comment]
@gnuoyd , how do I get what you want (i.e., test output & how/why child process exists)? I need an official documentation for reporting bugs correctly.

**Comment by gnuoyd** [comment]
On Mon, Jan 10, 2022 at 09:57:22AM -0800, H. Joe Lee wrote:
> @gnuoyd , how do I get what you want (i.e., test output & how/why child process exists)? I need an official documentation for reporting bugs correctly.

When you change to your build directory and run `make check`, each test
generates a file under test/ with `.chklog` suffix.  I think the file to
look for is accum.chklog.

Dave

**Comment by hyoklee** [comment]
> On Mon, Jan 10, 2022 at 09:57:22AM -0800, H. Joe Lee wrote: @gnuoyd , how do I get what you want (i.e., test output & how/why child process exists)? I need an official documentation for reporting bugs correctly.
> When you change to your build directory and run `make check`, each test generates a file under test/ with `.chklog` suffix. I think the file to look for is accum.chklog. Dave

I'm testing using ctest. I can't find `.chklog` file. Any other tip?

**Comment by seanm** [comment]
It mentions `/Users/hyoklee/src/hdf5/test/accum.c:2291`.  Run in lldb and put a breakpoint.

**Comment by gnuoyd** [comment]
On Mon, Jan 10, 2022 at 11:32:15AM -0800, Sean McBride wrote:
> It mentions `/Users/hyoklee/src/hdf5/test/accum.c:2291`.  Run in lldb and put a breakpoint.

That's where the parent catches the error.

Dave

**Comment by hyoklee** [comment]
It still fails as of 2022-08-26.

```
19/2204 Test: H5TEST-accum
Command: "/usr/local/Cellar/cmake/3.24.0/bin/cmake" "-D" "TEST_EMULATOR=" "-D" "TES\
T_PROGRAM=/Users/hyoklee/src/hdf5.HDFGroup/build/bin/accum" "-D" "TEST_ARGS:STRING=\
" "-D" "TEST_EXPECT=0" "-D" "TEST_SKIP_COMPARE=TRUE" "-D" "TEST_OUTPUT=accum.txt" "\
-D" "TEST_LIBRARY_DIRECTORY=/Users/hyoklee/src/hdf5.HDFGroup/build/bin" "-D" "TEST_\
FOLDER=/Users/hyoklee/src/hdf5.HDFGroup/build/test/H5TEST" "-P" "/Users/hyoklee/src\
/hdf5.HDFGroup/config/cmake/runTest.cmake"
Directory: /Users/hyoklee/src/hdf5.HDFGroup/build/test/H5TEST
"H5TEST-accum" start time: Aug 26 12:04 CDT
Output:
----------------------------------------------------------
-- Require TEST_EXPECT to be defined
-- COMMAND:  /Users/hyoklee/src/hdf5.HDFGroup/build/bin/accum
-- COMMAND Result: 1
-- Output :
```
