### ISSUE TITLE
How to convert MARRE_2 data from HDF5 format to CSV format using R?

### ISSUE THREAD

**Issue by MengluXie** [HDFGroup/hdf5#1292]
Hello, all. I have got a MERRA_2 weather data and want to convert it from HDF5 to CSV format using R. If anyone knows what should I do.

**Comment by hyoklee** [comment]
@MengluXie , what R package do you use for reading HDF5?
You have several options (e.g., NCDF4, rgdal, hdf5r) and I'd like to know it first to help you further:

https://hdfeos.org/software/R.php

**Comment by hyoklee** [comment]
Here's a sample script to convert an HDF5 dataset from MERRA2 into CSV.
```
# Install HDF5 R package.
install.packages('hdf5r', repos = "http://cran.us.r-project.org")
library(hdf5r)

# Read the MERRA2 HDF5 file.
file <- h5file('MERRA2_400.tavg1_2d_slv_Nx.20140101.nc4', 'r')
list.datasets(file, recursive=TRUE)
dset <- file[['T500']]
d <- readDataSet(dset)

# Create the .csv file.
filename <- "temp.csv"
write.table(d, file = filename, sep = ",", row.names = FALSE)
```

**Comment by MengluXie** [comment]
Ok, I will try to run it. Thanks for your reply.

**Comment by derobins** [comment]
For the record, questions like this are best asked on the HDF Group forum:

https://forum.hdfgroup.org/
