### ISSUE TITLE
build HDF5 with ZLIB under MSVC 2017 and CMAKE

### ISSUE THREAD

**Issue by jbensabat** [HDFGroup/hdf5#1293]
Hello 
I am trying to build hdf5 (last version) with ZLIB support.
First I successfully built zlib (debug and release) with CMAKE and then I tried to configure the HDF5 cmake 
I provided the location of the zlib include, lib and bin directories but I get the error 

Could NOT find ZLIB (missing: ZLIB_DIR)
even when I provide the path of the zlib directory 

I guess that some cmake file is missing in the zlib directory. 
Is there a way to overcome that ?
best
jac

**Comment by byrnHDF** [comment]
HDF5 is able to use external libs.
There are two defines, <ext-name>_DIR and <ext-name>_ROOT, one of which should work.
Check the CMakeFilters.cmake file and the referenced macros in the config directory for more details.

**Comment by byrnHDF** [comment]
The standard CMake variables should work finding zlib. Please reopen this issue and supply you configuration and log files if there is still a problem.
