### ISSUE TITLE
h5dump: Long option for '--format' not working

### ISSUE THREAD

**Issue by jamtrott** [HDFGroup/hdf5#1298]
When using `h5dump` from HDF5 1.10.5, the documentation states that the `-m` or `--format` option can be used to choose an output format for floating point values. The long version of this option does not appear to work.

That is, given an H5 file `fibre.h5` containing a dataset `/VisualisationVector/0`, the following command works fine and produces the expected results:

```
$ h5dump -m '%.3g' --dataset=/VisualisationVector/0 fibre.h5
HDF5 "fibre.h5" {
DATASET "/VisualisationVector/0" {
   DATATYPE  H5T_IEEE_F64LE
   DATASPACE  SIMPLE { ( 4717, 3 ) / ( 4717, 3 ) }
   DATA {
   (0,0): 0.607,
   (0,1): 0.611,
   (0,2): 0.508,
   (1,0): -0.167,
   (1,1): 0.931,
   ...
```

However, trying to use the long version of the option, `--format`, does not work. Instead, this results in the program help text being printed.
```
$ h5dump --format='%.3g' --dataset=/VisualisationVector/0 fibre.h5
usage: h5dump [OPTIONS] files
  OPTIONS
     -h,   --help         Print a usage message and exit
     -V,   --version      Print version number and exit
--------------- File Options ---------------
     -n,   --contents     Print a list of the file contents and exit
                          Optional value 1 also prints attributes.
...
```

**Comment by jamtrott** [comment]
Also, I think it would be a good idea for the documentation of `h5dump` (https://support.hdfgroup.org/HDF5/doc/RM/Tools/h5dump.htm) to mention that setting the floating point format also automatically sets the column width to print only a single item per line.

This is at least what I have observed, and seems to be a result of the following lines in `h5dump.c`: https://github.com/HDFGroup/hdf5/blob/10450e0491f97d33f2a07076d9346f6fee1c603c/tools/src/h5dump/h5dump.c#L1113-L1117

**Comment by byrnHDF** [comment]
Have you tried --format=%.3g without the quotes?

**Comment by byrnHDF** [comment]
Interesting that the format option is part of the XML control set. Maybe it was originally for XML (therefore the column set) and when it was used for non-xml output the col set was not changed.

**Comment by jamtrott** [comment]
> Have you tried --format=%.3g without the quotes?

I have also tried without the quotes, and it still does not work.

**Comment by byrnHDF** [comment]
I have tested this (no quotes) with current develop and there is no problem.
I will verify with other dev branches.

**Comment by byrnHDF** [comment]
Other dev branches also are fixed.
