### ISSUE TITLE
don't use F03 flags if you're not using F03

### ISSUE THREAD

**Issue by jeffhammond** [HDFGroup/hdf5#1344]
`-stand:f03` tells `ifort` to warn when non-F2003-standard features are used.  You are using `STORAGE_SIZE` from F2008 along with Intel-specific directives (`!$DEC`), so using this option just generates a bunch of pointless warnings.

There is no harm is not setting this option, since `ifort` will default to supporting every feature when you don't specify a standard.

```patch
diff --git a/config/intel-fflags b/config/intel-fflags
index 42c1781991..5bb6d76aa9 100644
--- a/config/intel-fflags
+++ b/config/intel-fflags
@@ -123,7 +123,7 @@ if test "X-ifort" = "X-$f9x_vendor"; then
     # General #
     ###########
 
-    H5_FCFLAGS="$H5_FCFLAGS -stand:f03 -free"
+    H5_FCFLAGS="$H5_FCFLAGS -free"
     H5_FCFLAGS="$H5_FCFLAGS $(load_intel_arguments ifort-general)"
 
     #############################
```

**Comment by derobins** [comment]
Fixed in develop
