### ISSUE TITLE
Use semantic versioning.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#1348]
This was suggested in 2013 but not executed:

https://forum.hdfgroup.org/t/semantic-versioning/3042

If you like the idea, please react with :+1:.

**Comment by derobins** [comment]
Semantic versioning will start with HDF5 2.0.0, which will be the next release line after 1.14.0 and should come out sometime in 2023.

**Comment by conradsnicta** [comment]
related issue, with more info: https://github.com/HDFGroup/hdf5/issues/2
