### ISSUE TITLE
dtransform test failing for char type-- signed integer overflow?

### ISSUE THREAD

**Issue by colleeneb** [HDFGroup/hdf5#1381]
Hello,

On a version of the Intel oneAPI compiler, we're seeing that the dtransform test is failing:
```
> ctest -R H5TEST-dtransform --output-on-failure
Test project /home/bertoni/libhdf5_bug/build_oneapi_cmake
    Start  6: H5TEST-clear-objects
1/2 Test  #6: H5TEST-clear-objects .............   Passed    0.01 sec
    Start 57: H5TEST-dtransform
2/2 Test #57: H5TEST-dtransform ................***Failed    0.02 sec
-- Require TEST_EXPECT to be defined
-- COMMAND:  /home/bertoni/libhdf5_bug/build_oneapi_cmake/bin/dtransform
-- COMMAND Result: 255
-- Output :
Testing Intializing test...                                            PASSED
Testing H5Pget_data_transform (get before set)                         PASSED
Testing H5Pset_data_transform (set with NULL transform)                PASSED
Testing H5Pset_data_transform (set with invalid transform 1)           PASSED
Testing H5Pset_data_transform (set with invalid transform 2)           PASSED
Testing H5Pset_data_transform (set with invalid transform 3)           PASSED
Testing H5Pset_data_transform (set with invalid transform 4)           PASSED
Testing H5Pset_data_transform (set with invalid transform 5)           PASSED
Testing H5Pset_data_transform (set with invalid transform 6)           PASSED
Testing H5Pset_data_transform (set with invalid transform 7)           PASSED
Testing H5Pset_data_transform (set with invalid transform 8)           PASSED
Testing contiguous, no data type conversion (char->char)              *FAILED*

CMake Error at /home/bertoni/libhdf5_bug/hdf5-hdf5-1_12_1/config/cmake_ext_mod/runTest.cmake:124 (message):
  Failed: Test program
  /home/bertoni/libhdf5_bug/build_oneapi_cmake/bin/dtransform exited != 0.
```

After discussing this with Intel, they said that it looks like there is signed integer overflow in the char computation for integer 36 (the first element in transformData) (signed chars have a range from -128 to 127). Since signed integer variables do not have wrap-around behavior in C language, this can produce undefined behavior for the test case.  

They suggest changing the test code in dtransform.c to not rely on wrap-around behavior, i.e. to use smaller values or different formulae. We're still not 100% sure if this is a compiler or test issue, so if you have any insight on this issue, let us know!

**Comment by byrnHDF** [comment]
I have seen this only on our windows test machine with Intel, clang or the VS2109 compiler do not fail.

**Comment by brianwhitney59** [comment]
In the dtransform test, the char->char test has a transform function of (x+100)/4*3 and the inverse of x/3*4-100.  Since char is signed and the first data value is 36, x+100=136, which is larger than 127.  If the functions are rewritten to (x/4+25)*3 and (x/3-25)*4, this would allow the values used for this test to stay in range for signed data.

**Comment by byrnHDF** [comment]
See PR #1415

**Comment by colleeneb** [comment]
Thanks a lot @brianwhitney59 and @byrnHDF !

**Comment by byrnHDF** [comment]
fixed.

**Comment by colleeneb** [comment]
Thank you so much!
