### ISSUE TITLE
Renamed Attribute in dense storage can't be deleted

### ISSUE THREAD

**Issue by kmuehlbauer** [HDFGroup/hdf5#1388]
If I add 

```C
    /* Delete last attribute */
    ret = H5Adelete(dataset, attrname);
    CHECK(ret, FAIL, "H5Adelete");
```

before Dataset close in this test file, the Attribute can't be deleted. This could be another manifestation of https://forum.hdfgroup.org/t/bug-h5arename-fails-unexpectedly/4881

https://github.com/HDFGroup/hdf5/blob/4d45d05078fb1f67cc449fd5a6826c6dcfe55bfe/test/tattr.c#L2807-L2810

More context:

- creation order tracking enabled
- attributes which are created in dense storage can be renamed since this fix https://github.com/HDFGroup/hdf5/commit/4e05249f98d9f7247032cfb6250da654e813f14a
- renamed attributes can't be deleted anymore
- attributes which are not renamed, can be deleted

Conclusion:

Something is going wrong in `H5A__dense_rename`. The above fix was introduced by @vchoi-hdfgroup, so maybe @vchoi-hdfgroup can give some insight here?

 https://github.com/HDFGroup/hdf5/blob/4d45d05078fb1f67cc449fd5a6826c6dcfe55bfe/src/H5Adense.c#L858-L1027

**Comment by kmuehlbauer** [comment]
I've added a possible fix to #1389. The testsuite runs smoothly, and downstream works nicely too.

**Comment by epourmal** [comment]
Thank you for the proposed fix. We will be reviewing it shortly.

**Comment by kmuehlbauer** [comment]
@epourmal Thanks for the heads-up.

**Comment by kmuehlbauer** [comment]
#1389 doesn't solve the problem and I'm not able to fix this. I'd very much appreciate if HDF5 group could prioritize here to find some working solution for this annoying issue. At least a time line would be good.

# HDFFV-10579
- https://forum.hdfgroup.org/t/bug-h5arename-fails-unexpectedly/4881/5

Downstream we constantly get bug reports which can be tracked to this very bug:

# h5netcdf
- https://github.com/h5netcdf/h5netcdf/issues/207
- https://github.com/h5netcdf/h5netcdf/issues/202
- https://github.com/h5netcdf/h5netcdf/issues/179
- https://github.com/h5netcdf/h5netcdf/issues/136
- https://github.com/h5netcdf/h5netcdf/issues/128
- 
# h5py
- https://github.com/h5py/h5py/issues/1641
- https://github.com/h5py/h5py/issues/1385
- https://github.com/h5py/h5py/issues/1185
- https://github.com/h5py/h5py/issues/1180

# other
- https://github.com/jjhelmus/pyfive/issues/46

Downstream already tried to workaround that issue, but finally the problem is only shifted to a later point in hdf5-file lifetime.

C-Examples showing the problem can be found [here](https://github.com/h5py/h5py/issues/1385#issuecomment-1020175316) and [there](https://github.com/h5py/h5py/issues/1385#issuecomment-1021260454).

Beside that issue, thanks for providing such a great library! :100: :+1:

**Comment by kmuehlbauer** [comment]
Great! Thank you very much all involved at HDFGroup for fixing this issue. 🎉 🚀
