### ISSUE TITLE
I failed to build  hdf5-hdf5-1_12_0  with gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

### ISSUE THREAD

**Issue by YINGPENGZH** [HDFGroup/hdf5#1392]
Hi, I failed to build hdf5-hdf5-1_12_0 with gcc 9.3, the error is following, could you help me?

![image](https://user-images.githubusercontent.com/21099446/151126459-ed033ebf-5276-4d5b-8773-7bc4c8d72603.png)

**Comment by derobins** [comment]
Hi,

You'll want to ask about this on the HDF Group forum:

https://forum.hdfgroup.org/

I've never seen an error like that, though.
