### ISSUE TITLE
Ectracting depth images to a folder

### ISSUE THREAD

**Issue by Lane689** [HDFGroup/hdf5#1393]
Hi all, I have h5 file which not have a group or subgroup, just dataset of depth images, here my code for extracting depth images from h5 file to a folder: 

```
import h5py
import numpy as np
import cv2

save_dir = 'C:/Users.../depth_imgs'

with h5py.File('depth.h5', 'r') as hf:
    image_ds = hf
    for imagename in image_ds.keys():
        IMAGE_arr = image_ds[imagename][()]
        cv2.imwrite(f"{save_dir}/{imagename}", IMAGE_arr)
        cv2.waitKey(1000)
        cv2.destroyAllWindows()
```

When I run this code it shows me this error: 

![image](https://user-images.githubusercontent.com/88096949/151150898-e99cf03f-893c-43e0-8a9e-0ef7542ff775.png)

Then I try `print(IMAGE_arr.dtype, IMAGE_arr.shape)` and this gives me a results: 

float32 (2, 600, 400)
float32 (2, 600, 493)
float32 (2, 600, 284)

The first one "2" here refers to two different depth estimates by two different neural networks (one trained on mostly indoor images, and the other on outdoor images).
Because of that I can't imwrite( ) images into a folder while images from seg.h5 (segmentation images) I successfully saved in a folder.
Opencv's imwrite expects (height, width, channels).

I'm wondering is it possible to extract these images to a folder?

**Comment by derobins** [comment]
Hi! Apologies for not getting to this earlier, but questions about HDF5 should be asked on the HDF Group forum:

https://forum.hdfgroup.org/
