### ISSUE TITLE
H5Dchunk_iter offset is not scaled by chunk dimensions

### ISSUE THREAD

**Issue by wenjuno** [HDFGroup/hdf5#1419]
I'm not very sure if this is intentional but I find it inconsistent with `offset` in `H5Dget_chunk_info`.
I think the relevant code for `H5Dchunk_iter` is this:
https://github.com/HDFGroup/hdf5/blob/1d598182d6097052060f15a6b0d744c42a2fd80a/src/H5Dchunk.c#L7519-L7520
Comparing to how the `offset` in `H5Dget_chunk_info` is calculated below, there are missing multipliers of `dset->shared->layout.u.chunk.dim[ii]`:
https://github.com/HDFGroup/hdf5/blob/1d598182d6097052060f15a6b0d744c42a2fd80a/src/H5Dchunk.c#L7347-L7349
In order to use `H5Dchunk_iter` I will need to apply the chunk dimensions multipliers myself. Is this a bug or a conscious design choice? Thanks.

**Comment by mkitti** [comment]
This is an important inconsistency. @gauteh was this intended?

**Comment by gauteh** [comment]
Hm, that was probably not intended: I can see in my library code that I scale it when this function is available, and that I don't scale when I use `chunk_info` directly. 

I also noticed that in https://github.com/HDFGroup/hdf5/blob/1d598182d6097052060f15a6b0d744c42a2fd80a/src/H5Dchunk.c#L7487 the *offset seems to not be written to, that also seems like a bug?

Neither it seems that the offset is set here: https://github.com/HDFGroup/hdf5/blob/1d598182d6097052060f15a6b0d744c42a2fd80a/src/H5Dchunk.c#L7391

**Comment by mkitti** [comment]
> the *offset seems to not be written to, that also seems like a bug?

You're looking at `H5Dget_chunk_info_by_coord` which takes `offset` as an input parameter.

https://docs.hdfgroup.org/hdf5/develop/group___h5_d.html#ga408a49c6ec59c5b65ce4c791f8d26cb0

**Comment by gauteh** [comment]
Doh, of course.

**Comment by mkitti** [comment]
I'll tackle if this unless someone else has started already.
