### ISSUE TITLE
Ninja Error when building HDF5

### ISSUE THREAD

**Issue by ominusliticus** [HDFGroup/hdf5#1425]
### My specs
- OS: Windows 11
- Using Visual Studio 2019
- Compiler: MSVC 
- CMake version: 3.22

### Problem description
I include HDF5 as an external project in my own [project](https://github.com/ominusliticus/VizQGP).
The CMake code that implements this is 
```cmake
set(HDF5_EXTERNALLY_CONFIGURED 1)
set(HDF5_EXTERNAL_LIB_PREFIX "VizQGP")

include(ExternalProject)
set(ExternalProjectCMakeArgs -DHDF5_BUILD_CPP_LIB=ON)

ExternalProject_Add(
    HDF5_Local
    PREFIX "HDF5"
    GIT_REPOSITORY "https://github.com/HDFGroup/hdf5.git"
    GIT_TAG "origin/1.12/master"
    CMAKE_ARGS ${ExternalProjectCMakeArgs}
    SOURCE_DIR "HDF5/HDF5_Local"
    STAMP_DIR  "HDF5/HDF5_Stamp"
    BINARY_DIR "HDF5/HDF5_Build"
    BUILD_ALWAYS ON
    INSTALL_COMMAND ""
)

include_directories(
    "${PROJECT_BINARY_DIR}/ThirdParty/HDF5/HDF5_Local/src"
    "${PROJECT_BINARY_DIR}/ThirdParty/HDF5/HDF5_Local/c++/src"
    "${PROJECT_BINARY_DIR}/ThirdParty/HDF5/HDF5_Build"
)

set(
    _HDF5_LIBS
    "${PROJECT_BINARY_DIR}/ThirdParty/HDF5/HDF5_Build/bin/libhdf5_cpp_D.lib"
    "${PROJECT_BINARY_DIR}/ThirdParty/HDF5/HDF5_Build/bin/libhdf5_D.lib"
    -ldl
)
```
the error that ninja provides me is
```console
ninja : error : build.ninja:6691: multiple rules generate src/shared/shared_gen_SRCS.stamp1 [-w dupbuild=err]
```

I think I have been able to narrow down the source of this error to the following bit of CMake (found in Line: 1109 src/CMakeLists.txt of this repository)
```cmake
add_custom_command (
        OUTPUT     shared/shared_gen_SRCS.stamp1
        COMMAND    ${CMAKE_COMMAND}
        ARGS       -E copy_if_different H5Tinit.c shared/H5Tinit.c
        BYPRODUCTS shared/H5Tinit.c shared/shared_gen_SRCS.stamp1
        COMMAND    ${CMAKE_COMMAND}
        ARGS       -E touch shared/shared_gen_SRCS.stamp1
        DEPENDS H5Tinit.c
        WORKING_DIRECTORY ${HDF5_GENERATED_SOURCE_DIR}
        COMMENT    "Copy existing H5Tinit.c to shared folder"
    )
```
which corresponds to the `ninja` code
```ninja
build src\shared\shared_gen_SRCS.stamp1 src\shared\H5Tinit.c src\shared\shared_gen_SRCS.stamp1: CUSTOM_COMMAND src\H5Tinit.c || bin\H5make_libsettings.exe
  COMMAND = cmd.exe /C "cd /D ...
```

Lastly, the bit of C++ code that I am trying to run I have taken form [here](https://github.com/bast/hdf5-cmake-example/blob/master/src/writedata.cpp). 
Which is just an example program that creates some data and writes it to a file, and reads it in again.

It seems to me that ninja is upset that the file `src\shared\shared_gen_SRCS.stamp1` shows up twice in the build command. Is there something obviously wrong that I have done?

**Comment by byrnHDF** [comment]
We have recently revised that section of code that should fix it. Can you use the hdf5_1_12 branch. The master branch is only used for generating releases, the latest development code is in the develop, hdf5_1_12, hdf5_1_10 and hdf5 1_8 branches. You find the released versions in hdf5_1_12_1, hdf5_1_10_8 and hdf5_1_8_22.

**Comment by ominusliticus** [comment]
Hi,
Thank you!
I had originally switched from develop branch to 1.12/master because its `src` folder was missing the file `H5Edefin.h`.
Switching to the hdf5_1_12 now gives the error that `H5Epubgen.h` cannot be found.

EDIT: It seems this is an auto-generated file. After playing around with my cmake files I finally got it to compile.
Is every file containing the work `pub` in it auto-generated? 
Now the error reads
```console
dependency cycle: 
cmake_object_order_depends_target_hdf5-static -> 
    src/gen_hdf5-static -> 
        src/CMakeFiles/gen_hdf5-static ->
            src/gen_SRCS.stamp1 ->
                src/H5Tinit.c -> 
                    cmake_object_order_depends_target_hdf5-static
```
Note: I have modified the output from being on a single line to multiple, to aid readability.

**Comment by byrnHDF** [comment]
The development branches need to enable the generation of files that are done by the release process for the release branches.
The 1.12 release branches are hdf5_1_12_0, hdf5_1_12_1 and the next will be hdf5_1_12_2.
The 1.12 development branch is hdf5_1_12. In release_docs folder is the file INSTALL_CMake.txt. In that file you will find a number of notes on how to configure and build hdf5. Near the bottom (around line 723) is the section titled "CMake Option Defaults for HDF5". In the subsection "HDF5 Advanced Options" you will find the option "HDF5_GENERATE_HEADERS" - enabling this will generate the headers you want.

**Comment by byrnHDF** [comment]
Having said that, it is curious that you are having problems because for the development branch (hdf5_1_12) the default is ON.

**Comment by byrnHDF** [comment]
One more thing, looking at src/CMakeLists.txt; there is one more requirement for generating the files - PERL.
the perl script files triggered by HDF5_GENERATE_HEADERS are H5err.txt, H5vers.txt and H5overflow.txt.
These files require PERL to generate the headers;
    H5Edefin.h
    H5Einit.h
    H5Epubgen.h
    H5Eterm.h
    H5version.h
    H5overflow.h

**Comment by ominusliticus** [comment]
Hi again, I had to take a break from working on my project.

The contents of my `cmake/config/cacheinit.cmake` file are (still on branch hdf5_1_12)

```cmake
#
# Copyright by The HDF Group.
# All rights reserved.
#
# This file is part of HDF5.  The full HDF5 copyright notice, including
# terms governing use, modification, and redistribution, is contained in
# the COPYING file, which can be found at the root of the source code
# distribution tree, or in https://www.hdfgroup.org/licenses.
# If you do not have access to either file, you may request a copy from
# help@hdfgroup.org.
#
# This is the CMakeCache file.

########################
# EXTERNAL cache entries
########################

set (CMAKE_INSTALL_FRAMEWORK_PREFIX "Library/Frameworks" CACHE STRING "Frameworks installation directory" FORCE)

set (HDF_PACKAGE_EXT "" CACHE STRING "Name of HDF package extension" FORCE)

set (HDF_PACKAGE_NAMESPACE "hdf5::" CACHE STRING "Name for HDF package namespace (can be empty)" FORCE)

set (HDF5_BUILD_CPP_LIB ON CACHE BOOL "Build C++ support" FORCE)

set (HDF5_BUILD_FORTRAN ON CACHE BOOL "Build FORTRAN support" FORCE)

set (HDF5_INSTALL_MOD_FORTRAN "NO" CACHE STRING "Copy FORTRAN mod files to include directory (NO SHARED STATIC)" FORCE)
set_property (CACHE HDF5_INSTALL_MOD_FORTRAN PROPERTY STRINGS NO SHARED STATIC)

set (HDF5_BUILD_GENERATORS ON CACHE BOOL "Build Test Generators" FORCE)

set (HDF5_ENABLE_Z_LIB_SUPPORT ON CACHE BOOL "Enable Zlib Filters" FORCE)

set (HDF5_ENABLE_SZIP_SUPPORT ON CACHE BOOL "Use SZip Filter" FORCE)

set (HDF5_ENABLE_SZIP_ENCODING ON CACHE BOOL "Use SZip Encoding" FORCE)

set (MPIEXEC_MAX_NUMPROCS "4" CACHE STRING "Minimum number of processes for HDF parallel tests" FORCE)

set (HDF5_ENABLE_ALL_WARNINGS ON CACHE BOOL "Enable all warnings" FORCE)

set (HDF_TEST_EXPRESS "2" CACHE STRING "Control testing framework (0-3)" FORCE)

set (HDF5_MINGW_STATIC_GCC_LIBS ON CACHE BOOL "Statically link libgcc/libstdc++" FORCE)

set (HDF5_ALLOW_EXTERNAL_SUPPORT "NO" CACHE STRING "Allow External Library Building (NO GIT TGZ)" FORCE)
set_property (CACHE HDF5_ALLOW_EXTERNAL_SUPPORT PROPERTY STRINGS NO GIT TGZ)

set (ZLIB_TGZ_NAME "ZLib.tar.gz" CACHE STRING "Use HDF5_ZLib from compressed file" FORCE)
set (SZIP_TGZ_NAME "SZip.tar.gz" CACHE STRING "Use SZip from compressed file" FORCE)
set (SZAEC_TGZ_NAME "LIBAEC.tar.gz" CACHE STRING "Use SZip AEC from compressed file" FORCE)
set (USE_LIBAEC ON CACHE BOOL "Use libaec szip replacement" FORCE)

set (ZLIB_PACKAGE_NAME "zlib" CACHE STRING "Name of HDF5_ZLIB package" FORCE)
set (LIBAEC_PACKAGE_NAME "libaec" CACHE STRING "Name of AEC SZIP package" FORCE)
set (SZIP_PACKAGE_NAME "szip" CACHE STRING "Name of SZIP package" FORCE)

#######################
# filter plugin options
#######################
.
.
.
```
Here the three dots at the end indicate cmake for working with different file formats.
There is no line with `HDF_GENERATE_HEADERS`.

I cannot simply add the line as Visual Studio overwrites the file with those from GitHub every time it builds.
(That is unless I fork the hdf5 project and make the change in the repository)

I do have perl installed, and cmake reports being to locate it during configuration.

**Comment by byrnHDF** [comment]
Right, you do not change the source. Instead you provide a list of overrides to the source.
In the config/cmake/scripts directory are files you can copy to your project directory; where the source has been copied or downloaded to.
CTestScript.cmake needs no edits (there are some options that might be useful)
HDF5config.cmake needs no edits as this is the main driver and is the file executed by running:
    ctest -S HDF5config.cmake,BUILD_GENERATOR=VS201764 -C Release -VV -O hdf5.log
Where # BUILD_GENERATOR is one of [Unix, VS2019, VS201964, VS2017, VS201764, VS2015, VS201564] 
HDF5options.cmake have a small set of useful options that can be enabled or disabled. This should be the only file you would need to edit.

**Comment by byrnHDF** [comment]
See the release_docs/INSTALL_CMake.txt file -> II. Quick Step Building HDF5 Libraries with CMake Script Mode

**Comment by ominusliticus** [comment]
Seems I should give that a closer read...

**Comment by ominusliticus** [comment]
Thank you for your help!
I was able to get the example [here](https://github.com/bast/hdf5-cmake-example/blob/master/src/writedata.cpp) to work for me (albeit, it uses some deprecated functions which I had to update).

I think the problem ended up being on my end: the file where I told CMake to look for targets was not the same as where I was telling CMake to build the targets.

**Comment by byrnHDF** [comment]
I believe this is resolved.
