### ISSUE TITLE
Problem with sense of release version check?

### ISSUE THREAD

**Issue by kmccarty-dgi** [HDFGroup/hdf5#1436]
Hi,

Recently HDF5 was updated to be more lenient about checking compatibility between the library version number, versus the version number that was used to compile an executable using the library.  (PR #812)

However, it seems to me that the test is going the wrong way?  As written, the code now has
```
if (H5_VERS_MAJOR != majnum || H5_VERS_MINOR != minnum || H5_VERS_RELEASE > (int)relnum) {
  // complain ...
```

Consider an executable that was built against a shared library HDF5 version 1.10.6 ... for which the H5CHECK macro will dump the call H5check_version(1, 10, 6) into the object code of the compiled executable.

One would think that this executable should also be drop-in compatible with the newer shared library HDF5 version 1.10.8 (presuming that the ABI hasn't changed backwards-incompatibly, which it should not have if the soname hasn't changed).  However, the test above, which runs within the context of the shared library, will see that H5_VERS_RELEASE, which is 8 within the new shared library, is > 6, and therefore will issue the compatibility warning.

This isn't right, is it?  I think that `>` should be `<` there.  The 1.10.8 release notes say

> Now the function first checks that the library release version, in
> major.minor.release, is not older than the version in the headers.

... which sounds like the way I'd expect it to work, but opposite of what the code does.

Thanks for considering!

**Comment by byrnHDF** [comment]
I have spent too much time explaining and contradicting myself on this question - only to come to the conclusion that something is wrong. I will need to go back and look at the history of this change to see why. I thought we removed the relnum check when added the second section to check for compatible releases.

**Comment by byrnHDF** [comment]
The check_version function was improperly half finished, likely a victim of a merge blitz. Anyway, the function should be absolute equal in major and minor. Except for develop all release version should be forward compatible as long as the API usage remains constant. Meaning the application does not use any new APIs introduced for advanced work. Should a release version be flawed (like 1.10) there will be an exception list of release versions that are incompatible. By definition, develop releases are always incompatible.
