### ISSUE TITLE
Do I need to use an mpi compiler wrapper for parallel IO support?

### ISSUE THREAD

**Issue by simon-Leary42** [HDFGroup/hdf5#1447]
Question is self explanatory.
I was wondering if -enable-parallel was enough, or if I have to set $CC to mpicc and such...

**Comment by derobins** [comment]
If mpicc exists, the build will try to use that when you specify --enable-parallel, so in general you don't need to set $CC.

Also, questions about HDF5 are best handled on the HDF Group forum:

https://forum.hdfgroup.org/

**Comment by derobins** [comment]
Also, keep in mind that you may need extra packages if you installed MPI via the package manager. In general, on Ubuntu you need the -dev packages to build software using a given library.
