### ISSUE TITLE
Not enough memory to read data

### ISSUE THREAD

**Issue by ddddddzhang** [HDFGroup/hdf5#1478]
Hi hdfgroup, 

I was reading more than 200 .h5 files in this code. But somehow the job stopped at the 36th .h5 file due to the following error: 
![image](https://user-images.githubusercontent.com/64808601/157373086-b23657a3-27e5-44c2-8b6e-49aa8a9d0b06.png)

In the fun.R, I was just using h5read to read in different variables in my .h5 data. 
I confirmed I have enough memory that can be used. But it seems there is a memory limit when reading .h5 files in r? Do you have suggestions about dealing with this error? Thanks! Also the hdf5 package is latest. Thanks!

D

**Comment by ddddddzhang** [comment]
[slurm-4340236_1_github.txt](https://github.com/HDFGroup/hdf5/files/8211733/slurm-4340236_1_github.txt)
Code I ran is here. Thanks.

**Comment by ddddddzhang** [comment]
Problem solved. The hdf file has no data in some groups.

**Comment by ajelenak** [comment]
Closing since the issue seems resolved with no follow-on discussion.
