### ISSUE TITLE
Cannot open include file: 'H5version.h': No such file or directory (when building dev branches)

### ISSUE THREAD

**Issue by kerim371** [HDFGroup/hdf5#149]
Hi,

When I try to build dev branch I get the following error:
_C:\S\extensions\Proba_fixed\Proba-build\hdf5\src\H5public.h(32,10): fatal error C1083: Cannot open include file: 'H5version.h': No such file or directory [C:\S\extensions\Proba_fixed\Proba-build\hdf5-build\src\H5detect.vcxproj] [C:\S\extensions\Proba_fixed\Proba-build\hdf5.vcxproj]
    Building Custom Rule C:/S/extensions/Proba_fixed/Proba-build/hdf5/src/CMakeLists.txt
    H5make_libsettings.c_

I cant understand why get this error but I get it only when I build HDF5 dev branches.

My configuration is Windows 10 x64, CMake 3.19.0, MSVC 2019 v142 x64, 

**Here is the output from CMake:**
The C compiler identification is MSVC 19.28.29334.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
SOVERSION: 1000.0.0
SOVERSION_TOOLS: 1000.0.0
SOVERSION_CXX: 1000.0.0
SOVERSION_F: 1000.0.0
SOVERSION_HL: 1000.0.0
SOVERSION_HL_CXX: 1000.0.0
SOVERSION_HL_F: 1000.0.0
SOVERSION_JAVA: 1000.0.0
Looking for include file sys/file.h
Looking for include file sys/file.h - not found
Looking for include file sys/ioctl.h
Looking for include file sys/ioctl.h - not found
Looking for include file sys/resource.h
Looking for include file sys/resource.h - not found
Looking for include file sys/socket.h
Looking for include file sys/socket.h - not found
Looking for include file sys/stat.h
Looking for include file sys/stat.h - found
Looking for include files sys/stat.h, sys/time.h
Looking for include files sys/stat.h, sys/time.h - not found
Looking for include files sys/stat.h, sys/types.h
Looking for include files sys/stat.h, sys/types.h - found
Looking for 3 include files sys/stat.h, ..., features.h
Looking for 3 include files sys/stat.h, ..., features.h - not found
Looking for 3 include files sys/stat.h, ..., dirent.h
Looking for 3 include files sys/stat.h, ..., dirent.h - not found
Looking for 3 include files sys/stat.h, ..., setjmp.h
Looking for 3 include files sys/stat.h, ..., setjmp.h - found
Looking for 4 include files sys/stat.h, ..., stddef.h
Looking for 4 include files sys/stat.h, ..., stddef.h - found
Looking for 5 include files sys/stat.h, ..., stdint.h
Looking for 5 include files sys/stat.h, ..., stdint.h - found
Looking for 6 include files sys/stat.h, ..., unistd.h
Looking for 6 include files sys/stat.h, ..., unistd.h - not found
Looking for 6 include files sys/stat.h, ..., io.h
Looking for 6 include files sys/stat.h, ..., io.h - found
Looking for 7 include files sys/stat.h, ..., winsock2.h
Looking for 7 include files sys/stat.h, ..., winsock2.h - found
Looking for 8 include files sys/stat.h, ..., globus/common.h
Looking for 8 include files sys/stat.h, ..., globus/common.h - not found
Looking for 8 include files sys/stat.h, ..., pdb.h
Looking for 8 include files sys/stat.h, ..., pdb.h - not found
Looking for 8 include files sys/stat.h, ..., pthread.h
Looking for 8 include files sys/stat.h, ..., pthread.h - not found
Looking for 8 include files sys/stat.h, ..., srbclient.h
Looking for 8 include files sys/stat.h, ..., srbclient.h - not found
Looking for 8 include files sys/stat.h, ..., string.h
Looking for 8 include files sys/stat.h, ..., string.h - found
Looking for 9 include files sys/stat.h, ..., strings.h
Looking for 9 include files sys/stat.h, ..., strings.h - not found
Looking for 9 include files sys/stat.h, ..., stdlib.h
Looking for 9 include files sys/stat.h, ..., stdlib.h - found
Looking for 10 include files sys/stat.h, ..., memory.h
Looking for 10 include files sys/stat.h, ..., memory.h - found
Looking for 11 include files sys/stat.h, ..., dlfcn.h
Looking for 11 include files sys/stat.h, ..., dlfcn.h - not found
Looking for 11 include files sys/stat.h, ..., inttypes.h
Looking for 11 include files sys/stat.h, ..., inttypes.h - found
Looking for 12 include files sys/stat.h, ..., netinet/in.h
Looking for 12 include files sys/stat.h, ..., netinet/in.h - not found
Looking for 12 include files sys/stat.h, ..., netdb.h
Looking for 12 include files sys/stat.h, ..., netdb.h - not found
Looking for 12 include files sys/stat.h, ..., arpa/inet.h
Looking for 12 include files sys/stat.h, ..., arpa/inet.h - not found
Looking for 12 include files sys/stat.h, ..., stdbool.h
Looking for 12 include files sys/stat.h, ..., stdbool.h - found
Looking for include file quadmath.h
Looking for include file quadmath.h - not found
Looking for gethostname in ucb;
Looking for gethostname in ucb; - not found
Performing Other Test STDC_HEADERS - Success
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of char
Check size of char - done
Check size of short
Check size of short - done
Check size of int
Check size of int - done
Check size of unsigned
Check size of unsigned - done
Check size of long
Check size of long - done
Check size of long long
Check size of long long - done
Check size of __int64
Check size of __int64 - done
Check size of float
Check size of float - done
Check size of double
Check size of double - done
Check size of long double
Check size of long double - done
Check size of int8_t
Check size of int8_t - done
Check size of uint8_t
Check size of uint8_t - done
Check size of int_least8_t
Check size of int_least8_t - done
Check size of uint_least8_t
Check size of uint_least8_t - done
Check size of int_fast8_t
Check size of int_fast8_t - done
Check size of uint_fast8_t
Check size of uint_fast8_t - done
Check size of int16_t
Check size of int16_t - done
Check size of uint16_t
Check size of uint16_t - done
Check size of int_least16_t
Check size of int_least16_t - done
Check size of uint_least16_t
Check size of uint_least16_t - done
Check size of int_fast16_t
Check size of int_fast16_t - done
Check size of uint_fast16_t
Check size of uint_fast16_t - done
Check size of int32_t
Check size of int32_t - done
Check size of uint32_t
Check size of uint32_t - done
Check size of int_least32_t
Check size of int_least32_t - done
Check size of uint_least32_t
Check size of uint_least32_t - done
Check size of int_fast32_t
Check size of int_fast32_t - done
Check size of uint_fast32_t
Check size of uint_fast32_t - done
Check size of int64_t
Check size of int64_t - done
Check size of uint64_t
Check size of uint64_t - done
Check size of int_least64_t
Check size of int_least64_t - done
Check size of uint_least64_t
Check size of uint_least64_t - done
Check size of int_fast64_t
Check size of int_fast64_t - done
Check size of uint_fast64_t
Check size of uint_fast64_t - done
Check size of size_t
Check size of size_t - done
Check size of ssize_t
Check size of ssize_t - failed
Check size of off_t
Check size of off_t - done
Check size of off64_t
Check size of off64_t - failed
Check size of time_t
Check size of time_t - done
Check size of _Bool
Check size of _Bool - done
Looking for alarm
Looking for alarm - not found
Looking for fcntl
Looking for fcntl - not found
Looking for flock
Looking for flock - not found
Looking for fork
Looking for fork - not found
Looking for frexpf
Looking for frexpf - not found
Looking for frexpl
Looking for frexpl - not found
Looking for getrusage
Looking for getrusage - not found
Looking for llround
Looking for llround - found
Looking for llroundf
Looking for llroundf - found
Looking for lround
Looking for lround - found
Looking for lroundf
Looking for lroundf - found
Looking for lstat
Looking for lstat - not found
Looking for pread
Looking for pread - not found
Looking for pwrite
Looking for pwrite - not found
Looking for rand_r
Looking for rand_r - not found
Looking for random
Looking for random - not found
Looking for round
Looking for round - found
Looking for roundf
Looking for roundf - found
Looking for setsysinfo
Looking for setsysinfo - not found
Looking for signal
Looking for signal - found
Looking for setjmp
Looking for setjmp - found
Looking for siglongjmp
Looking for siglongjmp - not found
Looking for sigsetjmp
Looking for sigsetjmp - not found
Looking for sigprocmask
Looking for sigprocmask - not found
Looking for snprintf
Looking for snprintf - not found
Looking for srandom
Looking for srandom - not found
Looking for strtoll
Looking for strtoll - found
Looking for strtoull
Looking for strtoull - found
Looking for symlink
Looking for symlink - not found
Looking for tmpfile
Looking for tmpfile - found
Looking for asprintf
Looking for asprintf - not found
Looking for vasprintf
Looking for vasprintf - not found
Looking for waitpid
Looking for waitpid - not found
Looking for vsnprintf
Looking for vsnprintf - not found
Looking for sigsetjmp
Looking for sigsetjmp - not found
Checking for InitOnceExecuteOnce:
Performing Test InitOnceExecuteOnce - Success
Performing Other Test HAVE_INLINE - Success
Performing Other Test HAVE___INLINE__ - Failed
Performing Other Test HAVE___INLINE - Success
Checking for appropriate format for 64 bit long:
Checking for appropriate format for 64 bit long: found "I64"
Looking for difftime
Looking for difftime - found
Check size of __float128
Check size of __float128 - failed
Check size of _Quad
Check size of _Quad - failed
Checking IF your system converts long double to (unsigned) long values with special algorithm... no
Checking IF your system can convert (unsigned) long to long double values with special algorithm... no
Checking IF correctly converting long double to (unsigned) long long values... yes
Checking IF correctly converting (unsigned) long long to long double values... yes
Checking IF the cpu is power9 and cannot correctly converting long double values... no
Checking IF alignment restrictions are strictly enforced... yes
Warnings Configuration: default:   /DWIN32 /D_WINDOWS /W3 :  
Could NOT find Perl (missing: PERL_EXECUTABLE) 
Cannot generate headers - perl not found
Cannot execute TEST flushrefresh - perl not found
The CXX compiler identification is MSVC 19.28.29334.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Check for STD namespace
Check for STD namespace - found
Looking for C++ include stdint.h
Looking for C++ include stdint.h - found
Performing CXX Test OLD_HEADER_FILENAME - Failed
Performing CXX Test HDF_NO_NAMESPACE - Failed
Performing CXX Test HDF_NO_STD - Failed
Performing CXX Test BOOL_NOTDEFINED - Failed
Performing CXX Test NO_STATIC_CAST - Failed
Performing CXX Test CXX_HAVE_OFFSETOF - Failed
Warnings Configuration: CXX default:    
Configuring done
Generating done

**Comment by byrnHDF** [comment]
dev branch requires the generation of the files, which requires PERL.

option (HDF5_GENERATE_HEADERS "Rebuild Generated Files" ON)
if (HDF5_GENERATE_HEADERS)
  set_source_files_properties(${H5_GENERATED_HEADERS} PROPERTIES GENERATED TRUE)
  find_package (Perl)

**Comment by kerim371** [comment]
@byrnHDF thank you
