### ISSUE TITLE
./configure issue for HDF5 

### ISSUE THREAD

**Issue by jahidhasanlinix** [HDFGroup/hdf5#1501]
I tried with both using  ./configure --prefix=$H5_DIR/install --enable-parallel --enable-threadsafe --enable-unsupported #(tried both with CFLAGS="03" CC=cc or CC=mpicc and --with-zlib) and each time I am having issues to make it run and it give some weird error which already installed in my ubuntu. 
`> sudo ./configure --prefix=$H5_DIR/install --enable-parallel --enable-threadsafe --enable-unsupported CFLAGS="-O3" CC=cc`
(Tried without sudo as well
![Screenshot 2022-03-15 160553](https://user-images.githubusercontent.com/36171973/158472492-d5cb8652-73e6-4aac-b079-5ce594a46c92.png)

Second try:
![Screenshot 2022-03-15 160746](https://user-images.githubusercontent.com/36171973/158472794-4fbc6e2d-b9bc-47a4-8eed-b26a38fc8f63.png)

Any suggestion how to fix this issue. thank you all.

**Comment by derobins** [comment]
The place to ask questions like this is the HDF Group forums:

https://forum.hdfgroup.org/

The output of config.log will be helpful (at least the parts where mpicc checks go awry).
