### ISSUE TITLE
hdf5.pc is incorrect for debug builds

### ISSUE THREAD

**Issue by soumagne** [HDFGroup/hdf5#1546]
Initially reported by @chuckcranor the hdf5.pc file that gets generated by CMake debug builds does not contain the `_debug` suffix that gets added to the library name. HDFMacros.cmake must first be fixed to include `OUTPUT_NAME_DEBUG` in the target name.

```bash
% egrep ^Libs: /tmp/hd/lib/pkgconfig/hdf5.pc
Libs: -L${libdir}  -lhdf5
```
even though:
```bash
% ls /tmp/hd/lib/libhdf5*.so
/tmp/hd/lib/libhdf5_debug.so     /tmp/hd/lib/libhdf5_tools_debug.so
/tmp/hd/lib/libhdf5_hl_debug.so
```

**Comment by byrnHDF** [comment]
Current builds are correct
