### ISSUE TITLE
Error while compiling HDF5 using AOCC compilers (error while loading shared libraries: libomp.so)

### ISSUE THREAD

**Issue by Enea2301** [HDFGroup/hdf5#1588]
Good evening. I'm trying to compile HDF5 using latest AMD AOCC compilers (3.2), but a problem arises constantly while executing the "make" command

**./H5_buildiface: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:1513: H5_gen.F90] Error 127
**

The runtime command for configure is as continues: CC="$CC" CXX="$CXX" FC="$FC" CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" FCFLAGS="$FCFLAGS"  LDFLAGS="$LDFLAGS" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" LIBRARY_PATH="$LIBRARY_PATH" ./configure --with-zlib=$DIR/grib2 --prefix=$DIR/hdf5 --enable-hl --enable-fortran

The referenced bashrc variables:
export DIR=path/to/librariesupperfolder
export DIRAOCC=path/to/AOCCdir
export CC=$DIRAOCC/AOCC/bin/clang
export CXX=$DIRAOCC/AOCC/bin/clang++
export FC=$DIRAOCC/AOCC/bin/flang
export CFLAGS="-m64 -O3 -march=znver2 -mtune=znver2"
export CXXFLAGS="-m64 -O3 -march=znver2 -mtune=znver2"
export FCFLAGS="-m64 -O3 -march=znver2 -mtune=znver2"
export LDFLAGS="-L$DIRAOCC/AOCC/lib -L$DIRAOCC/AOCC/lib32"
export LD_LIBRARY_PATH=$DIRAOCC/AOCC/lib:$DIRAOCC/AOCC/lib32/:$DIRAOCC/AOCC/ompd:/usr/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib:/usr/lib32
export LIBRARY_PATH=$DIRAOCC/AOCC/lib:$DIRAOCC/AOCC/lib32/:/usr/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib:/usr/lib32

Any ideas on why it could be happening?
libomp.so does exist under both ../AOCC/lib and ../AOCC/lib32

**Comment by derobins** [comment]
As a part of making AOCC work better at compiling HDF5, we'll be adding -nomp to flang builds in 1.14.3. That should take care of any OpenMP library issues (we don't use it in HDF5).

**Comment by derobins** [comment]
Fixed w/ #3674
