### ISSUE TITLE
Assertion with certain H5Pset_est_link_info() parameters on group flush / close

### ISSUE THREAD

**Issue by derobins** [HDFGroup/hdf5#1632]
Certain combinations of the est_num_entries and est_name_len parameter values can cause an assertion to be raised in debug builds of the HDF5 library when the group creation property list is used to create groups. The assertion arises when the group's object header is flushed to the disk. We are still characterizing this bug and determining its origin and effects in release builds.

This bug is present in the 1.8, 1.10, 1.12, and develop branches. We're still working to determine the exact version where it was introduced.

Reproducer:

```
int main() {
        hid_t file_id, group_id, plist_id, flist_id;
        herr_t res;

        flist_id = H5Pcreate(H5P_FILE_ACCESS);
        assert(flist_id != H5I_INVALID_HID);
        res = H5Pset_libver_bounds(flist_id, H5F_LIBVER_LATEST, H5F_LIBVER_LATEST);
        assert(res >= 0);

        file_id = H5Fcreate("test.h5", H5F_ACC_TRUNC, H5P_DEFAULT, flist_id);
        assert(file_id != H5I_INVALID_HID);

        plist_id = H5Pcreate(H5P_GROUP_CREATE);
        assert(plist_id != H5I_INVALID_HID);
        res = H5Pset_est_link_info(plist_id, 570, 100);
        assert(res >= 0);

        group_id = H5Gcreate(file_id, "g", H5P_DEFAULT, plist_id, H5P_DEFAULT);
        assert(group_id != H5I_INVALID_HID);

        H5Gclose(group_id);
        H5Pclose(plist_id);
        H5Fclose(file_id);
        H5Pclose(flist_id);
}
```

**Comment by alkino** [comment]
Hello, is there something new on that?
Regards

**Comment by emmenlau** [comment]
We would need that too, kindly pinging this issue before it gets one year old...

**Comment by alkino** [comment]
This bug is still relevant for 1.14.1
