### ISSUE TITLE
Remove Perl dependency.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#1648]
Spack installation of Perl on Mac is problematic:

https://github.com/hyoklee/hdf5/runs/6042719583?check_suite_focus=true

less dependency = more portability

**Comment by derobins** [comment]
As much as I'd be thrilled to remove Perl code from the library, it's used to build from non-release branches.

**Comment by hyoklee** [comment]
Yeah, Perl makes daily performance testing of the latest code commit using Spack on Mac impossible.
