### ISSUE TITLE
test/cross_read.c didn't catch the errors for split, multi, family, splitter drivers and indicates test passed

### ISSUE THREAD

**Issue by vchoi-hdfgroup** [HDFGroup/hdf5#1667]
Testing: cross_read
============================
Test log for cross_read
Virtual file driver (VFD): split
============================

Testing reading data created on Linux
*FAILED*
HDF5-DIAG: Error detected in HDF5 (1.13.2-1) thread 0:
  #000: ../../hdf5/src/H5F.c line 837 in H5Fopen(): unable to synchronously open file
    major: File accessibility
    minor: Unable to open file
  #001: ../../hdf5/src/H5F.c line 797 in H5F__open_api_common(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #002: ../../hdf5/src/H5VLcallback.c line 3686 in H5VL_file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: ../../hdf5/src/H5VLcallback.c line 3498 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #004: ../../hdf5/src/H5VLnative_file.c line 128 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #005: ../../hdf5/src/H5Fint.c line 1809 in H5F_open(): unable to open file: name = '../../hdf5/test/le_data.h5', tent_flags = 0
    major: File accessibility
    minor: Unable to open file
  #006: ../../hdf5/src/H5FD.c line 770 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
*FAILED*
      at ../../hdf5/test/cross_read.c:233 in check_file()...
:
:
:
All data type tests passed.
0.00user 0.00system 0:00.00elapsed 50%CPU (0avgtext+0avgdata 2820maxresident)k
0inputs+8outputs (0major+764minor)pagefaults 0swaps

**Comment by qkoziol** [comment]
I believe that my recent merge addressed this

**Comment by derobins** [comment]
These VFDs are skipped now
