### ISSUE TITLE
test/enc_dec_plist.c got errors but didn't get caught

### ISSUE THREAD

**Issue by vchoi-hdfgroup** [HDFGroup/hdf5#1668]
Test log for enc_dec_plist
Virtual file driver (VFD): sec2
============================
Testing ENCODE/DECODE with file version bounds: (earliest, v18):
Testing Default DCPL Encoding/Decoding                                 PASSED
Testing DCPL Encoding/Decoding                                         PASSED
Testing DCPL Encoding/Decoding for virtual layout                     *** UNEXPECTED VALUE from H5Pencode2 should be -1, but is 0 at line   49 in ../../hdf5/test/enc_dec_plist.c
Testing Default DAPL Encoding/Decoding                                 PASSED
Testing DAPL Encoding/Decoding                                         PASSED
Testing Default OCPL Encod
:ing/Decoding                                 PASSED
Testing OCPL Encoding/Decoding                                         PASSED
Testing Default DXPL Encoding/Decoding                                 PASSED
:
:
:
Testing Default STRCPL Encoding/Decoding                               PASSED
Testing STRCPL Encoding/Decoding                                       PASSED
Testing Default ACPL Encoding/Decoding                                 PASSED
Testing ACPL Encoding/Decoding                                         PASSED
0.06user 0.00system 0:00.07elapsed 97%CPU (0avgtext+0avgdata 3084maxresident)k
0inputs+48outputs (0major+848minor)pagefaults 0swaps

Finished testing enc_dec_plist

**Comment by derobins** [comment]
Fixed in develop (#2325)
