### ISSUE TITLE
H5Pset_efile_prefix documentation error

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#1759]
[External datasets relative to current directory or HDF5 file as documented?](https://forum.hdfgroup.org/t/external-datasets-relative-to-current-directory-or-hdf5-file-as-documented/9742)

> Examining the source code indicates the default prefix is the current directory of the program and NOT “the same directory as the HDF5 file”.

**Comment by mkitti** [comment]
Thanks, Gerd. To clarify the situation, the existing and intended behavior is that the default external dataset prefix is the current working directory of the calling program's current process. This is the case when the prefix is not set, set to an empty string, or set to `"."` via [`H5Pset_efile_prefix`](https://docs.hdfgroup.org/hdf5/v1_8/group___d_a_p_l.html#ga442647d48171db920c71a7baf6fdeee6).

To make the location of the external dataset file relative to the HDF5 file, the misdocumented default, `H5Pset_efile_prefix` should be set to `"${ORIGIN}"`.

**Comment by mkitti** [comment]
I believe this is the text that needs to be edited.

https://github.com/HDFGroup/hdf5/blob/a124f02f2c94476f58e4bca047e7786a3231cf0c/src/H5Ppublic.h#L7351-L7353
