### ISSUE TITLE
hdf5 1.8.22 parallel Fortran interface is broken with CMake

### ISSUE THREAD

**Issue by pab42** [HDFGroup/hdf5#1810]
Related to https://github.com/spack/spack/issues/31085 : the parallel Fortran interface in hdf 1.8.22 is broken for compilation:
```
mpifort ph5example.f90 -Iopt/spack/linux-sles15-haswell/gcc-11.2.0/hdf5-1.8.22-eqz3y6v6ibvvirocnnphhq6aa63czcwd/include -Lopt/spack/linux-sles15-haswell/gcc-11.2.0/hdf5-1.8.22-eqz3y6v6ibvvirocnnphhq6aa63czcwd/lib -lhdf5_fortran -lhdf5
/usr/bin/ld: /tmp/ccV3VZVL.o: in function `MAIN__':
ph5example.f90:(.text+0x33c): undefined reference to `h5pset_fapl_mpio_f_'
/usr/bin/ld: ph5example.f90:(.text+0x6ae): undefined reference to `h5pset_dxpl_mpio_f_'
collect2: error: ld returned 1 exit status
```
I attached all log files from spack but the error also appears without spack only using plain CMake with the same arguments. I also checked with Intel MPI/Compilers, no difference. Is there any chance this still will be fixed? We have quite a few users who still rely on 1.8.x.

[spack-configure-args.txt](https://github.com/HDFGroup/hdf5/files/8898448/spack-configure-args.txt)
[spack-build-01-cmake-out.txt](https://github.com/HDFGroup/hdf5/files/8898441/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/HDFGroup/hdf5/files/8898442/spack-build-02-build-out.txt)
[spack-build-03-install-out.txt](https://github.com/HDFGroup/hdf5/files/8898445/spack-build-03-install-out.txt)
[spack-build-env.txt](https://github.com/HDFGroup/hdf5/files/8898446/spack-build-env.txt)
[spack-build-out.txt](https://github.com/HDFGroup/hdf5/files/8898447/spack-build-out.txt)

**Comment by derobins** [comment]
Closing this as 1.8 is no longer supported
