### ISSUE TITLE
h5cc is severely lacking when building hdf5 with cmake, breaking downstream users

### ISSUE THREAD

**Issue by BtbN** [HDFGroup/hdf5#1814]
When building hdf5 with autotools, the following file is used to produce h5cc and friends:
https://github.com/HDFGroup/hdf5/blob/develop/bin/h5cc.in

However, when building with cmake, the following file is used for it:
https://github.com/HDFGroup/hdf5/blob/develop/config/cmake/libh5cc.in

It is massively less complex, but also lacking a bunch of stuff.
So far, I have noticed the following two major issues:

A whole bunch of downstream users call "h5cc -show" in their configure scripts. That option is plain gone and gets passed to gcc if you use the cmake version, leading to various hilariously broken configure and build results (for example: slurm finishes configure, but produces a Makefile with syntax-errors).
I have so far only noticed -show being missing, but there's a bunch of other missing options that might cause issues if some downstream user relies on them.

Additionally:
The cmake version has "$dir/lib/libhdf5.settings" hardcoded in. So if things got installed into lib64, it breaks as well.

**Comment by byrnHDF** [comment]
CMake hdf5 uses pkgconfig as requested. (h5cc uses that also) see https://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by BtbN** [comment]
Yes, if a downstream would use pkg-config, it'd still work.
However, at least one of them (and probably more) doesn't, and relies on calling "h5cc -show".
The behaviour of h5cc changing dramatically based on the build system hdf5 was built with is very unexpected.

As of right now, slurm cannot be built against a cmake built hdf5, but works just fine with the same version built via autotools.

**Comment by m214089** [comment]
We are having the same issue. And a remark: if the man page for a tool is giving you options which are not available anymore, the man page has to changed too. As well, this changes need to be mentioned in the release notes.

**Comment by byrnHDF** [comment]
CMake h5cc changes have been noted in the Release.txt at the time of change - archived copy should exist in the history files.

**Comment by byrnHDF** [comment]
I am not aware of a man page.
