### ISSUE TITLE
Replace all sprintf with safer snprintf

### ISSUE THREAD

**Issue by seanm** [HDFGroup/hdf5#1824]
Even after https://github.com/HDFGroup/hdf5/pull/1815 there are 16 remaining uses of HDsprintf() left. They were a bit too tricky for me to confidently change as I don't know the codebase well.

**Comment by seanm** [comment]
@jhendersonHDF

**Comment by seanm** [comment]
I took another stab at this, and was disappointed to see there are *more* sprintf than there used to be.

Anyway, I fixed more of them. After [this](https://github.com/HDFGroup/hdf5/pull/4003) there is only 1 left!

**Comment by jhendersonHDF** [comment]
Thanks @seanm, I'd forgotten about this; will review.

**Comment by derobins** [comment]
All done. Yay!
