### ISSUE TITLE
Inconsistency between code and comment/error message

### ISSUE THREAD

**Issue by iamthad** [HDFGroup/hdf5#1844]
https://github.com/HDFGroup/hdf5/blob/3ed53d17fb018c0415be2d668c6765217deff16f/src/H5Fint.c#L2710-L2713

Both the comment and the error message printed on failure talk about setting the character encoding, but it appears that the actual operation is to set the internal `want_posix_fd` flag so that file descriptor can be retrieved below.

**Comment by jhendersonHDF** [comment]
Thanks for reporting! Created a quick PR to fix the comment.
