### ISSUE TITLE
H5Dopen2 incorrect brief description

### ISSUE THREAD

**Issue by iamthad** [HDFGroup/hdf5#1914]
The [brief description](https://github.com/HDFGroup/hdf5/blob/develop/src/H5Dpublic.h#L372) of `H5Dopen2` is identical to that of `H5Dcreate2`: "Creates a new dataset and links it into the file." This is inconsistent with the [detailed description](https://docs.hdfgroup.org/hdf5/develop/group___h5_d.html#ga04198c4cf0b849ed3a8921f6c7169ee2), which indicates that it opens an existing dataset.

**Comment by derobins** [comment]
Fixed in develop. Thanks!
