### ISSUE TITLE
H5Gget_objtype_by_idx returns the linked object type instead of H5G_LINK

### ISSUE THREAD

**Issue by wenjuno** [HDFGroup/hdf5#1917]
I tested it with HDF5 1.10.7, 1.12.1 and 1.13.1. With 1.10.6 the function returns H5G_LINK for soft link, hard link and external link but with 1.12.1 and 1.13.1 it returns the type of the linked object (e.g. H5G_DATASET if the link points to a dataset). Is it an intentional change or a regression? Thanks.

**Comment by cronhan** [comment]
I also ran into this now after upgrading from 1.10 -> 1.12, albeit "indirectly" via `H5Location::getObjTypeByIdx` which now throws an exception for dangling links instead of just returning the type as it should. Not sure how to work around the problem :(

**Comment by bmribler** [comment]
@cronhan @wenjuno Do you happen to have the minimal repro code?

**Comment by wenjuno** [comment]
Hi @bmribler, I don't remember where I saved my code. I think I just made a file with different link types and wrote a simple program to print the output from the API.

**Comment by bmribler** [comment]
@wenjuno @cronhan 

I'm sorry to let you know that we've decided not to fix this issue.

Returning H5G_LINK was an incorrect behavior of H5Gget_objtype_by_idx().  The function was to return the "object type" and H5G_link was not a type of an object.  That was the reason that H5Gget_objtype_by_idx() was changed in the first place.  The incorrect behavior will not be put back into this deprecated function.  Applications, which use H5Lget_info_by_idx() to get link type, will need to be modified to use [H5Lget_info_by_idx()](https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/documentation/doxygen/group___h5_l.html#ga4db00b8b944eae68233438165c784b67).  Please also see the note in [H5Gget_objtype_by_idx()](https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_5/documentation/doxygen/group___h5_g.html#gab1383b8cca3fa99410ad36427059c5a7).

**Comment by wenjuno** [comment]
Thanks for the update.
