### ISSUE TITLE
SZ filter target name is wrong.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#195]
h5ex_d_szf should be h5ex_d_sz.

**Comment by byrnHDF** [comment]
This will need to be in all the branches including 1.8.22 release.

**Comment by lrknox** [comment]
It’s in 1.8.22 now.  I thought I was pushing to hdf5_1_8_22 in my fork to create a PR, but “git push” sent it to canonical instead of to origin.  Apparently with multiple remotes the default behavior can change.

I’ll cherry-pick the SZ filter change to PRs for 1.12, 1.10 and 1.8 shortly.

Larry
