### ISSUE TITLE
[Feature Request] H5P documention shoud have a listing of H5P functions

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#1950]
In the updated documentation for H5P:

https://docs.hdfgroup.org/hdf5/develop/group___h5_p.html

The APIs are grouped into modules:

  | Attribute and Link Creation Properties
  | Dataset Access Properties
  | Dataset Creation Properties
  | Dataset Transfer Properties
  | File Access Properties
  | File Creation Properties
  | General Access Properties
  | General Property List Operations
  | General Property List Operations (Advanced)
  | Group Creation Properties
  | Link Access Properties
  | Map Access Properties
  | Object Copy Properties
  | Object Creation Properties

But odds are users will not know what category the function they are interested in belongs to.

So, there should also be a list in the table of contents of all the H5P functions.

**Comment by byrnHDF** [comment]
Added common tables in develop, now H5P RM page has lists of functions.
