### ISSUE TITLE
Build hdf5 version 1.12.2 on redhat 8 with cmake and Intel oneapi

### ISSUE THREAD

**Issue by jbensabat** [HDFGroup/hdf5#1965]
Hello 
I am trying to build hdf5 as detailed above.
this is what I do  

CMake-hdf5-1.12.2]$ ctest -S HDF5config.cmake,MPI=false,BUILD_GENERATOR=Unix -C Release -V -O hdf5.log
-- Dashboard script uname output: Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64

-- Dashboard script configuration:
  CTEST_SITE=[fladsmodel]
  CTEST_BUILD_NAME=[Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64]
  CTEST_SOURCE_DIRECTORY=[/home/jacob_be/hdf5/CMake-hdf5-1.12.2/hdf5-1.12.2]
  CTEST_BINARY_DIRECTORY=[/home/jacob_be/hdf5/CMake-hdf5-1.12.2/build]
  CTEST_CMAKE_GENERATOR=[Unix Makefiles]
  CTEST_CONFIGURATION_TYPE=[Release]
  CTEST_GIT_COMMAND=[]
  CTEST_CHECKOUT_COMMAND=[]
  CTEST_CONFIGURE_COMMAND=["/usr/bin/cmake" -C "/home/jacob_be/hdf5/CMake-hdf5-1.12.2/hdf5-1.12.2/config/cmake/cacheinit.cmake" -DCMAKE_BUILD_TYPE:STRING=Release  -DBUILD_SHARED_LIBS:BOOL=ON -DHDF5_BUILD_FORTRAN:BOOL=ON -DHDF5_BUILD_JAVA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/home/jacob_be/hdf5/CMake-hdf5-1.12.2/HDF_Group/HDF5/1.12.2 -DHDF5_ALLOW_EXTERNAL_SUPPORT:STRING=TGZ -DTGZPATH:PATH=/home/jacob_be/hdf5/CMake-hdf5-1.12.2 -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_BUILD_CPP_LIB:BOOL=OFF -DHDF5_BUILD_JAVA:BOOL=OFF -DHDF5_ENABLE_THREADSAFE:BOOL=OFF -DHDF5_PACKAGE_EXTLIBS:BOOL=ON -DSITE:STRING=fladsmodel -DBUILDNAME:STRING=Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64 -DCTEST_USE_LAUNCHERS:BOOL=ON "-GUnix Makefiles" "" "-TIntel C++ Compiler 17.0" "/home/jacob_be/hdf5/CMake-hdf5-1.12.2/hdf5-1.12.2"]
  CTEST_SCRIPT_DIRECTORY=[/home/jacob_be/hdf5/CMake-hdf5-1.12.2]
  CTEST_USE_LAUNCHERS=[1]

Run dashboard with model Experimental
   Source directory: /home/jacob_be/hdf5/CMake-hdf5-1.12.2/hdf5-1.12.2
   Build directory: /home/jacob_be/hdf5/CMake-hdf5-1.12.2/build
   Group: Experimental
   Reading ctest configuration file: /home/jacob_be/hdf5/CMake-hdf5-1.12.2/hdf5-1.12.2/CTestConfig.cmake
   Site: fladsmodel
   Build name: Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64
   Use Experimental tag: 20220803-0710
Configure project
   Each . represents 1024 bytes of output
    . Size of output: 0K
Error(s) when configuring the project
Build project
   Each symbol represents 1024 bytes of output.
    . Size of output: 0K
Error(s) when building project
   1 Compiler errors
   0 Compiler warnings
Test project /home/jacob_be/hdf5/CMake-hdf5-1.12.2/build
No tests were found!!!

any help would really be appreciated
best
jac

**Comment by derobins** [comment]
The best place to ask questions like this is the HDF Group forum:

https://forum.hdfgroup.org/

**Comment by jbensabat** [comment]
Thanks
Will try there

Sent from my iPhone

On 4 Aug 2022, at 21:04, Dana Robinson ***@***.***> wrote:

﻿

The best place to ask questions like this is the HDF Group forum:

https://forum.hdfgroup.org/
