### ISSUE TITLE
[BUG] Unknown CMake command "IDE_GENERATED_PROPERTIES"

### ISSUE THREAD

**Issue by liam-clink** [HDFGroup/hdf5#2075]
**Describe the bug**
Cannot build library because cmake files are missing the IDE_GENERATED_PROPERTIES macro.

**Expected behavior**
Successful build, as I'm trying to build a release version 

**Platform (please complete the following information)**
 - HDF5 version [hdf5-1_13_2](https://github.com/HDFGroup/hdf5/releases/tag/hdf5-1_13_2)
 - OS and version Windows 10
 - Compiler and version  MSVC 19.32.31332.0
 - Build system and version (CMake 3.24.1 and NMake 14.32.31332.0)
 - Any configure options you specified None
 - MPI library and version (parallel HDF5) Not trying to link against MPI and error isn't related to this

**Comment by byrnHDF** [comment]
IDE_GENERATED_PROPERTIES macro is in the config/cmake_ext_mod/HDFMacros.cmake file.

**Comment by byrnHDF** [comment]
Without a log file showing the error and invocation, it is hard to diagnose anything further.

**Comment by liam-clink** [comment]
What log file should I provide?

**Comment by byrnHDF** [comment]
First, how are you building, from a command line?

**Comment by byrnHDF** [comment]
The IDE_GENERATED_PROPERTIES macro exists in config/cmake and that folder is added to the cmake module include path in the root CMakeLists.cmake. 
This problem cannot be reproduced.
