### ISSUE TITLE
[DOC] Cannot link with shared build

### ISSUE THREAD

**Issue by chacha21** [HDFGroup/hdf5#2103]
HDF5 at least 1.12.2, Windows 64 bits, latest Visual Studio 2019

I built both static and shared HDF5 lib.
When linking with the static build (libhdf5.lib), everything is fine.
When linking with the shared build (hdf5.lib), missing symbols occur (see below)

What am I supposed to do ?

```
main.obj : error LNK2020: jeton non résolu (0A000459) H5E_NOSPACE_g
1>EXHDF5.obj : error LNK2020: jeton non résolu (0A000242) H5E_NOSPACE_g
1>main.obj : error LNK2020: jeton non résolu (0A000451) H5P_CLS_DATASET_CREATE_ID_g
1>EXHDF5.obj : error LNK2020: jeton non résolu (0A000245) H5P_CLS_DATASET_CREATE_ID_g
1>main.obj : error LNK2020: jeton non résolu (0A00041D) H5P_CLS_FILE_ACCESS_ID_g
1>EXHDF5.obj : error LNK2020: jeton non résolu (0A00024B) H5P_CLS_FILE_ACCESS_ID_g
1>main.obj : error LNK2020: jeton non résolu (0A00035C) H5T_NATIVE_UCHAR_g
1>EXHDF5.obj : error LNK2020: jeton non résolu (0A000265) H5T_NATIVE_UCHAR_g
1>main.obj : error LNK2020: jeton non résolu (0A000370) H5E_ERROR_g
1>EXHDF5.obj : error LNK2020: jeton non résolu (0A000270) H5E_ERROR_g
1>EXHDF5.obj : error LNK2001: symbole externe non résolu H5T_NATIVE_UCHAR_g
1>main.obj : error LNK2001: symbole externe non résolu H5T_NATIVE_UCHAR_g
1>EXHDF5.obj : error LNK2001: symbole externe non résolu H5E_ERROR_g
1>main.obj : error LNK2001: symbole externe non résolu H5E_ERROR_g
1>EXHDF5.obj : error LNK2001: symbole externe non résolu H5P_CLS_FILE_ACCESS_ID_g
1>main.obj : error LNK2001: symbole externe non résolu H5P_CLS_FILE_ACCESS_ID_g
1>EXHDF5.obj : error LNK2001: symbole externe non résolu H5P_CLS_DATASET_CREATE_ID_g
1>main.obj : error LNK2001: symbole externe non résolu H5P_CLS_DATASET_CREATE_ID_g
1>EXHDF5.obj : error LNK2001: symbole externe non résolu H5E_NOSPACE_g
1>main.obj : error LNK2001: symbole externe non résolu H5E_NOSPACE_g
1>E:\SFT\code\Sandbox\TestHDF5\Debug\x64\TestHDF5.exe : fatal error LNK1120: 15 externes non résolus
```

**Comment by chacha21** [comment]
Same behaviour when trying to link to Debug or Release builds.

A binary  lookup in both hdf5[_D].lib and hdf5[_D].dll reveals those symbols, though.
What could prevent the linker from finding them ?

[edit]
When H5_BUILT_AS_DYNAMIC_LIB  is not defined, dllspec(dllexport) is not prepended to those symbols, and the symbol name decoration is not the same in the binary files

**Comment by chacha21** [comment]
It can be fixed by defining the Preprocessor macro `H5_BUILT_AS_DYNAMIC_LIB` in the project linking with HDF5
Is it documented anywhere ?

The only mention I can find is here [https://www.hdfgroup.org/downloads/hdf5/](https://www.hdfgroup.org/downloads/hdf5/)

**Comment by byrnHDF** [comment]
> It can be fixed by defining the Preprocessor macro `H5_BUILT_AS_DYNAMIC_LIB` in the project linking with HDF5 Is it documented anywhere ?
> 
> The only mention I can find is here https://www.hdfgroup.org/downloads/hdf5/

realease_docs/INSTALL_Windows.txt: last paragraph.

**Comment by chacha21** [comment]
> realease_docs/INSTALL_Windows.txt: last paragraph.

Ok, my fault. It is also quoted in "USING_HDF5_VS".
However, I might suggest to mention it in some new "linking with HDF5" doc file because :

- "INSTALL" suggests that it is related to precompiled builds or deployment of the binaries, not the linking per se
- "USING_HDF5_VS" suggests that it is related to building HDF5 with Visual Studio

**Comment by byrnHDF** [comment]
Will add that to my todo list. Just need to find the appropriate locations.
