### ISSUE TITLE
Remove the useless "Mind the gap" sentence.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2135]
Why does it exist?

See https://docs.hdfgroup.org/hdf5/develop/_r_m.html.

**Comment by brtnfld** [comment]
Also remove "Break a leg" , we should not be using English idioms.

**Comment by brtnfld** [comment]
And Colin Powell is quoted as "you break it, you own it", not the phrase mentioned here.
Also, _(Not the free function du jour!)_ is, I'm assuming, referring to not using various C standard free functions,  but again, this might not come across for non-native English speakers.

**Comment by hyoklee** [comment]
Reference manual should be 3C - Clear, Concise, Consistent.
