### ISSUE TITLE
Use \code instead of \Code.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2151]
**Describe the bug**

The current Doxygen-related command comment block generates too many (370K~) lines of warnings.
Here's an example.

```
./H5public.h:828:23: warning: unknown command tag name 'Code'; did you mean
      'code'? [-Wdocumentation-unknown-command]
 *            <tr><td>\Code{H5resize_memory(buffer, size)}</td>
                      ^~~~~~
                       code
```

**Expected behavior**

0 warnings.

**Platform (please complete the following information)**
 - HDF5 version: develop branch
 - OS and version: macOS Mont.
 - Compiler and version: clang-1400.0.29.102
 - Build system (e.g. CMake, Autotools) and version: autotools by brew
 - Any configure options you specified: -Weverything for CFLAGS.
 - MPI library and version (parallel HDF5): n/a

**Additional context**

n/a

**Comment by byrnHDF** [comment]
That is not a bug. "\Code" is an alias in the doxygen/aliases file;
```
ALIASES += THG="The HDF Group"

################################################################################
# Styling
################################################################################

ALIASES += Bold{1}="<b>\1</b>"
ALIASES += Emph{1}="<em>\1</em>"
ALIASES += Code{1}="<tt>\1</tt>"

################################################################################
# Return values
################################################################################

```

**Comment by hyoklee** [comment]
@byrnHDF Can we use a different alias that make clang happy? Also, why `Code` for `tt` instead of `Teletype`?

**Comment by bmribler** [comment]
> @byrnHDF Can we use a different alias that make clang happy? Also, why `Code` for `tt` instead of `Teletype`?

@hyoklee @byrnHDF @derobins Should I use H5Code or H5_code or something else?

**Comment by bmribler** [comment]
> > @byrnHDF Can we use a different alias that make clang happy? Also, why `Code` for `tt` instead of `Teletype`?
> 
> @hyoklee @byrnHDF @derobins Should I use H5Code or H5_code or something else?

Thought?
