### ISSUE TITLE
CMake config depends on MPI but does not find it

### ISSUE THREAD

**Issue by svenevs** [HDFGroup/hdf5#2176]
**Describe the bug**
The hdf5 library code installed had `#include` statments looking for MPI that could not be found.

Redirected CC @jhendersonHDF if interested.

https://github.com/hpc-io/vfd-gds/issues/8#issuecomment-1284521787

If I compile `hdf5 +mpi` (specifically 1.13.2 via spack with OpenMPI), my consuming cmake code should only need to `find_package(HDF5 CONFIG REQUIRED)` and I link against `hdf5-static|shared`.  I should not have to `find_package(MPI REQUIRED)` and link against it in addition.

**Expected behavior**
If mpi is a dependency of hdf5, hdf5's CMake should find that dependency.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): 1.13.2
 - OS and version: multiple linux
 - Compiler and version: multiple gcc
 - Build system (e.g. CMake, Autotools) and version: `spack`
 - Any configure options you specified: I do not have access to these anymore.
 - MPI library and version (parallel HDF5): OpenMPI

**Comment by lrknox** [comment]
followed link https://github.com/hpc-io/vfd-gds/issues/8#issuecomment-1284521787 near the top, which in later comments implies it was resolved.  Also ran "spack install hdf5-vfd-gds" which seemed to be the package that reported the problem.  It built with no issues.
