### ISSUE TITLE
1.10.7 - Pkgconfig on cmake build incomplete (RHEL 7.8 (Toss3))

### ISSUE THREAD

**Issue by dmageeLANL** [HDFGroup/hdf5#218]
Here are the files in $prefix/lib/pkgconfig when building with cmake:

``` bash
~ ls lib/pkgconfig
hdf5-1.10.7.pc  hdf5_fortran-1.10.7.pc  hdf5_hl-1.10.7.pc
```

It's missing the fortran_hl config file.  Also the pc files themselves point at a pc file that isn't there:

``` bash 
~ cat lib/pkgconfig/hdf5_hl-1.10.7.pc
prefix=/usr/projects/hpcsoft/toss3/kodiak/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: hdf5_hl
Description: HDF5 (Hierarchical Data Format 5) Software Library
Version: 1.10.7

Cflags: -I${includedir}
Libs: -L${libdir}  -lhdf5_hl
Requires: hdf5
Libs.private:   -lhdf5_hl
Requires.private: hdf5
~
~ cat lib/pkgconfig/hdf5_fortran-1.10.7.pc
prefix=/usr/projects/hpcsoft/toss3/kodiak/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: hdf5_fortran
Description: HDF5 (Hierarchical Data Format 5) Software Library
Version: 1.10.7

Cflags: -I${includedir}
Libs: -L${libdir}  -lhdf5_fortran
Requires: hdf5
Libs.private:   -lhdf5_fortran
Requires.private: hdf5
```

There's no hdf5.pc file so the compiler wrappers h5fc and h5hlcc are broken.

Also there is no h5hlfc wrapper in bin which is confusing considering there are fortran hl libraries and h5hlcc exists in bin.

**Comment by byrnHDF** [comment]
The hdf5_hl_fortran-1.10.7.pc file is now in source.
The "Requires.private: hdf5" should be "Requires.private: hdf5-1.10.7"? What about "Requires: hdf5"?

Allen

**Comment by byrnHDF** [comment]
If I add the "-1.10.7" to both the "Requires" and "Requires.private" will static linking work? If I understand the pkg_config docs correctly, the ".private" settings are for static linking.

**Comment by dmageeLANL** [comment]
Sure, both should work as far as I know.  You call them as inputs to the pkg config command in the cmake wrappers so that's why they're important from my POV.  So if you add the suffix to the pkg config files, that will fix that issue.  Then there's just he issue of the missing config and wrapper.  

I can test it to confirm the functionality if you provide a final commit hash I can point to.

**Comment by byrnHDF** [comment]
The commit is currently the last one: https://github.com/HDFGroup/hdf5/commit/497e8382cd1e40864843991d19ebc0d19a206dcf

**Comment by dmageeLANL** [comment]
I tested it out and it looks good.  Thanks!

-Dan
