### ISSUE TITLE
how to cross-compile it using aarch64-linux-musl toolchain?please help me

### ISSUE THREAD

**Issue by cbldlpl** [HDFGroup/hdf5#2206]
Is there any reference documentation, I don't know where to start, or has anyone had success with it?

**Comment by giordano** [comment]
Related issues: #1203  #1948

**Comment by cbldlpl** [comment]
> Related issues: #1203 #1948

thks a lot.I will try to compile hdf5 with references later this week.It seems that I have some ideas about it.And I will update here.

**Comment by hyoklee** [comment]
Here's a working example: https://github.com/hyoklee/hdf5/actions/runs/3516693293

**Comment by cbldlpl** [comment]
this part of work is done.Show in this page:[https ://github.com/hyoklee/hdf5/actions/runs/3516693293](https://github.com/hyoklee/hdf5/actions/runs/3516693293)
thank you!

> 这是一个工作示例：[https ://github.com/hyoklee/hdf5/actions/runs/3516693293](https://github.com/hyoklee/hdf5/actions/runs/3516693293)

**Comment by cbldlpl** [comment]
well done!
