### ISSUE TITLE
Garbage characters in configure.ac at line 627 on 1.13.3 release.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2253]
**Describe the bug**
It has invisible 3 characters although it appears empty line.

`configure` will fail w/ `--enable-fortran` [as reported by a forum user](https://forum.hdfgroup.org/t/error-when-running-configure-during-install-of-hdf5-missing-dummy-main/10477/2).

**Comment by brtnfld** [comment]
I don't see any hidden characters in develop or hdf5_1_14, it was fixed with #1922
