### ISSUE TITLE
[BUG] CMake generated pkg-config file is incorrect in multiple ways

### ISSUE THREAD

**Issue by haampie** [HDFGroup/hdf5#2259]
**Describe the bug**

When I build a static version of `zlib` and `hdf5`, for instance using Spack:

```
hdf5@1.12.2%gcc@11.2.0~cxx~fortran~hl~ipo~java+mpi~shared~szip~threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo arch=linux-ubuntu22.04-zen2
    ^cmake@3.24.3%gcc@11.2.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-zen2
    ^openmpi@4.1.4%gcc@11.2.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-ubuntu22.04-zen2
    ^pkgconf@1.8.0%gcc@11.2.0 build_system=autotools arch=linux-ubuntu22.04-zen2
    ^zlib@1.2.13%gcc@11.2.0+optimize+pic~shared build_system=makefile arch=linux-ubuntu22.04-zen2
```

I get a nonsensical pkg-config file:

```
prefix=/home/harmen/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/hdf5-1.12.2-r5jg4gl3uq7tww2exzoi6vn74dawxglb
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: hdf5
Description: HDF5 (Hierarchical Data Format 5) Software Library
Version: 1.12.2

Cflags: -I${includedir}
Libs: -L${libdir} 
Requires: 
Libs.private:  -lm -ldl -l/home/harmen/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/zlib-1.2.13-22f6ayr62k7ost462l4ah4mpveq7dc2m/lib/libz.a  -lhdf5
Requires.private: 
```

The problems are:

1. the order of the libraries are incorrect (dependencies should come after dependents)
2. the linker argument `-l<path to libz>/libz.a` is invalid syntax
3. (minor) `Libs:` does not set `-lhdf5` 

**Expected behavior**

Notice that alternatively one could just use `Requires.private: zlib`, see https://people.freedesktop.org/~dbn/pkg-config-guide.html.

With the following change:

```
$ cat hdf5.pc 
prefix=/home/harmen/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/hdf5-1.12.2-r5jg4gl3uq7tww2exzoi6vn74dawxglb
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: hdf5
Description: HDF5 (Hierarchical Data Format 5) Software Library
Version: 1.12.2

Cflags: -I${includedir}
Libs: -L${libdir} 
Requires: 
Libs.private: -lhdf5 -lm -ldl
Requires.private: zlib
```

I get the following:

```
$ pkg-config --libs --static hdf5
-L/home/harmen/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/hdf5-1.12.2-r5jg4gl3uq7tww2exzoi6vn74dawxglb/lib -L/home/harmen/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.2.0/zlib-1.2.13-22f6ayr62k7ost462l4ah4mpveq7dc2m/lib -lhdf5 -lm -ldl -lz
```

where the order is correct.

**Platform (please complete the following information)**

See the Spack output above

**Comment by byrnHDF** [comment]
The move of -lhdf5 to the left is easy enough to do. The problem with the compression libs are they might not have pkgconfig support and must be in the Libs.private line instead of Requires.private.

**Comment by byrnHDF** [comment]
However, the CMake configuration files should be preferred over the pkgconfig files with CMake projects. The configuration setting in the CMake configuration files have more information for building reqs.

**Comment by byrnHDF** [comment]
Will leave this open for a week to gather any feedback on the Requires.private decision.

**Comment by byrnHDF** [comment]
No further comments recieved
