### ISSUE TITLE
[Cmake Building Question] Parallel tools or Parallel ?

### ISSUE THREAD

**Issue by bozhang-hpc** [HDFGroup/hdf5#2265]
Hi,

I'm having trouble building the parallel HDF5 in order to use parallel NetCDF functionalities. It seems when I turn on both `HDF5_ENABLE_PARALLEL` and `HDF5_BUILD_PARALLEL_TOOLS` then it will try to find a MFU package.

My questions are:

1. What is the MFU library?
2. Do I need `HDF5_ENABLE_PARALLEL` or `HDF5_BUILD_PARALLEL_TOOLS` or both ?
3. What is the difference between `HDF5_ENABLE_PARALLEL` and `HDF5_BUILD_PARALLEL_TOOLS`?

Thanks

**Comment by byrnHDF** [comment]
HDF5_ENABLE_PARALLEL is only needed.

HDF5_BUILD_PARALLEL_TOOLS enables an extended version of parallelized tools that requires extra libraries.

**Comment by barracuda156** [comment]
Enabling tools fails on
```
CMake Error at /opt/local/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find MFU (missing: MFU_LIBRARY MFU_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  config/cmake/FindMFU.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:1182 (find_package)
```

**Comment by brtnfld** [comment]
Just to be clear, as I find the option name is misleading. It does not mean "build HDF5 tools with parallel support," but it actually means "build an extra HPC-specific parallel file walker (h5dwalk) that requires three exotic external libraries." 

mpiFileUtils is a suite of HPC parallel file utilities from LLNL. Along with CIRCLE (libcircle, a distributed queue) and DTCMP (distributed sort/merge), these are specialized HPC system libraries not found in standard distros or package managers, so you will need to install them yourself.

If you don't need that utility, best to not enable it.
