### ISSUE TITLE
Perform TEST_LFS_WORKS in every CMake run

### ISSUE THREAD

**Issue by maxaehle** [HDFGroup/hdf5#2395]
**Describe the bug**

I noticed that a different set of compiler flags is used to build the Insight Toolkit (ITK), depending on whether CMake has been run once or twice, see https://github.com/InsightSoftwareConsortium/ITK/pull/3852. ITK includes HDF5 and the issue is partly due to the following issue in the CMake build system of HDF5 around [these lines](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/config/cmake_ext_mod/ConfigureChecks.cmake#L274-L290).

- In the first CMake run, `TEST_LFS_WORKS_RUN` is not defined, so [this if-condition](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/config/cmake_ext_mod/ConfigureChecks.cmake#L274) is true, so the test is run. Ideally, the test succeeds and some compiler definitions are appended to `HDF_EXTRA_FLAGS` [here](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/config/cmake_ext_mod/ConfigureChecks.cmake#L290).
- In any subsequent CMake run, `TEST_LFS_WORKS_RUN` is defined (I think `try_run` creates cache variables; it's not properly documented for `try_run`, but for `try_compile`). Thus, the test is not repeated and no compiler definitions are appended to `HDF_EXTRA_FLAGS`.

**Expected behavior**

I would expect that HDF5 uses the same set of compiler flags no matter how often CMake has been run before.

**Proposed Fix**

Perform the test in every CMake run, by changing [`hdf5/config/cmake_ext_mod/ConfigureChecks.cmake`](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/config/cmake_ext_mod/ConfigureChecks.cmake) in the following way:
```diff
-  if (HDF_ENABLE_LARGE_FILE AND NOT DEFINED TEST_LFS_WORKS_RUN)
+  if (HDF_ENABLE_LARGE_FILE)
```

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): `hdf5-1_12_1`
 - OS and version: *Ubuntu*
 - Compiler and version: *GCC 9.4.0*
 - Build system (e.g. CMake, Autotools) and version: *CMake 3.16.3*
 - Any configure options you specified: *Included into ITK*
 - MPI library and version (parallel HDF5): *probably OpenMPI 4.0.3, but irrelevant here*

**Additional context**
https://github.com/InsightSoftwareConsortium/ITK/pull/3852

**Comment by byrnHDF** [comment]
The problem is that $HDF_EXTRA_FLAGS variable gets cleared every time and should not be. Removing line 226 (in develop branch) should keep the value in cache.

**Comment by maxaehle** [comment]
Removing the `set(HDF_EXTRA_FLAGS)` statement [here](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/config/cmake_ext_mod/ConfigureChecks.cmake#L253) does not solve the problem on my system. 

At the moment, `HDF_EXTRA_FLAGS` is a not a cache but a local CMake variable, and thus empty by default. I don't think one should make it a cache variable, because it is modified in the course of the program.

**Comment by derobins** [comment]
Do we even need to test if LFS works? Isn't this an artifact from the 90s?

**Comment by derobins** [comment]
We'll address this for 1.14.4, when we clean up all the try_run stuff in CMake.

**Comment by derobins** [comment]
I "fixed" this by overhauling how we deal with LFS support. We no longer need to run a special program to see if LFS support is available.
