### ISSUE TITLE
src\H5FDs3comms.c(944,13): : error : call to undeclared function 'StrStrIA'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#2396]
ONEapi Intel C Compiler on windows cannot find StrStrIA(A, B)

30>    start = HDstrcasestr(headerresponse, "\r\nContent-Length: ");
30>            ^
30>hdfsrc\src/H5win32defs.h(84,31): note: expanded from macro 'HDstrcasestr'
30>#define HDstrcasestr(A, B)    StrStrIA(A, B)

**Comment by mkitti** [comment]
I found something similar with mingw32.

Might need to explicitly link the  shlwapi library.


https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strstria
