### ISSUE TITLE
[Q] ROS support

### ISSUE THREAD

**Issue by TheChymera** [HDFGroup/hdf5#2403]
Not a bug, but the tracker makes me choose either bug or feature and I can't remove the label :(

I notice that since `1.12.2` ROS support is enabled by default even in the absence of `--enable-ros3-vfd`.

Is this likely to remain a constant in future versions, or should I be cautious and not assume that ROS support will always be present unless explicitly disabled?

**Comment by derobins** [comment]
The place for questions is the HDF Group forum (https://forum.hdfgroup.org/)

As for the ros3 VFD, it should be disabled by default. There was some weirdness in a few VFDs that were coded in a way that provides a non-functional stub when the VFD is disabled (removed in newer versions), but you won't get a working VFD unless you specify it at the command line.

It'd be nice to have the ros3 VFD always available, but that adds a dependency on libcurl, which we'd like to avoid for people who don't care about the cloud. This decision may change in the future.
