### ISSUE TITLE
Change to public CMake link for MPI breaks spack builds for certain packages

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#2404]
PR #2198 "Correct the CMake link for MPI" changed the dependency on MPi:MPI_C from PRIVATE to PUBLIC for target_link_libraries (${HDF5_LIBSH_TARGET} to resolve issues with some dependent software packages.  See also #2176 "CMake config depends on MPI but does not find it"

The change introduced this error when configuring 2 or more Spack packages in E4S tests:

1 error found in build log:
     25    -- Found ZLIB: /scr/lrknox/spack_lrknox/opt/spack/linux-centos7-haswell/g
           cc-10.2.0/zlib-1.2.13-lik6tppfkychie657bb37cn4nxt2sewa/lib/libz.so (found
            version "1.2.13")
     26    -- Found OpenMP_C: -fopenmp (found version "4.5")
     27    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
     28    -- Found OpenMP: TRUE (found version "4.5")
     29    -- Found HDF5: hdf5-shared (found version "1.14.0")
     30    -- Configuring done
  >> 31    CMake Error at /scr/lrknox/spack_lrknox/opt/spack/linux-centos7-haswell/g
           cc-10.2.0/hdf5-1.14.0-rfvrzau53dmibmjws7rz4tinc4xebz3k/cmake/hdf5-targets
           .cmake:68 (set_target_properties):
     32      The link interface of target "hdf5-shared" contains:
     33    
     34        MPI::MPI_C
     35    
     36      but the target was not found.  Possible reasons include:
     37    

Note that the default configuration for the hdf5 spack pacakge includes +mpi, but the packages that fail with the change may not use mpi.

**Comment by hyoklee** [comment]
Fix `See aalso#2176`.

**Comment by hyoklee** [comment]
Fix `The change introduced this error iwhen`.

**Comment by derobins** [comment]
Everyone insists that this is fixed. Closing.
