### ISSUE TITLE
[BUG] Packaging HDF5 1.14 references build directory in settings

### ISSUE THREAD

**Issue by SMillerDev** [HDFGroup/hdf5#2422]
**Describe the bug**
After https://github.com/HDFGroup/hdf5/commit/27bb358f7ab1d23f3f8ce081c6b4f1602033e4d7#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810 the hdf5 settings file references the directory hdf5 was build in.

**Expected behavior**
Includes should not reference a temporary build directory.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.0
 - OS and version: macOS 13.2
 - Compiler and version: CLang
 - Build system: latest version of all tools to use with configure
 - Any configure options you specified: https://github.com/Homebrew/homebrew-core/pull/119504/files#diff-932622d999a2cb8276fb857b7d97c7d3a2c3a6694db7c01f641f00ecd71d18c2R50-R59
 - MPI library and version: 1.14.0

**Additional context**
This was discovered at https://github.com/Homebrew/homebrew-core/pull/119504

**Comment by hmaarrfk** [comment]
did you ever find a workaround for this?
