### ISSUE TITLE
Missing or misplaced entries in API reference tables

### ISSUE THREAD

**Issue by jhendersonHDF** [HDFGroup/hdf5#2470]
Several entries appear to be missing or incorrect from the Property List API reference tables rooted at https://docs.hdfgroup.org/hdf5/develop/group___h5_p.html.

- File Creation Property Lists
    - H5Pset_file_image/H5Pget_file_image should be listed under FAPL table, rather than FCPL

- File Access Property Lists
    - Missing entries for H5Pset_driver, H5Pset_driver_by_name, H5Pset_driver_by_value, H5Pget_driver, H5Pget_driver_info, H5Pget_driver_config_str, H5Pset_multi_type, H5Pget_multi_type, H5Pset_mdc_image_config, H5Pget_mdc_image_config, H5Pset_fclose_degree, H5Pget_fclose_degree, H5Pset_file_image, H5Pget_file_image, H5Pset_file_image_callbacks, H5Pget_file_image_callbacks, H5Pset_metadata_read_attempts, H5Pget_metadata_read_attempts, H5Pset_object_flush_cb, H5Pget_object_flush_cb, H5Pset_mdc_log_options, H5Pget_mdc_log_options, H5Pset_evict_on_close, H5Pget_evict_on_close, H5Pset_file_locking, H5Pget_file_locking, H5Pset_coll_metadata_write, H5Pget_coll_metadata_write, H5Pset_mpi_params, H5Pget_mpi_params, H5Pset_page_buffer_size, H5Pget_page_buffer_size, H5Pset_vol, H5Pget_vol_id, H5Pget_vol_info, H5Pget_vol_cap_flags, H5Pset_fapl_core, H5Pget_fapl_core, H5Pset_fapl_direct, H5Pget_fapl_direct, H5Pset_fapl_family, H5Pget_fapl_family, H5Pset_fapl_hdfs, H5Pget_fapl_hdfs, H5Pset_fapl_log, H5Pset_fapl_mirror, H5Pget_fapl_mirror, H5Pset_fapl_mpio, H5Pget_fapl_mpio, H5Pset_fapl_multi, H5Pget_fapl_multi, H5Pset_fapl_split, H5Pset_fapl_onion, H5Pget_fapl_onion, H5Pset_fapl_sec2, H5Pset_fapl_stdio, H5Pset_fapl_windows, H5Pset_fapl_subfiling, H5Pget_fapl_subfiling, H5Pset_fapl_ioc, H5Pget_fapl_ioc, H5Pset_core_write_tracking, H5Pget_core_write_tracking
    - Missing entry for H5Pset_all_coll_metadata_ops/H5Pget_all_coll_metadata_ops, though this is both a File Access Property and Link Access Property, so would be listed in multiple places

- Link Access Property Lists
    - Missing entry for H5Pset_all_coll_metadata_ops/H5Pget_all_coll_metadata_ops, though this is both a File Access Property and Link Access Property, so would be listed in multiple places

- Dataset Creation Property Lists
    - Missing entries for H5Pset_virtual, H5Pget_virtual_count, H5Pget_virtual_vspace, H5Pget_virtual_srcspace, H5Pget_virtual_filename, H5Pget_virtual_dsetname, H5Pset_chunk_opts, H5Pget_chunk_opts, H5Pset_dset_no_attrs_hint, H5Pget_dset_no_attrs_hint
    - H5Pset_char_encoding/H5Pget_char_encoding should be listed under String Creation Property Lists rather than being in the Attribute Creation Property Lists group and listed under the Dataset Creation Property Lists table

- Dataset Access Property Lists
    - Missing entries for H5Pset_virtual_view, H5Pget_virtual_view, H5Pset_virtual_printf_gap, H5Pget_virtual_printf_gap, H5Pset_append_flush, H5Pget_append_flush, H5Pset_efile_prefix, H5Pget_efile_prefix, H5Pset_virtual_prefix, H5Pget_virtual_prefix
    - Entries that should be listed under Dataset Transfer Property Lists, rather than Dataset Access Property Lists: H5Pset_buffer, H5Pget_buffer, H5Pset_edc_check, H5Pget_edc_check, H5Pset_filter_callback, H5Pset_data_transform, H5Pget_data_transform, H5Pset_type_conv_cb, H5Pget_type_conv_cb, H5Pset_hyper_vector_size, H5Pget_hyper_vector_size, H5Pset_btree_ratios, H5Pget_btree_ratios, H5Pset_vlen_mem_manager, H5Pget_vlen_mem_manager, H5Pset_dxpl_mpio, H5Pget_dxpl_mpio, H5Pset_dxpl_mpio_chunk_opt, H5Pset_dxpl_mpio_chunk_opt_num, H5Pset_dxpl_mpio_chunk_opt_ratio, H5Pset_dxpl_mpio_collective_opt, 
    - Entries that should be listed under File Access Property Lists instead: H5Pset_multi_type, H5Pget_multi_type
    - Entries that should be removed from this table: H5Pset_small_data_block_size, H5Pget_small_data_block_size

- Dataset Transfer Property Lists
    - This table should be created and populated with the entries from Dataset Access Property Lists mentioned above, as well as entries for: H5Pset_preserve, H5Pget_preserve, H5Pget_mpio_actual_chunk_opt_mode, H5Pget_mpio_actual_io_mode, H5Pget_mpio_no_collective_cause, H5Pset_dataset_io_hyperslab_selection

- Group Creation Property Lists
    - Missing entries for: H5Pset_local_heap_size_hint, H5Pget_local_heap_size_hint
    - H5Pset_char_encoding/H5Pget_char_encoding should be listed under String Creation Property Lists rather than being in the Attribute Creation Property Lists group and listed under the Group Creation Property Lists table

- Map Creation Property Lists
    - This table should be created and populated with entries for: H5Pset_map_iterate_hints, H5Pget_map_iterate_hints

- Object Creation Property Lists
    - Missing entry for: H5Pall_filters_avail

- String Creation Property Lists
    - Entries that should be removed from this table: H5Pset_create_intermediate_group, H5Pget_create_intermediate_group

**Comment by byrnHDF** [comment]
the file driver FAPLs were in a separate table that was not added with the fapl_table snippet.
Corrected.

**Comment by byrnHDF** [comment]
the H5Pget/set_all_coll_metadata_ops is identified as GAPL and is in that table.

**Comment by jhendersonHDF** [comment]
> the H5Pget/set_all_coll_metadata_ops is identified as GAPL and is in that table.

Yes, it should probably either only be under FAPL and LAPL though, or in every relevant table (FAPL, LAPL, GAPL, DAPL, etc.). I certainly wouldn't expect to only find it under GAPL.

**Comment by byrnHDF** [comment]
H5Pall_filters_avail is in DCPL.

**Comment by byrnHDF** [comment]
#2472 PR created

**Comment by jhendersonHDF** [comment]
> H5Pall_filters_avail is in DCPL.

It's an OCPL property because it can be used for both dataset and group creation property lists. If it's only in DCPL, users might not realize it's useful for checking for filters on groups as well.

**Comment by byrnHDF** [comment]
That then is a bug that needs to fixed? Maybe it needs it's own PR?  This one only changes the tables to match the source.

**Comment by jhendersonHDF** [comment]
I don't think I'd call it a bug, just poor/misleading documentation, especially since we have a table for OCPL already. But yes, a separate PR to fix that is probably fine.

**Comment by byrnHDF** [comment]
One thing that also should be checked is if there are references to these documentation errors in the User Guide docs?
The tables are one thing but specific refs to functions could be out of synec.

**Comment by byrnHDF** [comment]
All branches updated
