### ISSUE TITLE
[BUG] Memory issue in H5VL_pass_through_str_to_info

### ISSUE THREAD

**Issue by yzanhua** [HDFGroup/hdf5#2473]
**Describe the bug**
[This line](https://github.com/HDFGroup/hdf5/blob/966454aac1231da7209ef81c11055d3312181f99/src/H5VLpassthru.c#L691) accesses 1 byte outside the malloc'd region for `under_vol_info_str`. A `-1` is expected.
```c
*(under_vol_info_str + (under_vol_info_end - under_vol_info_start) - 1) = '\0';
```

**Comment by raylu-hdf** [comment]
I verified that the issue was fixed in the develop branch.
