### ISSUE TITLE
Consistent Configuration Summary State Values

### ISSUE THREAD

**Issue by WeiqunZhang** [HDFGroup/hdf5#2488]
**Describe the bug**
It appears that the configuration summary does not sanitize the cmake build options.  For example, if HDF5 is built with `-DHDF5_ENABLE_PARALLEL=42`, the configuration summary shown by `h5pcc` will be `Parallel HDF5: 42`.  Since cmake accepts so many values as true (e.g, `ON`, `Y`, `TRUE`, `YES`, `1`, `42`, `3.14`, etc.), this becomes an issue.  For example, this spack issue (https://github.com/spack/spack/issues/35546) is caused by spack using `ON` to enable cmake build options whereas CMake's FindHDF5 module checking `yes` for Parallel HDF5 support.

**Expected behavior**
Maybe HDF5 should always write `YES` or `ON` or `yes` (because that's what CMake checks) for all cmake true values.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash)
 - OS and version
 - Compiler and version
 - Build system (e.g. CMake, Autotools) and version
   CMake
 - Any configure options you specified
 - MPI library and version (parallel HDF5)

**Comment by byrnHDF** [comment]
Unfortunately, that file should only be informational, CMake produces a hdf5-config.cmake file that has build program-usable variables.

That file is created with a simple variable substitution command;
configure_file (
    ${HDF_RESOURCES_DIR}/libhdf5.settings.cmake.in
    ${HDF5_SRC_BINARY_DIR}/libhdf5.settings ESCAPE_QUOTES @ONLY
)

**Comment by byrnHDF** [comment]
I believe that, unless otherwise stated in the option message, that HDF5 consistently uses ON or OFF for boolean type options.
