### ISSUE TITLE
HDF5 Website refers to JIRA instead of Github for issues

### ISSUE THREAD

**Issue by calvertdw** [HDFGroup/hdf5#2504]
I had reported an issue on JIRA because that is where hdfgroup.org directs you, but it sat there for quite a few weeks. When I made the issue on this Github it had a very timely response. 

Maybe the official website should refer users to the Github instead? In fact, due to permissions, the public cannot report issues to the HDF5 project on the JIRA anyway, only the HDFView project.

No big deal on this, just thought it might help out the project. :)

**Comment by loricooperhdf** [comment]
Updated the page to better reflect our changes in issue handling: https://confluence.hdfgroup.org/display/support/The+HDF+Help+Desk 

Also: updated link for support on Twitter.. we will not update support.hdfgroup.org as it's just there for archival purposes.
