### ISSUE TITLE
Intel Compiler linker removed after installation of hdf5

### ISSUE THREAD

**Issue by HathewayWill** [HDFGroup/hdf5#2536]
Long text chain on the Intel support forum. 

They say it's a hdf5 problem and not Intel. 

Can someone look into this?

https://community.intel.com/t5/Intel-oneAPI-Base-Toolkit/Intel-linker-not-found/m-p/1464435/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExGMzVBSkRPRTRFQVhSfDE0NjQ0MzV8U1VCU0NSSVBUSU9OU3xoSw#M2839

**Comment by HathewayWill** [comment]
Will this issue be addressed in 1.15.0?

@derobins @glennsong09

**Comment by derobins** [comment]
Is this an HDF5 issue or a netCDF  / WRF issue? It looks like that tarball is trying to unpack a math library on top of a system math library? That seems unlikely to be an HDF5 issue. I'll check our binaries, but I feel like if we were trying to reinstall system math libraries, that would have caused severe, noticeable problems by now.
