### ISSUE TITLE
h5repack: Unnecessary HDprintf in non verbose in run

### ISSUE THREAD

**Issue by sreerajkksd** [HDFGroup/hdf5#2538]
It looks with this [PR](https://github.com/HDFGroup/hdf5/pull/1142), we added h5repack timing verbosity (verbose=2), but that accidentally (I think) moved a verbose log to print in non verbose mode.

https://github.com/HDFGroup/hdf5/pull/1142/files#diff-8aebc9007c810372a68b3decdd1dfd17f39975246dbc69a2f75208fe29696973R533-R538

ie, we added `HDprintf(FORMAT_OBJ_ATTR_TIME, "attr", read_time, write_time, name);` when verbosity is 2 and we made previously verbose log to print always.

I can create a PR to fix this, but can someone confirm this is an actual bug ?

**Comment by ArvidJB** [comment]
To reproduce you can run the following which will now print the attributes:
```
$ python
Python 3.10.4 (main, Jul  5 2022, 12:54:02) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> with h5py.File('/tmp/data.h5', 'w') as f:
...     f.attrs['foo'] = 'bar'
...
>>> exit()
$ h5repack /tmp/data.h5 /tmp/data.repacked.h5
  attr                        foo
```

**Comment by byrnHDF** [comment]
This should have been fixed in the development versions. And should be available in the next releases. Looks like that might have been missed.

**Comment by byrnHDF** [comment]
PR# 2540 created.

**Comment by sreerajkksd** [comment]
Thanks for fixing and merging ( https://github.com/HDFGroup/hdf5/pull/1142 )
