### ISSUE TITLE
[Feature Request] Use Github mirror for libaec

### ISSUE THREAD

**Issue by mkitti** [HDFGroup/hdf5#2552]
**Is your feature request related to a problem? Please describe.**
There is an actively maintained github mirror by one of the original libaec authors here:
https://github.com/MathisRosenhauer/libaec

**Describe the solution you'd like**
Per https://github.com/HDFGroup/hdf5/pull/2487/files#r1118169340 use https://github.com/MathisRosenhauer/libaec instead of https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.0.6 since "loading anything outside of GitHub can be very slow".

**Describe alternatives you've considered**
Do nothing.

**Additional context**
https://gitlab.dkrz.de/k202009 is @MathisRosenhauer

**Comment by byrnHDF** [comment]
Created #2559

**Comment by byrnHDF** [comment]
Verified codebase of branches have changes
