### ISSUE TITLE
[BUG] Intel OneAPI Issue of -loopopt=1 causing autotools builds to fail with fortran enabled.

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#2563]
For a complete discussion see https://community.intel.com/t5/Intel-Fortran-Compiler/ifx-2021-1-beta04-HPC-Toolkit-build-error-with-loopopt/td-p/1184181

but in summary, ifx passes "-mllvm -loopopt=n" to xfortcom, and

> The underlying issue was that Autoconf tries to dig through the internal interface between the compiler driver and the Fortran compiler to figure out what libraries need to be used during linking.  Before Autoconf 2.70, Autoconf interprets a flag intended for the compiler as a the name of a library that does not exist, and so linking fails.  The fix in 2.70 was to recognize and ignore flags the compiler driver is passing to the internal Fortran compiler interface.

The solution is to generate configure files with autotools 2.70 or greater. I tried 2.71 is it fixes the issue on Sunspot an ANL.

**Comment by derobins** [comment]
This is something that we are addressing during the release process.
