### ISSUE TITLE
Detected memory leaks in H5FL__malloc hdf5/src/H5FL.c

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2599]
detected memory leaks in H5FL__malloc hdf5/src/H5FL.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013588/pov.zip)

Stack trace:
```
==1947206==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 56 byte(s) in 1 object(s) allocated from:
#0 0x4c170f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x72cebb in H5FL__malloc hdf5/src/H5FL.c:237:30
SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
```

**Comment by vchoi-hdfgroup** [comment]
It was fixed and merged to develop, 1.14, 1.12 and 1.10.
