### ISSUE TITLE
Memory error in H5C__load_entry hdf5/src/H5C.c

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2600]
requested allocation size 0xe40000000060 (0xe40000001060 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0) in H5C__load_entry hdf5/src/H5C.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013594/pov.zip)

Stack trace:
```
==1947262==ERROR: AddressSanitizer: requested allocation size 0xe40000000060 (0xe40000001060 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
#0 0x4c170f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x5c93ad in H5C__load_entry hdf5/src/H5C.c:7120:37
#2 0x5c6b0d in H5C_protect hdf5/src/H5C.c:2330:30
#3 0x58386f in H5AC_protect hdf5/src/H5AC.c:1394:26
==1947262==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: allocation-size-too-big /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3 in malloc
==1947262==ABORTING
```

**Comment by derobins** [comment]
h5dump exits normally with no memory leaks when parsing this file. I don't see a fixable error here.
