### ISSUE TITLE
Detected memory leaks in H5O__pline_copy hdf5/src/H5Opline.c

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2602]
detected memory leaks in H5O__pline_copy hdf5/src/H5Opline.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11013610/pov.zip)

Stack trace:
```
==1947783==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 192 byte(s) in 1 object(s) allocated from:
#0 0x4c18c7 in calloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
#1 0x87a91d in H5O__pline_copy hdf5/src/H5Opline.c:392:57
SUMMARY: AddressSanitizer: 192 byte(s) leaked in 1 allocation(s).
```

**Comment by derobins** [comment]
Fixed in develop. h5dump exits normally with no memory leaks.
