### ISSUE TITLE
[BUG] detected memory leaks in H5O__efl_decode hdf5/src/H5Oefl.c

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2605]
detected memory leaks in H5O__efl_decode hdf5/src/H5Oefl.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11014096/pov.zip)

Stack trace:
```
==1948296==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x4c18c7 in calloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
#1 0xcc2c04 in H5O__efl_decode hdf5/src/H5Oefl.c:137:37
#2 0x8738c8 in H5O_msg_read_oh hdf5/src/H5Omessage.c:513:5
#3 0x8732df in H5O_msg_read hdf5/src/H5Omessage.c:454:30
#4 0x63d32f in H5D__layout_oh_read hdf5/src/H5Dlayout.c:627:21
#5 0x623906 in H5D_open hdf5/src/H5Dint.c:1498:13
#6 0x622d37 in H5D__open_name hdf5/src/H5Dint.c:1433:25
#7 0xb81750 in H5VL__native_dataset_open hdf5/src/H5VLnative_dataset.c:318:25
#8 0xb5638b in H5VL__dataset_open hdf5/src/H5VLcallback.c:1946:30
SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

**Comment by derobins** [comment]
develop debug h5dump dumps core with the file:

```
h5dump: ../../hdf5/src/H5Oefl.c:114: H5O__efl_decode: Assertion `mesg->nalloc > 0' failed.
Aborted (core dumped)
```

so we'll address that before the memory leak (production mode is fine).
