### ISSUE TITLE
Allocator is out of memory in H5C__load_entry hdf5/src/H5C.c

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2607]
allocator is out of memory trying to allocate 0x8000000060 bytes in H5C__load_entry hdf5/src/H5C.c

Built from git commit hash 0553fb7
OS: Ubuntu 20.04
Compiler: clang version 11.0

Build options:
- Shared library disabled
CC=clang
CXX=clang++
CFLAGS="-g -fno-inline -fsanitize=address"
CXXFLAGS="-g -fno-inline -fsanitize=address"
LDFLAGS="$LDFLAGS -fsanitize=address"
ASAN_OPTIONS=abort_on_error=1

Command: ./h5dump pov

POV file:
[pov.zip](https://github.com/HDFGroup/hdf5/files/11014112/pov.zip)

Stack trace:
```
==1973001==ERROR: AddressSanitizer: allocator is out of memory trying to allocate 0x8000000060 bytes
#0 0x4c170f in malloc /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x5c93ad in H5C__load_entry hdf5/src/H5C.c:7120:37
#2 0x5c6b0d in H5C_protect hdf5/src/H5C.c:2330:30
#3 0x58386f in H5AC_protect hdf5/src/H5AC.c:1394:26
==1973001==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: out-of-memory /home/chaitra/aflgo-top/build/llvm_tools/llvm-11.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3 in malloc
==1973001==ABORTING
```

**Comment by derobins** [comment]
The library behaves correctly when the system is out of memory, exiting with no memory leaks. I see no fixable issue here.
