### ISSUE TITLE
[BUG] HDF5 C++ 1.14.0 includes H5FDsubfiling build path

### ISSUE THREAD

**Issue by Mvwivs** [HDFGroup/hdf5#2621]
**Describe the bug**
Using HDF5 C++ library with cmake results in error:

```
CMake Error in CMakeLists.txt:
  Imported target "hdf5::hdf5_cpp" includes non-existent path

    "/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

The path is from HDF5 build directory which is deleted after install

**Expected behavior**
No build path should be included anywhere, because H5FDsubfiling headers are already installed in the system.

**Platform (please complete the following information)**
 - HDF5 version 1.14.0
 - OS and version: Linux Debian 11
 - Compiler and version: GCC 12.2.0
 - Build system (e.g. CMake, Autotools) and version: Autotools
 - Any configure options you specified
 `./configure --prefix=/usr/local --enable-cxx`

**Additional context**
Path to H5FDsubfiling is included in 3 places:

```
/usr/local/bin/h5c++:H5BLD_CPPFLAGS=" -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling "
/usr/local/bin/h5cc:H5BLD_CPPFLAGS=" -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling "
/usr/local/lib/libhdf5.settings:                    AM_CPPFLAGS:  -I/tmp/hdf5-hdf5-1_14_0/src/H5FDsubfiling
```

Removing flags from h5c++ and h5cc fixes the problem.

**Comment by jhendersonHDF** [comment]
This is likely the same as in https://github.com/HDFGroup/hdf5/issues/2422
