### ISSUE TITLE
Memory leaks detected in HDF5 via NetCDF utility ncdump

### ISSUE THREAD

**Issue by cniddodi** [HDFGroup/hdf5#2657]
Memory leaks were detected in HDF5 library (included by NetCDF) via NetCDF utility `ncdump`. 
More details here:
https://github.com/Unidata/netcdf-c/issues/2669
Would this be considered a bug in HDF5 library?

**Comment by derobins** [comment]
This is fixed in the develop branch. I didn't check other branches, but 1.14.3 will be fixed for sure.
