### ISSUE TITLE
Unexpected independent reads with chunked datasets

### ISSUE THREAD

**Issue by roblatham00** [HDFGroup/hdf5#2658]
**Describe the bug**
The Darshan tool shows us more independent reads than expected after setting collective metadata for reads.

When we use `H5Pset_coll_metadata_write` and `H5Pset_all_coll_metadata_ops` we see the expected decrease in metadata calls, except for one case:  when the dataset has an unlimited dimension:

Here's the h5dump of the header:
```
HDF5 "H4j.hdf5" {
GROUP "/" {
   DATASET "events" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 1780331, 10 ) / ( H5S_UNLIMITED, 10 ) }
      ATTRIBUTE "events" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 10 ) / ( 10 ) }
      }
   }
   DATASET "init" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 10 ) / ( 10 ) }
      ATTRIBUTE "properties" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 10 ) / ( 10 ) }
      }
   }
   DATASET "particles" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 12462317, 13 ) / ( H5S_UNLIMITED, 13 ) }
      ATTRIBUTE "properties" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 13 ) / ( 13 ) }
      }
   }
   DATASET "procInfo" {
      DATATYPE  H5T_IEEE_F64LE
      DATASPACE  SIMPLE { ( 1, 6 ) / ( 1, 6 ) }
      ATTRIBUTE "properties" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SIMPLE { ( 6 ) / ( 6 ) }
      }
   }
   DATASET "version" {
      DATATYPE  H5T_STD_I32LE
      DATASPACE  SIMPLE { ( 3 ) / ( 3 ) }
   }
}
}
```

Darshan tells us there are a lot of 2616-byte reads from every process .   These reads are not costing us much time at this scale on this file system, but I'm worried what happens at larger scales ?

**Expected behavior**
chunking metadata loaded in collectively

**Platform (please complete the following information)**
 - HDF5 version: 1.12.0
 - NERSC Cori
 - gcc-11
 - Build system: cmake, I presume (built via spack)
 - Any configure options you specified:  spack with `+cxx+fortran+hl+mpi+shared~szip~threadsafe` variants
 - Cray-MPI 8.1.17
 
**Additional context**
Discussed this with Scot and Jordan, who directed me to section 3.2 of the attached report
[HDF5_Collective_IO_Performance_Investigation.pdf](https://github.com/HDFGroup/hdf5/files/11140557/HDF5_Collective_IO_Performance_Investigation.pdf)

**Comment by jhendersonHDF** [comment]
@roblatham00 I believe PR #3716 should address most or all of the collective metadata read issues that you were seeing here; the changes in that PR will be in the 1.14.3 release. However, there are still certain pieces of metadata that can't yet be read collectively without significant rework. If that PR doesn't address the problems you were seeing, feel free to re-open this issue so we can investigate closer and see if there's a more specific fix we can make.
