### ISSUE TITLE
Delegating open fuzzing issues of libmatio to hdf5

### ISSUE THREAD

**Issue by tbeu** [HDFGroup/hdf5#272]
OSS library [matio](https://github.com/tbeu/matio) is being continuously fuzzed by the [oss-fuzz](https://github.com/google/oss-fuzz) service. Most of the [open matio fuzzing issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?q=matio&can=2&sort=-id&mode=grid&x=Engine&y=Type) seem to be related to the hdf5 v1.12.0 library dependency which is is not being fuzzed by oss-fuzz. Whom can I add as contact person for these issues? I believe the mail address needs to be setup as Google account in order to get access? 

See also https://github.com/google/oss-fuzz/issues/4999 where I first raised this topic.

FYI @inferno-chromium

**Comment by emmenlau** [comment]
May be related? https://github.com/HDFGroup/hdf5/issues/309

**Comment by derobins** [comment]
Can you send me email at derobins@hdfgroup.org?

**Comment by derobins** [comment]
We are set up to use oss-fuzz now
