### ISSUE TITLE
Problem about the H5Dread_chunk

### ISSUE THREAD

**Issue by supersteven** [HDFGroup/hdf5#2737]
I want to read data directly from dataset to memory buffer, my code like this:

char line[128];
sprintf(line, "/DataSet/ResolutionLevel %d/TimePoint 0/Channel 0/Data", level);
dataset_id = H5Dopen2(file_id, line, H5P_DEFAULT);

hsize_t offset[3];   // hyperslab offset in the file
offset[2] = X_CHUNKED_SIZE * blockIndexX;
offset[1] = Y_CHUNKED_SIZE * blockIndexY;
offset[0] = Z_CHUNKED_SIZE * blockIndexZ;
uint32_t filter_mask[1];
filter_mask[0] = 0;

status = H5Dread_chunk(dataset_id, H5P_DEFAULT, offset, filter_mask, buffer8);

status = H5Dclose(dataset_id);

the data type is H5T_NATIVE_UCHAR, the buffer8 is a pointer to a uint8 buffer.

But the returned buffer8 data is abnormal.

Could you help me? Or is there any code examples about this API?

**Comment by gheber** [comment]
This is not an HDF5 issue. Please direct questions about API use to the [HDF Forum](https://forum.hdfgroup.org/).
