### ISSUE TITLE
[BUG] `HDF5_BUILD_FORTRAN:BOOL=OFF` ->`HDF5_TEST_FORTRAN:BOOL=ON` ?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2781]
**Describe the bug**
I ran the generic `mkdir build && cd build && cmake ..`. 

It's strange to see
```
//Execute fortran tests
HDF5_TEST_FORTRAN:BOOL=ON

//Execute java tests
HDF5_TEST_JAVA:BOOL=ON
```
in `build/CMakeCache.txt`.

**Expected behavior**

I think they should be `OFF`.

**Platform (please complete the following information)**
 - HDF5 version: develop branch
 - OS and version: `Linux login13 5.14.21-150400.24.46_12.0.63-cray_shasta_c #1 SMP Fri Mar 3 22:39:37 UTC 2023 (6e164f9) x86_64 x86_64 x86_64 GNU/Linux`
 - Compiler and version: n/a
 - Build system: CMake 3.20.4
 - Any configure options you specified: n/a
 - MPI library and version (parallel HDF5): n/a

**Comment by byrnHDF** [comment]
HDF5_TEST_xxx are dependent on HDF5_BUILD_xxx and will only be applicable if the BUILD is enabled.  Dependent defaults are the state expected if they apply. Normal expectation is that if one enables a language and testing is enabled then the language tests should run.

**Comment by byrnHDF** [comment]
What is missing is the section in INSTALL_CMake.txt that should list those HDF5_TEST_xxx options

**Comment by byrnHDF** [comment]
doc file updated

**Comment by hyoklee** [comment]
Where is the commit hash / PR that refers this issue?
