### ISSUE TITLE
CMake can't generate Xcode project.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2791]
**Describe the bug**

1. git clone repo
2. mkdir build && cd build && cmake -G Xcode ..

```
-- Found Perl: /usr/bin/perl (found version "5.30.3") 
CMake Error at CMakeLists.txt:614 (if):
  if given arguments:

    "MATCHES" "Debug" "OR" "MATCHES" "Developer"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/Users/hyoklee/src/hdf5.HDFGroup/build/CMakeFiles/CMakeOutput.log".
See also "/Users/hyoklee/src/hdf5.HDFGroup/build/CMakeFiles/CMakeError.log".
```

**Expected behavior**

Create Xcode project.

**Platform (please complete the following information)**
 - HDF5 version: develop def21b1e33f2499ed4d51af0708d12242d63fa63
 - OS and version: Darwin nene.ad.hdfgroup.org 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
 - Compiler and version: AppleClang 14.0.0.14000029
 - Build system (e.g. CMake, Autotools) and version: cmake version 3.25.2

**Comment by hyoklee** [comment]
If I run `cmake -G Xcode -D HDF_CFG_NAME:STRING="Debug" ..`, 
I get 547 lines of these repeating messages:

```
CMake Error in src/CMakeLists.txt:
  The custom command generating

    /Users/hyoklee/src/hdf5/build/src/gen_SRCS.stamp1

  is attached to multiple targets:

    gen_hdf5-static
    gen_hdf5-shared

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".


CMake Error in examples/CMakeLists.txt:
  The custom command generating

    /Users/hyoklee/src/hdf5/build/src/gen_SRCS.stamp1

  is attached to multiple targets:

    gen_hdf5-static
    gen_hdf5-shared

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".

```

**Comment by byrnHDF** [comment]
Use CMAKE_BUILD_TYPE

**Comment by hyoklee** [comment]
Can you make `CMAKE_BUILD_TYPE` not required?

**Comment by byrnHDF** [comment]
No. CMake required.

**Comment by hyoklee** [comment]
How about this? 

https://github.com/hyoklee/hdf5/commit/605adb8850ac03c9160c067dc23cb853f00ad7a3

**Comment by derobins** [comment]
This is the same issue I tripped over on Windows when using the CMake GUI. @byrnHDF is working on a fix.

**Comment by byrnHDF** [comment]
This should be fixed for both windows and xcode, if someone can verify.

**Comment by hyoklee** [comment]
@byrnHDF , please add this Action https://github.com/hyoklee/hdf5/blob/develop/.github/workflows/mac-xcode.yml

**Comment by derobins** [comment]
This is no longer a problem as of 1.14.3
