### ISSUE TITLE
Change CMake defaults for enabling szip and gzip compression

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#2926]
It is requested that the options should be on by default.

**Comment by byrnHDF** [comment]
Currently, if the filter is enabled and not found, the build will halt. Should this be changed?

**Comment by jhendersonHDF** [comment]
> Currently, if the filter is enabled and not found, the build will halt. Should this be changed?

Yes, AFAIK Autotools will skip building the filter if support for it can't be found so CMake should do the same.

**Comment by byrnHDF** [comment]
This has been addressed in all branches.
