### ISSUE TITLE
[BUG] Remove  `./hdf5-1.14.1-2/configure~` file

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2954]
**Describe the bug**
The `hdf5-1.14.1-2.tar.gz` has backup files `configure~` and `src/H5config.h.in~`.

**Expected behavior**
The tar.gz package should not have a backup file.

**Platform (please complete the following information)**
n/a

**Additional context**
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/hdf5-1.14.1/src/hdf5-1.14.1-2.tar.gz

**Comment by lrknox** [comment]
This will be fixed by automated release processes in future releases.  The file shouldn't be there, but won't cause problems.

**Comment by hyoklee** [comment]
https://medium.com/gft-engineering/greencoding-the-keys-to-lower-emissions-67ab55028d6
