### ISSUE TITLE
`bin/cmakehdf5` is broken.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2958]
**Describe the bug**

Unpack hdf5-1.14.1-2.tar.gz and run the following steps.
You'll get `hdf5_plugins.tar.gz not found` error.

```
hyoklee@uan-0001:~/src>cd hdf5-1.14.1-2/
hyoklee@uan-0001:~/src/hdf5-1.14.1-2> mkdir build
hyoklee@uan-0001:~/src/hdf5-1.14.1-2> cd build
hyoklee@uan-0001:~/src/hdf5-1.14.1-2/build> ../bin/cmakehdf5 
...
-- Looking for clock_gettime in posix4 - not found
-- Found Perl: /usr/bin/perl (found version "5.26.1")
-- ....All Warnings are enabled
-- Filter PLUGIN file /home/hyoklee/src/hdf5-1.14.1-2/hdf5_plugins.tar.gz not found
```

**Expected behavior**

The hdf5_plugin.tar.gz should exist.
Or the script should download it if it is not found.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.1-2
 - OS and version: *Sunspot* - `Linux uan-0001 5.3.18-150300.59.115-default #1 SMP Fri Mar 10 07:48:20 UTC 2023 (0398b56) x86_64 x86_64 x86_64 GNU/Linux`
 - Compiler and version: n/a
 - Build system (e.g. CMake, Autotools) and version: CMake 3.24.2
 - Any configure options you specified: n/a
 - MPI library and version (parallel HDF5): n/a

**Additional context**

If `bin/cmakehdf5` is for internal use only, remove it from the package in the future.

**Comment by byrnHDF** [comment]
No that is an informational message as the plugins are optional.

**Comment by hyoklee** [comment]
OK. How about this error?
```
CMake Error at java/CMakeLists.txt:2 (project):
  No CMAKE_Java_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "JAVA_COMPILER" or the CMake cache entry CMAKE_Java_COMPILER to
  the full path to the compiler, or to the compiler name if it is in the
  PATH.


-- Configuring incomplete, errors occurred!
See also "/home/hyoklee/src/hdf5-1.14.1-2/build/CMakeFiles/CMakeOutput.log".
See also "/home/hyoklee/src/hdf5-1.14.1-2/build/CMakeFiles/CMakeError.log".
```

**Comment by byrnHDF** [comment]
What is missing in both cmakehdf5 and buildhdf5 (autotools script) is a note that the compilers must be specified in the three ENV variables; CC, CXX, and FC.
Seems like an easy task for someone to add.

**Comment by derobins** [comment]
@hyoklee is this fixed now?

**Comment by mattjala** [comment]
> @hyoklee is this fixed now?

Running `cmakehdf5` myself, I elicited the same error he got, and the change fixed it. Closing for now.
