### ISSUE TITLE
Do not use /bin/mv in configure.ac

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#296]
Believe it or not, there are systems where `mv` is not located at `/bin/mv`. For example:
```
gerd@guix ~/scratch/hdf5 [env]$ which mv
/run/current-system/profile/bin/mv
```
In that case, the references to `/bin/mv` on lines 98 and 103 in `configure.ac` are show stoppers.

**Comment by derobins** [comment]
Fixed in develop, 1.12, and 1.10
