### ISSUE TITLE
CI: Set minimal permissions on GitHub Workflows

### ISSUE THREAD

**Issue by diogoteles08** [HDFGroup/hdf5#2973]
Hi!

I'm here to suggest that you set minimal permissions to your GitHub Workflows, because currently they don't specify the permissions for their jobs and their privileges are being determined by GitHub's defaults. If you define minimal permissions, you would be secured against erroneous or malicious behaviours from external jobs you call from your workflow. It's specially important for the case they get compromised, for example.

The ideal would be to set a top-level read-only permission on all workflows, so that they would be inherited by any job that does not define job-level permissions. Additionally, you can set any write permissions as job-level permissions, only where they are needed -- as I see its the case for your job in [clang-format-fix.yml](https://github.com/HDFGroup/hdf5/blob/develop/.github/workflows/clang-format-fix.yml), which requires `contents: write` permission.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

Let me know what you think about this. If you agree, I'd be happy to contribute with a PR =).

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

**Comment by jhendersonHDF** [comment]
Hi @diogoteles08,

we'd be happy to review a PR if you wanted to create one. AFAICT, this looks to be mostly as simple as adding

```YAML
permissions:
  contents: read
```

to most of the workflow files, correct?

**Comment by diogoteles08** [comment]
Hi, @jhendersonHDF! Yes, you are correct and it would be a very simple change indeed. I'll open a PR with the changes.
