### ISSUE TITLE
Improve `bin/h5vers` usage message.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2978]
**Describe the bug**

There's only `src/H5public.h` but usage output mentions 3 files.
 
```
    FILE
        The name of the file that contains version information.  This is
        seldom necessary since files H5public.h, src/H5public.h and
        ../src/H5public.h are automatically checked.
```

**Expected behavior**

Print only `src/H5public.h`. 

**Platform (please complete the following information)**
 n/a

**Additional context**

[Developer guide](https://github.com/HDFGroup/hdf5/blob/develop/doc/getting-started-with-hdf5-development.md) doesn't mention this program.

**Comment by lrknox** [comment]
@hyoklee, check PR #3162 - can this be closed?
