### ISSUE TITLE
[BUG] CMake Error at HDF5_ZLIB-stamp/verify-HDF5_ZLIB.cmake:11

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#2989]
**Describe the bug**

I got this error message from Polaris.

```
  File not found: /home/hyoklee/src/hdf5/ZLib.tar.gz 
make[2]: *** [CMakeFiles/HDF5_ZLIB.dir/build.make:98: HDF5_ZLIB-prefix/src/HDF5_\
ZLIB-stamp/HDF5_ZLIB-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:1439: CMakeFiles/HDF5_ZLIB.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Expected behavior**

First, I think it should give an errorl at configuration step, not building step.

Second, if CMake is trying to download /home/hyoklee/src/hdf5/ZLib.tar.gz and fails, 
I think it should suggest where to get the ZLib.tar.gz from the Internet.
Then, users can download it and continue.

**Platform (please complete the following information)**
 - HDF5 version: https://github.com/HDFGroup/hdf5/commit/5c2e434dc630d6e333aa4118c20d67b80df2173d
 - OS and version: Linux polaris-login-01 5.3.18-57-default`#1` SMP Wed Apr 28 10:54:41 UTC 2021 (ba3c2e9) x86_64 x86_64 x86_64 GNU/Linux
 - Compiler and version: gcc 11.2.0
 - Build system (e.g. CMake, Autotools) and version: CMake 3.23.3
 - Any configure options you specified: 
 ```
export CC=mpicc
export CXX=mpicxx
export FC=mpifort
export RUNPARALLEL="mpiexec -n 6"

cmake -C $HDF5/config/cmake/cacheinit.cmake -G "Unix Makefiles" \
-D CMAKE_INSTALL_PREFIX=$PWD/hdf5 \
-D CMAKE_BUILD_TYPE:STRING="Release" \
-D HDF5_BUILD_FORTRAN:BOOL=ON \
-D HDF5_ENABLE_PARALLEL:BOOL=ON \
-D HDF5_BUILD_CPP_LIB:BOOL=OFF \
-D HDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
-D HDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON \
-D BUILD_TESTING:BOOL=ON \
-D HDF5_BUILD_EXAMPLES:BOOL=OFF \
-D HDF5_BUILD_HL_LIB:BOOL=ON \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D HDF5_BUILD_JAVA:BOOL=OFF \
-D HDF5_ENABLE_SUBFILING_VFD:BOOL=ON \
-D HDF5_ENABLE_MAP_API:BOOL=ON
```
 - MPI library and version (parallel HDF5): gcc (GCC) 11.2.0 20210728 (Cray Inc.)

**Additional context**

If I download https://src.fedoraproject.org/repo/pkgs/zlib/zlib-1.2.3.tar.gz/debc62758716a169df9f62e6ab2bc634/zlib-1.2.3.tar.gz
and put it as ZLib.tar.gz, I get the following error:

```
CMake Error: The source directory "/home/hyoklee/src/hdf5/build/HDF5_ZLIB-prefix\
/src/HDF5_ZLIB" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [CMakeFiles/HDF5_ZLIB.dir/build.make:92: HDF5_ZLIB-prefix/src/HDF5_\
ZLIB-stamp/HDF5_ZLIB-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:1439: CMakeFiles/HDF5_ZLIB.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by lrknox** [comment]
Working on HPC machines; fixed by PR #2988.
