### ISSUE TITLE
`make check` failures w/ thread-safe + code stacks

### ISSUE THREAD

**Issue by bazimo** [HDFGroup/hdf5#2990]
**Describe the bug**
Encountered following errors:

H5VL_object_inc_rc function, FUNC_ENTER/LEAVE macro mismatch (FUNC_LEAVE_NOAPI should be FUNC_LEAVE_NOAPI_NOFS).

Two swmr test applications fail on H5FD__supports_swmr_test call, because HDF5 is not initialized. These are:
 - accum_swmr_reader.c
 - swmr.c

Inserting an H5open call before the "supports" call addresses that.

**Expected behavior**
All make checks tests should pass.

**Platform (please complete the following information)**
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.14.1-2
                  Configured on: Thu May 18 18:59:35 UTC 2023
                  Configured by: bappel@v4dev0
                    Host system: x86_64-pc-linux-gnu
              Uname information: Linux v4dev0 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /home/bappel/hdf5-1.14.1_debug

Compiling Options:
------------------
                     Build Mode: debug
              Debugging Symbols: yes
                        Asserts: yes
                      Profiling: yes
             Optimization Level: debug

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables:
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: -lpthread -lz -ldl -lm
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /usr/bin/gcc -std=gnu11 ( gcc (GCC) 4.8.5 20150623 )
                       CPPFLAGS: -g -m64
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -UNDEBUG -DH5AC_DEBUG -DH5B2_DEBUG -DH5CX_DEBUG -DH5D_DEBUG -DH5F_DEBUG -DH5HL_DEBUG -DH5I_DEBUG -DH5O_DEBUG -DH5S_DEBUG -DH5T_DEBUG -DH5Z_DEBUG -DH5_DEBUG_API -I/home/bappel/hdf5/src/H5FDsubfiling
                    AM_CPPFLAGS:
                        C Flags:
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wshadow -Wundef -Wwrite-strings -pedantic -Wno-c++-compat -Wvla -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized   -g -fno-omit-frame-pointer  -Wbad-function-cast -Wcast-align -Wformat -Wimplicit-function-declaration -Wint-to-pointer-cast -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-sign -Wpointer-to-int-cast -Wredundant-decls -Wstrict-prototypes -Wswitch -Wunused-but-set-variable -Wunused-variable -Wunused-function -Wunused-parameter -Waggregate-return -Wdisabled-optimization -Winline -Wmissing-format-attribute -Wmissing-noreturn -Wswitch-default -Wswitch-enum -Wunsafe-loop-optimizations -Wunused-macros -Wjump-misses-init -Wstrict-overflow=5 -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wvector-operation-performance -Wsuggest-attribute=format -pg
                     AM C Flags:
               Shared C Library: yes
               Static C Library: yes

                        Fortran: no

                            C++: no

                           Java: no

Features:
---------
                     Parallel HDF5: no
  Parallel Filtered Dataset Writes: no
                Large Parallel I/O: no
                High-level library: no
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                   Build GIF Tools: no
                      Threadsafety: yes
               Default API mapping: v114
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib)
                     Map (H5M) API: no
                        Direct VFD: no
                        Mirror VFD: no
                     Subfiling VFD: no
                (Read-Only) S3 VFD: no
              (Read-Only) HDFS VFD: no
    Packages w/ extra debug output: AC,B2,CX,D,F,HL,I,O,S,T,Z
                       API tracing: yes
              Using memory checker: yes
            Function stack tracing: yes
                  Use file locking: best-effort
         Strict file format checks: yes
      Optimization instrumentation: no

**Comment by bazimo** [comment]
PRs posted, 1_14_1 & develop.

**Comment by derobins** [comment]
I can't reproduce this. What is your exact configure line?

**Comment by bazimo** [comment]
> I can't reproduce this. What is your exact configure line?

configure --disable-hl --enable-threadsafe --enable-build-mode=debug --enable-profiling=yes  --enable-developer-warnings=yes  --enable-codestack --enable-using-memchecker

**Comment by derobins** [comment]
Aha! It's the code stacks. There are missing/misplaced h5_reset() lines. I'll have a PR for that in a bit.

**Comment by derobins** [comment]
PR up. Thanks for finding the issues and helping with fixes!

**Comment by bazimo** [comment]
> PR up. Thanks for finding the issues and helping with fixes!

You are welcome! My first ever open-source contribution. Though small, and what I posted was not quite correct, it was fun.

Thank you for the pleasant interaction!
