### ISSUE TITLE
Update documentation (website) for 1.14.1 and 1.15.0

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#3000]
- [ ] We need to add an automated way to update the develop (1.15.0) documentation on the website, https://docs.hdfgroup.org/hdf5/develop/

- [ ] Publish the 1.14.1 documentation. Link "HDF5 1.14.x" points to the 1.14.1 documentation, https://docs.hdfgroup.org/hdf5/develop

**Comment by byrnHDF** [comment]
github action?

**Comment by brtnfld** [comment]
Yes, something like:
https://dev.to/denvercoder1/using-github-actions-to-publish-doxygen-docs-to-github-pages-177g

**Comment by hyoklee** [comment]
@gheber , this is a blocker.

**Comment by hyoklee** [comment]
See also #1186

**Comment by hyoklee** [comment]
https://github.com/HDFGroup/hdf5/pull/3175
