### ISSUE TITLE
H5Dchunk_iter() does not account for user block when reporting chunk file address

### ISSUE THREAD

**Issue by ajelenak** [HDFGroup/hdf5#3003]
#### Describe the bug

For HDF5 files with user block the `H5Dchunk_iter()` function does not account for user block size when reporting chunk file address. To correct this one has to add user block size to locate the actual chunk in that file. The function's documentation does not mention this.

The function for contiguous datasets, `H5Dget_offset()`, does correctly take into account user block size.

#### Expected behavior

`H5Dchunk_iter()` should report chunk file addresses corrected for user block size if present. The documentation for the libhdf5 releases with this function should have a note to alert users.

#### Platform (please complete the following information)

 - HDF5 version: 1.14.0
 - OS: AWS EC2 Linux
 - Compiler and version: N/A
 - Build system: obtained with the `conda` package manager from the conda-forge channel
 - Any configure options you specified: N/A
 - No MPI or parallel build

#### Additional context

Sample files attached:
* A file with one contiguous and one chunked dataset. [test.h5.zip](https://github.com/HDFGroup/hdf5/files/11549732/test.h5.zip)
* A copy of the above file but with a 4,096 bytes user block. [ublock4kiB_test.h5.zip](https://github.com/HDFGroup/hdf5/files/11549733/ublock4kiB_test.h5.zip)

The chunk file addresses from both files will be the same.

**Comment by mkitti** [comment]
Does this match the behavior of `H5Dget_chunk_info`?
https://docs.hdfgroup.org/hdf5/v1_12/group___h5_d.html#title12

**Comment by ajelenak** [comment]
Yes, `H5Dget_chunk_info()` also does not account for user block size.

**Comment by mkitti** [comment]
I think we might be stuck with the current behavior then. I think we should just document this for now.

Alternatively, we could introduce version 2 of the function and also bump the others.

**Comment by derobins** [comment]
> I think we might be stuck with the current behavior then. I think we should just document this for now.
> 
> Alternatively, we could introduce version 2 of the function and also bump the others.

We don't version API calls for semantics. Also, this is a bug and we don't enshrine buggy behavior in the API.

This will be fixed in 1.14.4.

**Comment by mkitti** [comment]
As long as the chunk APIs are consistent with each other, I'm fine with the changes. I noticed this during development of `H5Dchunk_iter` but thought it would be better to be consistent.

**Comment by mkitti** [comment]
This was fixed in https://github.com/HDFGroup/hdf5/pull/4284 for releases 1.14.3 and newer. Those getting chunk offsets may need an `if` statement contingent on the HDF5 library version to handle this.

```python
def get_chunk_offsets(filename, datasetname):
    with h5py.File(filename, "r") as h5f:
        chunk_offsets = []
        h5dataset = h5f[datasetname].id
        userblock_offset = h5f.userblock_size if h5py.h5.get_libversion() < (1, 14, 3) else 0
        h5dataset.chunk_iter(lambda x: chunk_offsets.append(x.byte_offset + userblock_offset))
    return chunk_offsets
```
