### ISSUE TITLE
`HDstrncmp(name, "IOC", 9)` 

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#3005]
**Describe the bug**

The `src/H5FDsubfiling/H5FDioc.c` has the following code in line 576:

```
    if (HDstrncmp(name, "IOC", 9))
```

It also has the following codes in line 530-523:

```
    /* Encode driver name */
    HDstrncpy(name, "IOC", 9);
    name[8] = '\0';
```

**Expected behavior**

I think 9 should be 3 and 8 should be 4.

**Platform (please complete the following information)**
 - HDF5 version: develop
 
**Additional context**

Overall, codes under `H5FDsubfiling` are poorly documented and written.
Please review them throughly again.

**Comment by jhendersonHDF** [comment]
The number 9 comes from the name field of the `H5O_drvinfo_t` structure. There's an argument to be made here that the magic number 9 should be a #define, but other than that the rest of the code is written this way intentionally.

`HDstrncpy(name, "IOC", 9);` will copy no more than 9 bytes from the string "IOC" so as not to overflow the name buffer and will fill the rest of the buffer with zeroes. The next line `name[8] = '\0';` ensures that if someone changes the string "IOC" in the future to be more than 9 bytes long (including the NUL terminator), the resulting string will still be NUL-terminated.

`HDstrncmp(name, "IOC", 9)` ensures that no more than 9 bytes are compared from the name buffer and will stop at the NUL terminator in the string "IOC" anyway.

**Comment by hyoklee** [comment]
If `name` has "IOC" + 6 garbage characters in memory, what will HDstrncmp return?

**Comment by jhendersonHDF** [comment]
The superblock driver info decode function NUL terminates the driver name, so if `name` already has the string "IOC" in it, it will have at most 5 garbage characters and a NUL terminator, so there's no issue. Even if `name` had no NUL terminator, the 9 supplied to HDstrncmp ensures that there's still no issue here.

**Comment by hyoklee** [comment]
See how `HDstrncmp` is being used in other places:

```
H5Dint.c:        if (HDstrncmp(prefix, "${ORIGIN}", HDstrlen("${ORIGIN}")) == 0) {
H5ESint.c:    HDassert(0 == HDstrncmp(caller_args, "*s*sIu", 6));
H5FD.c:    if (!HDstrncmp(name, "NCSAfami", (size_t)8) && HDstrcmp(file->cls->name, "family") != 0)
H5FD.c:    if (!HDstrncmp(name, "NCSAmult", (size_t)8) && HDstrcmp(file->cls->name, "multi") != 0)
H5FDonion_header.c:    if (HDstrncmp((const char *)buf, H5FD_ONION_HEADER_SIGNATURE, 4))
H5FDonion_history.c:    if (HDstrncmp((const char *)buf, H5FD_ONION_HISTORY_SIGNATURE, 4))
H5FDonion_index.c:    if (HDstrncmp((const char *)buf, H5FD_ONION_REVISION_RECORD_SIGNATURE, 4))
H5FDs3comms.c:    } while (HDstrncmp(line_buffer, profile_line, HDstrlen(profile_line)));
H5FDs3comms.c:            if (!HDstrncmp(line_buffer, line_prefix, setting_name_len + 1)) {
H5FDsubfiling/H5FDsubfiling.c:    if (HDstrncmp(name, "Subfilin", 9))
H5FDsubfiling/H5FDioc.c:    if (HDstrncmp(name, "IOC", 9))
H5Gname.c:            if (HDstrncmp(fullpath, prefix, nchars1) == 0) {
H5PLpath.c:        if (!HDstrncmp(dp->d_name, "lib", (size_t)3) &&
H5PLpath.c:        if (!HDstrncmp(dp->d_name, "cyg", (size_t)3) && HDstrstr(dp->d_name, ".dll")) {
H5PLpath.c:        if (!HDstrncmp(dp->d_name, "lib", (size_t)3) &&
H5PLpath.c:        if (!HDstrncmp(dp->d_name, "cyg", (size_t)3) && HDstrstr(dp->d_name, ".dll")) {
```

**Comment by fortnern** [comment]
I agree with Jordan here, there's no problem with the existing code and it is more resilient if the name is changed. strncmp won't compare garbage characters after the null terminator, the "n" is just a safety catch.
