### ISSUE TITLE
H5Fset_libver_bounds has unexpected behavior

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#3011]
**Describe the bug**
H5Fset_libver_bounds does not report an error if the API tries to downgrade the version bound of the file that was opened. Whereas, if you try to open a file with a downgraded version bound, the opening will fail.

**Expected behavior**
Expect that the call to H5Fset_libver_bounds will return an error if it is impossible to specify a specific bounds version.

The documentation also needs to be updated about how the version bounds is related to the actual bounds setting for the file.

**Comment by Dave-Allured** [comment]
> the version bound of the file that was opened

What does this mean?  There is no such embedded "version bound", according to the current bounds documentation.  There are a plethora of individually versioned file objects, that's all.  Success or failure of a file access depends on the interaction of the individual file object versions, and the capability of the current library version doing the access.  I had to deal with this for netcdf support, a while back.

**Comment by brtnfld** [comment]
I wrote a test, and the function behaves as expected.
