### ISSUE TITLE
https://github.com/HDFGroup/hdf5/releases/tag/snapshot has hidden files.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#3024]
**Describe the bug**

Snapshot includes hidden files:

```
  -rw-r--r--@   1 hyoklee  HDF\\hdf    6148 May 26 16:35 .DS_Store
  -rw-rw-r--@   1 hyoklee  HDF\\hdf     571 May 25 16:07 .autom4te.cfg
  -rw-rw-r--@   1 hyoklee  HDF\\hdf    2634 May 25 16:07 .clang-format
  -rw-rw-r--@   1 hyoklee  HDF\\hdf   39675 May 25 16:07 .gitattributes
  drwxrwxr-x@   7 hyoklee  HDF\\hdf     224 May 25 16:07 .github
  -rw-rw-r--@   1 hyoklee  HDF\\hdf     833 May 25 16:07 .gitignore
  -rw-rw-r--@   1 hyoklee  HDF\\hdf    1530 May 25 16:07 .h5chkright.ini
```

**Expected behavior**

Remove them.

**Platform (please complete the following information)**
 - HDF5 version: develop
 
**Additional context**

It's nice to see snapshot on GitHub!

**Comment by hyoklee** [comment]
@byrnHDF wrote release.yml.

**Comment by lrknox** [comment]
The latest release produced by bin/release also contains 5 of these files beginning with '.'.  The files not in the latest release are .DS_Store and .gitignore.  The tar command in bin/release includes the option --exclude-vcs (exclude version control system directories) which probably accounts for no .gitignore in the release tar files.  There are other --exclude options  that could possibly be used to exclude all . files.

**Comment by byrnHDF** [comment]
Those files all exist in the repo, if they should not be wanted in the source tarball they should not be in the repo. They should be added to .gitignore file.
