### ISSUE TITLE
Embedded nulls not correctly read via DataSet::p_read_fixed_len

### ISSUE THREAD

**Issue by mkitti** [HDFGroup/hdf5#3034]
**Describe the bug**
Fixed length strings are copied to `H5std_string` (`std::string`) as if they were null terminated C strings. This incorrect if the fixed length string contains embedded null bytes.

This is because `string& operator= (const char* s)` is used on line 732 here:

https://github.com/HDFGroup/hdf5/blob/81bc34ac4c3f42532edee32095651f6bcd5e55a2/c%2B%2B/src/H5DataSet.cpp#L711-L735

**Expected behavior**
Fixed length strings with embedded null bytes should be correctly read into the `std::string`.

Line 732 should probably be

```
strg = H5std_string(strg_C, data_size);
```

**Platform (please complete the following information)**
 - HDF5 version 1.14.0
 - macOS 13.3.1
 - Apple clang version 14.0.3 (clang-1403.0.22.14.1)
 - cmake

**Additional context**

**Comment by mkitti** [comment]
To illustrate the issue, here's an example C++ program.

```cpp
#include <string>
#include <iostream>

int main ()
{
    std::string str1, str2;
    const char* str_data = "Test\0string";
    const int str_data_len = 11;

    /* Uses string& operator= (const char* s), truncates at first null byte */
    str1 = str_data;

    /* uses string& operator= (const string& str), embedded null byte is included */
    str2 = std::string(str_data, str_data_len);

    std::cout << "str1: " << str1 << '\n';
    std::cout << "str2: " << str2 << '\n';
    return 0;
}
```

The output of this is as follows.
```
str1: Test
str2: Teststring
```

**Comment by hyoklee** [comment]
@mkitti , thank you so much for your report.

@derobins modified the code 2 years ago so I assigned this to him.

**Comment by mkitti** [comment]
@steven-varga What are your thoughts about this?

**Comment by mkitti** [comment]
[Ultrafeel](https://github.com/Ultrafeel) seems to have recognized the same issue:
https://github.com/HDFGroup/hdf5/commit/c1ad3676c4b56b80663d271ac367a65cc41c39ab#r88347289

**Comment by steven-varga** [comment]
@mkitti Hi Mark,  from the [DDL](https://docs.hdfgroup.org/hdf5/develop/_d_d_l_b_n_f110.html)
```
<string> ::= H5T_STRING {
                 STRSIZE <strsize>;
                 STRPAD <strpad>;
                 CSET <cset>;
                 CTYPE <type>;
             }
<strsize> ::= <int_value>
<strpad> ::= H5T_STR_NULLTERM | H5T_STR_NULLPAD | H5T_STR_SPACEPAD
<cset> ::= H5T_CSET_ASCII | H5T_CSET_UTF8
```
The DDL resembles to an EBNF variant, and doesn't give a precise definition of `H5T_CSET_ASCII` and `H5T_CSET_UTF8` nor to `H5T_STR_NULLTERM`  The official `set` for both contain the `\0` byte. From here  this really goes downhill for me:   `<ctype> ::= H5T_C_S1 | H5T_FORTRAN_S1` allows both C or Fortran style strings, and Fortran allows `\0` so my current interpretation of the above DDL has changed: yes HDF5 allows `\0` in some strings, and the inverse mapping should consider if `H5T_FORTRAN_S1` set or not.

**Comment by mkitti** [comment]
Proposed fix:
https://github.com/HDFGroup/hdf5/commit/003935edae94a5574409dcb93b6ee0f835ff6765

https://github.com/HDFGroup/hdf5/pull/3083
