### ISSUE TITLE
[BUG] 1.14.1-2 - szip/libaec decode missing when building with CMake.

### ISSUE THREAD

**Issue by jwsblokland** [HDFGroup/hdf5#3036]
**Describe the bug**
The szip/libaec decode filter functionality is missing in HDF5 1.14.1-2 when I build the library using CMake. I used libaec 1.0.6 for the szip (de)compression. Cmake does find libaec library. 

**Expected behavior**
Both the encoding and decoding functionality of szip/libaec should be present.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.1-2 (serial)
 - RHEL 7.9
 - intel/2021a (easybuild)
 - CMake 3.23

**Additional context**
This bug is fixed in pull request #3035

**Comment by byrnHDF** [comment]
Merged into all branches
