### ISSUE TITLE
HDF5Array.java arrayify method is missing break statement causing exception

### ISSUE THREAD

**Issue by bpatters** [HDFGroup/hdf5#3056]
**Describe the bug**
There HDF5Array.arrayify method is missing a `break` statement in the `case 'L':` section which causes it to fall through and throw an HDF5JavaException when attempting to read an Array[Array[Long]].

**Expected behavior**
after converting from the Byte[] to a Long[] it should have a break statement so the flattened array is returned.

**Platform (please complete the following information)**
 - 1.14.1
 - macos arm64 prebuilt binaries

**Additional context**

You can see the case statement missing the break in the source code [here](https://github.com/HDFGroup/hdf5/blob/2384a731763a7ceb11e39d48cc0f6991d908389e/java/src/hdf/hdf5lib/HDFArray.java#L440)

**Comment by derobins** [comment]
Fixed in #3060  but needs a release note

**Comment by byrnHDF** [comment]
See PR #3117

**Comment by byrnHDF** [comment]
Implemented

**Comment by bpatters** [comment]
Thanks so much for the quick fix for this, I really appreciate it. What's standard release cycle for the HDF5 releases where this might make it it into a fix release?
