### ISSUE TITLE
Don't create `utils/subfiling_vfd/h5fuse.sh` if `--enable-subfiling-vfd` is not used.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#3089]
**Describe the bug**

I see this message although I did not enable `subfiling_vfd`.

`config.status: creating utils/subfiling_vfd/h5fuse.sh`

**Expected behavior**

  I should not see the above message.

**Platform (please complete the following information)**
 - HDF5 version: Develop
 - OS and version: Ubuntu 22.04
 - Compiler and version: n/a
 - Build system: Autotools

**Comment by derobins** [comment]
Configure processes all the .in files, regardless of what is being built. This is expected behavior.
