### ISSUE TITLE
Continuous fuzzing through OSS-fuzz

### ISSUE THREAD

**Issue by AdamKorcz** [HDFGroup/hdf5#309]
I have been working on setting up continuous fuzzing of hdf5 by way of Libfuzzer and OSS-fuzz.

Fuzzing of hdf5 has been discussed here: https://github.com/HDFGroup/hdf5/pull/263#issuecomment-766171426 and here: https://github.com/HDFGroup/hdf5/issues/272.

Tagging @schwehr since you suggested integrating with OSS-fuzz.

I have set up a draft integration over at OSS-fuzz here: https://github.com/google/oss-fuzz/pull/5103.
Feel free to leave any comments over there.

It is free to integrate with OSS-fuzz, and it is expected that bugs are fixed, so that the resources spent on fuzzing hdf5 go towards resolving bugs in the code base.

To finish the integration, at least one maintainers email is needed for bug reports.

I recommend moving the fuzzer and the build script upstream to easier maintain them.

**Comment by derobins** [comment]
We're set up to use oss-fuzz now
