### ISSUE TITLE
hdf5 1.14.1-2 soname error with amd aocc compiler amd/aocc/4.0.0

### ISSUE THREAD

**Issue by feiliuesmf** [HDFGroup/hdf5#3125]
Hello, I would like to report a problem with the amd compilers that are gaining popularity on the amd cpu based HPC machines.

Building hdf5 with -fPIC and shared library enabled leads to the following error:

  FCLD     libhdf5_fortran.la
clang-14: error: unknown argument: '-soname'
clang-14: error: no such file or directory: 'libhdf5_fortran.so.310'

quick googling shows this is due to amd compiler using a slight different syntax to generate shared library, see the link below

https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/368
Just replace

-Wl,-soname,libphpcpp.so.$(SONAME)
with

-Wl,-install_name,libphpcpp.so.$(SONAME)
in Makefile.

Will be happy to test when a version of hdf5 is available that works with amd compilers with shared library enabled. Thanks,

**Comment by byrnHDF** [comment]
Is this with autotools or cmake?

**Comment by byrnHDF** [comment]
That must be a function of the build system (autoconf for autotools, cmake) as we do not specify the command. We just set the property of the target to the SONAME value.

**Comment by byrnHDF** [comment]
The build system creates the Makefile and I can find no option for us to control this in either build system.
