### ISSUE TITLE
ICX command line warning for hdf5

### ISSUE THREAD

**Issue by HathewayWill** [HDFGroup/hdf5#3144]
icx: command line warning #10430: Unsupported command line options encountered
These options as listed are not supported.
For more information, use '-qnextgen-diag'.
option list: 
	-Wp64

see attached files

`  ############################# HDF5 library for NetCDF4 & parallel functionality ############################

  cd $WRF_FOLDER/Downloads
  tar -xvzf hdf5-1_14_1-2.tar.gz
  cd hdf5-hdf5-1_14_1-2

  CC=$MPICC FC=$MPIFC CXX=$MPICXX F90=$MPIF90 F77=$MPIF77 CFLAGS=$CFLAGS ./configure --prefix=$DIR/grib2 --with-zlib=$DIR/grib2 --enable-hl --enable-fortran --enable-parallel

  make -j $CPU_HALF_EVEN 2>&1 | tee hdf5.make.log
  make -j $CPU_HALF_EVEN install 2>&1 | tee hdf5.makeinstall.log

  # other libraries below need these variables to be set
  export HDF5=$DIR/grib2
  export LD_LIBRARY_PATH=$DIR/grib2/lib:$LD_LIBRARY_PATH
  export PATH=$HDF5/bin:$PATH
  export PHDF5=$DIR/grib2

  echo " "

`

[config.log](https://github.com/HDFGroup/hdf5/files/11764309/config.log)
[hdf5.make.log](https://github.com/HDFGroup/hdf5/files/11764310/hdf5.make.log)
[hdf5.makeinstall.log](https://github.com/HDFGroup/hdf5/files/11764311/hdf5.makeinstall.log)

**Comment by byrnHDF** [comment]
The Intel warnings files have not been updated since version 18 (5 years ago) and before Intel moved to OneAPI.
The CompilerFlags files also are likely to need updates and maybe distinguish between intel classic and IntelLLVM compilers.

**Comment by derobins** [comment]
This should be fixed w/ #3751, which splits the Intel configuration files into 'classic' and oneAPI.
