### ISSUE TITLE
A Bug in H5VL__native_dataset_optional() of H5VLnative_dataset.c 

### ISSUE THREAD

**Issue by raylu3** [HDFGroup/hdf5#3234]
In the function `H5VL__native_dataset_optional()` of H5VLnative_dataset.c, for the case of `H5VL_NATIVE_DATASET_GET_OFFSET`, the pointer `*opt_args->get_offset.offset` doesn't point to anything.  In the definition of `H5VL_native_dataset_optional_args_t` in H5VLnative.h, `offset` is declared as a pointer: 
```
    /* H5VL_NATIVE_DATASET_GET_OFFSET */            
    struct {
        haddr_t *offset; /* Contiguous dataset's offset in the file (OUT) */
    } get_offset;
```
One solution is changing  the pointer `*offset` to a regular variable in H5VLnative.h.  Another solution is fixing the code in H5VLnative_dataset.c like this:
```
        /* H5Dget_offset */
        case H5VL_NATIVE_DATASET_GET_OFFSET: {
            /* Get offset */
            haddr_t addr = H5D__get_offset(dset);

            opt_args->get_offset.offset = args->args;

            *(opt_args->get_offset.offset) = addr;

            break;
        }   
```

To verify this bug, one can do the following call in a VOL:
```
    H5VL_optional_args_t dset_args;

    dset_args.op_type = H5VL_NATIVE_DATASET_GET_OFFSET;
    dset_args.args = malloc(sizeof(haddr_t));

    H5VL_pass_through_ext_dataset_optional(dset, &dset_args, H5P_DEFAULT, req);

    addr = *((haddr_t *)(dset_args.args));
    free(dset_args.args);
```
The variable `dset` is a pointer to the `H5VL_pass_through_ext_t` type.

**Comment by fortnern** [comment]
The intent with this function, and with other similar H5VL functions, is for the calling function to point the pointer to its own variable for the output. You can look at the code for H5Dget_offset() for an example of this. Let me know if you still think there's a problem here.

**Comment by raylu3** [comment]
Yes, I agree after a closer look at it.  Thanks for checking it.
