### ISSUE TITLE
When CXX, FORTRAN and PARALLEL are all enabled, the compilation fails: no suitable MPI type for size_t

### ISSUE THREAD

**Issue by yurivict** [HDFGroup/hdf5#3235]
**Describe the bug**
```
In file included from /usr/ports/science/hdf5/work/CMake-hdf5-1.12.2/hdf5-1.12.2/hl/c++/src/H5PacketTable.cpp:23:
In file included from /usr/ports/science/hdf5/work/CMake-hdf5-1.12.2/hdf5-1.12.2/hl/src/H5HLprivate2.h:24:
/usr/ports/science/hdf5/work/CMake-hdf5-1.12.2/hdf5-1.12.2/src/H5private.h:532:2: error: "no suitable MPI type for size_t"
#error "no suitable MPI type for size_t"
 ^
```

**Expected behavior**
n/a

**Platform (please complete the following information)**
 - HDF5 version: 1.12.2
 - OS and version: FreeBSD 13.2
 - Compiler and version: clang-15
 - Build system (e.g. CMake, Autotools) and version: cmake
 - Any configure options you specified: see below
 - MPI library and version (parallel HDF5): mpich-3.4.3

cmake options:
-DDEFAULT_API_VERSION=v112  -DHDF5_INSTALL_CMAKE_DIR=lib/cmake/hdf5  -DHDF5_INSTALL_INCLUDE_DIR=/usr/local/include -DHDF5_BUILD_CPP_LIB:BOOL=true -DHDF5_BUILD_EXAMPLES:BOOL=true -DHDF5_TEST_EXAMPLES:BOOL=true -DHDF5_PACK_EXAMPLES:BOOL=true -DHDF5_BUILD_FORTRAN:BOOL=true -DHDF5_ENABLE_PARALLEL:BOOL=true -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -D__LONG_LONG_SUPPORTED -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -Wl,-rpath=/usr/local/lib/gcc12  -L/usr/local/lib/gcc12 -B/usr/local/bin -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DHDF5_BUILD_HL_LIB:BOOL=ON -DHDF5_BUILD_TOOLS:BOOL=ON -DHDF5_ENABLE_INSTRUMENT:BOOL=ON -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON -DHDF5_STRICT_FORMAT_CHECKS:BOOL=ON -DMPIEXEC_EXECUTABLE:FILEPATH="/usr/local/bin/mpiexec"	 -DMPI_HOME:PATH="/usr/local"

**Comment by yurivict** [comment]
@jhendersonHDF Any chance to fix this?
Currently either Fortran users can be allowed, or parallel users, but not both.
This limits what ports can link with hdf5, which is a very bad limitation.

**Comment by jhendersonHDF** [comment]
Hi @yurivict, was HDF5 installed via a package manager? If so, do you happen to know if the FreeBSD project plans to upgrade to the 1.14 series of HDF5 releases at some point? I believe this issue might be caused by some changes made in the HDF5 develop branch / 1.14 development branch for releases that weren't synced back to the 1.12 development branch for releases.

**Comment by derobins** [comment]
Is this still a problem for 1.14? It'd be nice to make sure HDF5 is working properly on FreeBSD.

Kicking this to 1.14.4 since there won't be time before the 1.14.3 to address any issues. We should bulid and test on a FreeBSD VM before the next release, though.

**Comment by derobins** [comment]
Closed due to age/version/lack of response. Please reopen if this is a problem in 1.14.3.

**Comment by yurivict** [comment]
Was this actually fixed?
