### ISSUE TITLE
CMake hdf5-config.cmake.in needs review

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#3251]
hdf5-config.cmake.in section "User Options" needs to be reviewed for completeness and correctness.
Some options do not return expected ON/OFF results.

**Comment by byrnHDF** [comment]
libhdf5.settings considers these as features:
Features:
---------
                     Parallel HDF5: OFF
  Parallel Filtered Dataset Writes: 
                Large Parallel I/O: 
                High-level library: ON
Dimension scales w/ new references: 
                  Build HDF5 Tests: ON
                  Build HDF5 Tools: ON
                   Build GIF Tools: OFF
                      Threadsafety: OFF
               Default API mapping: v116
    With deprecated public symbols: ON
            I/O filters (external):  DEFLATE DECODE ENCODE
                     Map (H5M) API: 
                        Direct VFD: 
                        Mirror VFD: 
                     Subfiling VFD: 
                (Read-Only) S3 VFD: 
              (Read-Only) HDFS VFD: 
    Packages w/ extra debug output: 
                       API Tracing: OFF
              Using memory checker: OFF
            Function Stack Tracing: OFF
                  Use file locking: best-effort
         Strict File Format Checks: OFF
      Optimization Instrumentation:

**Comment by byrnHDF** [comment]
This is what CMake puts in the hdf5_config.cmake file:

#-----------------------------------------------------------------------------
# User Options
#-----------------------------------------------------------------------------
set (${HDF5_PACKAGE_NAME}_ENABLE_PARALLEL OFF)
set (${HDF5_PACKAGE_NAME}_BUILD_FORTRAN   ON)
set (${HDF5_PACKAGE_NAME}_BUILD_CPP_LIB   ON)
set (${HDF5_PACKAGE_NAME}_BUILD_JAVA      ON)
set (${HDF5_PACKAGE_NAME}_BUILD_TOOLS     ON)
set (${HDF5_PACKAGE_NAME}_BUILD_HL_LIB    ON)
set (${HDF5_PACKAGE_NAME}_BUILD_HL_GIF_TOOLS  OFF)
set (${HDF5_PACKAGE_NAME}_ENABLE_THREADSAFE OFF)
set (${HDF5_PACKAGE_NAME}_ENABLE_PLUGIN_SUPPORT ON)
set (${HDF5_PACKAGE_NAME}_ENABLE_Z_LIB_SUPPORT ON)
set (${HDF5_PACKAGE_NAME}_ENABLE_SZIP_SUPPORT  ON)
set (${HDF5_PACKAGE_NAME}_ENABLE_SZIP_ENCODING ON)
set (${HDF5_PACKAGE_NAME}_ENABLE_ROS3_VFD      OFF)
set (${HDF5_PACKAGE_NAME}_ENABLE_SUBFILING_VFD OFF)
set (${HDF5_PACKAGE_NAME}_BUILD_SHARED_LIBS    YES)
set (${HDF5_PACKAGE_NAME}_BUILD_STATIC_LIBS    YES)
set (${HDF5_PACKAGE_NAME}_PACKAGE_EXTLIBS      ON)
set (${HDF5_PACKAGE_NAME}_EXPORT_LIBRARIES hdf5-static;hdf5-shared;hdf5_tools-static;hdf5_tools-shared;hdf5_hl-static;hdf5_hl-shared;hdf5_f90cstub-static;hdf5_f90cstub-shared;hdf5_fortran-static;hdf5_fortran-shared;hdf5_hl_f90cstub-static;hdf5_hl_f90cstub-shared;hdf5_hl_fortran-static;hdf5_hl_fortran-shared;hdf5_cpp-static;hdf5_cpp-shared;hdf5_hl_cpp-static;hdf5_hl_cpp-shared;hdf5_java)
set (${HDF5_PACKAGE_NAME}_ARCHITECTURE "")
set (${HDF5_PACKAGE_NAME}_TOOLSET "")
set (${HDF5_PACKAGE_NAME}_DEFAULT_API_VERSION "v116")
set (${HDF5_PACKAGE_NAME}_PARALLEL_FILTERED_WRITES )
set (${HDF5_PACKAGE_NAME}_INSTALL_MOD_FORTRAN "NO")

**Comment by derobins** [comment]
Fixed in #3725
