### ISSUE TITLE
make doxygen returns error

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#3262]
For HDF5 develop and autotools, the **make doxygen** command is failing with:

Generating directory documentation...
Generating index page...
Generating main page...
finalizing index lists...
writing tag file...
Running plantuml with JAVA...
type lookup cache used 11017/65536 hits=174357 misses=12176
symbol lookup cache used 14966/65536 hits=255417 misses=14966
finished...
Exiting...
make: *** [Makefile:1188: hdf5lib_docs/hdf5.tag] Error 1

This is with Doxygen 1.9.8 and linux.

**Comment by byrnHDF** [comment]
But where is the error?

**Comment by brtnfld** [comment]
That line listed in the makefile, it appears it could not execute it.

**Comment by byrnHDF** [comment]
Can you attach the whole log? There has to be another hint somewhere.

**Comment by derobins** [comment]
Do we need to disable doxygen warnings as errors?

**Comment by byrnHDF** [comment]
[10:37 AM] Scot Breitenfeld

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:949: error: argument 'loc_id' from the argument list of H5Giterate has multiple @param documentation sections

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:949: error: argument 'name' from the argument list of H5Giterate has multiple @param documentation sections

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:949: error: argument 'idx' from the argument list of H5Giterate has multiple @param documentation sections

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:949: error: argument 'op' from the argument list of H5Giterate has multiple @param documentation sections

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:949: error: argument 'op_data' from the argument list of H5Giterate has multiple @param documentation sections

/home/brtnfld/packages/hdf5/src/H5Gpublic.h:654: error: argument 'cur_loc_id' from the argument list of H5Glink has multiple @param documentation sections

**Comment by byrnHDF** [comment]
Maybe it is getting confused with the deprecated version in H5Gdeprec.c? Possibly exclude the *deprec.c files?

**Comment by derobins** [comment]
We should remove the "warnings as errors" stuff from the default build and pass it as a build option in CI. This would protect against Doxygen flakiness.

We can always change the CI if the runners start using a flaky version of Doxygen.

**Comment by derobins** [comment]
Fixed in #3708
