### ISSUE TITLE
[doc?] transfer between dataspaces of different layouts

### ISSUE THREAD

**Issue by chacha21** [HDFGroup/hdf5#3302]
I want to transfer data between multi-dimensional datasets storing the same data, but with a different interleaving (layout).
For instance, let's assume a 2D dataset D1 with dimensions x,y, while D2 will rather store y,x
I assumed that the Dataspace  abstraction would let me specify the data layout re-interleaving during dataset read/writes, but I can't find where it is.
In [this example](https://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/12_Dataspaces.html#DTransfer), magic seems to occur if the dimensions do not match, (3x4 vs 4x3) but it does not describe what would happen if the max dimensions happened to be the same (4x4), how would it guess the transpose ?
What is the expected way to specify data [de/re ]interleaving during a data transfer ?

**Comment by mattjala** [comment]
Questions are better suited for the [HDF forum](https://forum.hdfgroup.org/). We use Github issues for bug/request tracking. Please move this to a new forum thread in the HDF5 section. Thanks!

**Comment by chacha21** [comment]
For anyone that found this thread  : [https://forum.hdfgroup.org/t/transfer-between-dataspaces-of-different-layouts/11380/2](https://forum.hdfgroup.org/t/transfer-between-dataspaces-of-different-layouts/11380/2)
