### ISSUE TITLE
assertion failure in H5D__mpio_collective_filtered_vec_io

### ISSUE THREAD

**Issue by qkoziol** [HDFGroup/hdf5#3337]
**Describe the bug**
Crash in t_pmulti_dset test:

Configuration:
  Layout:           Chunked
  Shape same:       No
  I/O type:         Single
  MPI I/O type:     Collective
  Low level MPI I/O:Collective
  Type conversion:  No
  Data filter:      Yes
Testing random I/O                                                    Assertion failed: (vec_idx < iovec_count), function H5D__mpio_collective_filtered_vec_io, file H5Dmpio.c, line 5498.

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 91513 RUNNING AT Nile.local
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Terminated: 15 (signal 15)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
        7.23 real        33.77 user         8.05 sys
make[3]: *** [t_pmulti_dset.chkexe_] Error 1
make[2]: *** [build-check-p] Error 1
make[1]: *** [test] Error 2
make: *** [check-am] Error 2

**Expected behavior**

**Platform (please complete the following information)**
Current version of the develop branch, on my Mac, with this configuration:

env CC=mpicc CXX=mpic++ FC=mpif90 ../hdf5/configure --enable-build-mode=debug --enable-maintainer-mode --enable-developer-warnings --enable-diags --disable-shared --enable-parallel --enable-cxx --enable-fortran --enable-map-api --enable-threadsafe --enable-build-all --enable-mirror-vfd --enable-subfiling-vfd --enable-unsupported

**Additional context**

**Comment by qkoziol** [comment]
@jhendersonHDF - related to your recent PR?

**Comment by jhendersonHDF** [comment]
Hmm yes, though I don't know why I didn't see this.
