### ISSUE TITLE
Make use of C++11 `override`

### ISSUE THREAD

**Issue by seanm** [HDFGroup/hdf5#334]
Even if HDF5 doesn't require at least C++11, it could use the `override` keyword conditionally like this:

```
#if defined __cplusplus && 201103L <= __cplusplus
#define HDF_OVERRIDE override
#else
#define HDF_OVERRIDE
#endif
```

In projects that now require C++11, like VTK and ITK, HDF5 headers are now causing lots of compile warnings from, for example, clang's -Wsuggest-override -Wsuggest-destructor-override warnings.

Suppressing these warnings isn't a great idea as `override` is great for finding mistakes.

I could make a patch if it would be accepted...

**Comment by qkoziol** [comment]
Could you give an example in the source code where the override keyword is used?  I grep'ed through the codebase and didn't see anything (at least from a quick read).

**Comment by seanm** [comment]
Sorry, where I said "could use" I should have said "should use".  What I'm suggesting is that someone should sprinkle `override` keywords everywhere/appropriately in the HDF5 codebase.  The lack of them is causing warnings in projects that use HDF5.

If C++11 is already your minimum, then the actual `override` keyword should be used.  If you still need C++98 support, the `#define` trick should be used.

If you let me know your minimum C++, and will accept such a patch, I offer one.

**Comment by seanm** [comment]
@qkoziol maybe `H5api_adpt.h` would be a good place to add an `HDF_OVERRIDE` macro?

It already has things like `#define H5TEST_DLL    __attribute__((visibility("default")))`

**Comment by qkoziol** [comment]
I did a little more research on the override keyword and it's only relevant to the C++ methods, so it may be better in one of the C++ -specific headers.

@bmribler - Any opinions?

**Comment by bmribler** [comment]
Yes, it can be in H5Cpp.h.

**Comment by seanm** [comment]
And what is your minimum C++ version?  Do we even need a macro or can `override` be used directly?

**Comment by bmribler** [comment]
C++98 and we need the macro.

**Comment by seanm** [comment]
How should I spell it?  `HDF_OVERRIDE`? `HOVERRIDE`? `H5OVERRIDE`?

**Comment by bmribler** [comment]
Oh, I thought we're going to do that.  My guess is H5_OVERRIDE, but I'll bring it up with the group to make sure.

**Comment by seanm** [comment]
It's something someone like me, that doesn't know the codebase, can still easily do.

**Comment by bmribler** [comment]
H5_OVERRIDE can be used.  Thanks!

**Comment by seanm** [comment]
A tangentially-related question: what is HDF5's minimum C version?  C17? C11? C99? C89?

**Comment by qkoziol** [comment]
> A tangentially-related question: what is HDF5's minimum C version? C17? C11? C99? C89?

C99 officially, but we'd like to move up to at least C11 if possible.

**Comment by seanm** [comment]
WIP here: https://github.com/HDFGroup/hdf5/pull/433

@bmribler but `H5Cpp.h` doesn't work for me, it seems to not be included by any of the headers where I added `override`

**Comment by derobins** [comment]
This has been done in develop and has a hack in other branches.

**Comment by seanm** [comment]
Additional fixes here: https://github.com/HDFGroup/hdf5/pull/1812
