### ISSUE TITLE
Reduce number of S3 requests on file open in ros3 VFD

### ISSUE THREAD

**Issue by ajelenak** [HDFGroup/hdf5#3381]
When opening HDF5 files with the ros3 VFD, the VFD always makes something like the four separate S3 requests below for tiny amount of bytes at the beginning of the file:

```
GET: Bytes 0 - 7, Request Size: 8
GET: Bytes 0 - 15, Request Size: 16
GET: Bytes 16 - 95, Request Size: 80
GET: Bytes 96 - 607, Request Size: 512
```

Would it be possible to have ros3 VFD make a single request for a larger amount of bytes on file open and cache it somehow to satisfy multiple libhdf5 data reads? The request size could be configurable. Something like 16 MiB default could be really helpful because a lot of useful information can be packed at the beginning of an HDF5 file (thinking about cloud-optimized HDF5 files).

**Comment by derobins** [comment]
Fixed in #3753, but we may want to expand on that in the future.
