### ISSUE TITLE
How are links saved with order tracking enabled?

### ISSUE THREAD

**Issue by woutdenolf** [HDFGroup/hdf5#339]
When creating an HDF5 file with tracking order enabled on the root and more than 8 top-level groups, I do not see any top-level links when iteration over the data objects starting from the superblock. How are links expected to be saved? When I go from 8 to 9 top-level HDF5 groups, the file structure seems to change drastically.

FYI I'm doing this in an attempt to reconstruct a corrupt HDF5 file (the disk got full during writing which corrupts the file apparently). The hdf5-devel utilities do not seem to contain a utility that does this.

See https://github.com/jjhelmus/pyfive/issues/46 for versions and example.

**Comment by derobins** [comment]
Hi, apologies for getting to this so late, but we're asking that questions about HDF5 be asked on the forum and not created as GitHub issues.

https://forum.hdfgroup.org/
