### ISSUE TITLE
Increase in memory usage when using H5Aread / H5DSget_num_scales in a loop opening and closing files.

### ISSUE THREAD

**Issue by planetMDX** [HDFGroup/hdf5#3396]
**Describe the bug**
When opening a file and using `H5Aread` or `H5DSget_num_scales` (which calls `H5Aread`) in a loop, a conversion path gets added, which is neither deallocated at the end of the loop nor reused in future iterations of the loop. This only happens once per opening of the file.

**Expected behavior**
Memory usage stays consistent

**Platform (please complete the following information)**
 - hdf5-versions: release 1.14.1 and building on branch develop with commit ffde055be2995ea62ee5ccbcb9c3a838b1fed229
 - os: arch linux
 - compiler: gcc 13.2.1
 - biuld tool: cmake
 - configure options for building from develop: HDF5_ENABLE_DEBUG_APIS=true

**Additional context**
Program for reproduction
```
#include <H5public.h>
#include <H5Apublic.h>
#include <H5DSpublic.h>
#include <H5Fpublic.h>
#include <H5Gpublic.h>
#include <H5LTpublic.h>
#include <H5Ppublic.h>
#include <H5Tpublic.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv) {
    int iterations = 1000;
    if (argc > 1) { iterations = atoi(argv[1]); }
    const char *fp =
        "/home/plane/Documents/meteoblue/hdf5docker/OMI-Aura_L2-example.nc";
    if (argc > 3) { fp = argv[3]; }
    int ret_val = 0;
    printf("iterations: %d\tfilepath: %s\n", iterations, fp);
    H5open();
    for (int c = 0; c < iterations; ++c) {
        hid_t fapl = -1, file = -1, did = -1;
        int   nsc = 0;
        if ((fapl = H5Pcreate(H5P_FILE_ACCESS)) == H5I_INVALID_HID) {
            ret_val = EXIT_FAILURE;
            goto fail_fapl;
        }
        unsigned mode = H5F_ACC_RDONLY;
        if ((file = H5Fopen(fp, mode, fapl)) == H5I_INVALID_HID) {
            ret_val = EXIT_FAILURE;
            goto fail_file;
        }
        did = H5Dopen2(file, "/LATITUDE", H5P_DEFAULT);
        if (did < 0) {
            ret_val = EXIT_FAILURE;
            goto end;
        }
        nsc = H5DSget_num_scales(did, 0);
    end:
        if (did >= 0) H5Dclose(did);
        if (file >= 0) H5Fclose(file);
    fail_file:
        if (fapl >= 0) H5Pclose(fapl);
    fail_fapl:;
        if (ret_val == EXIT_FAILURE) { abort(); }
    }
    _Exit(0);
}
```
valgrind results:
looping 300 times: [hdf11_log.zip](https://github.com/HDFGroup/hdf5/files/12392106/hdf11_log.zip)
looping 5000 times: [hdf12_log.zip](https://github.com/HDFGroup/hdf5/files/12392109/hdf12_log.zip)

The problem doesn't appear with hdf5 version 1.10.10.
As a large part of the memory build up happens in `H5T__path_find_real` and a new conversion path in `H5T_g` gets added per iteration, I believe the problem is a failure in `H5T_cmp` not detecting two types from the same file as equal.
This might happen because in [H5T.c:4616](https://github.com/HDFGroup/hdf5/blob/ffde055be2995ea62ee5ccbcb9c3a838b1fed229/src/H5T.c#L4616C1-L4619C31)
```
            if (dt1->shared->u.vlen.file < dt2->shared->u.vlen.file)
                HGOTO_DONE(-1);
            if (dt1->shared->u.vlen.file > dt2->shared->u.vlen.file)
                HGOTO_DONE(1);
```
a pointer to a `H5VL_object_t` get used for comparison, which seem to be not equal if the file was closed and opened again, while the `H5F_t` pointer used in version 1.10.10 seem to not have this issue.
Replacing those lines with:
```
            if (dt1->shared->u.vlen.file && dt2->shared->u.vlen.file) {
                if (dt1->shared->u.vlen.file->data < dt2->shared->u.vlen.file->data)
                    HGOTO_DONE(-1);
                if (dt1->shared->u.vlen.file->data > dt2->shared->u.vlen.file->data)
                    HGOTO_DONE(1);
            }
            else {
                if (dt1->shared->u.vlen.file < dt2->shared->u.vlen.file)
                    HGOTO_DONE(-1);
                if (dt1->shared->u.vlen.file > dt2->shared->u.vlen.file)
                    HGOTO_DONE(1);
            }

```
fixes the memory buildup, but I'm not sure if this is correct.

**Comment by planetMDX** [comment]
I have observed the same problematic behaviour when reading an attribute of a `H5T_COMPOUND` type featuring a `H5T_REFERENCE` type, which is also features the same comparison on the `H5VL_object_t` pointer in [H5T.c:4765](https://github.com/HDFGroup/hdf5/blob/f61522ec4d080c6a62285bd530b4851e03771014/src/H5T.c#L4765C30-L4765C30).  
Should I open a seperate issue for that?

**Comment by jhendersonHDF** [comment]
@planetMDX It's difficult to be 100% certain without the test file used in this program, but this should be addressed with https://github.com/HDFGroup/hdf5/commit/f86fe61c7f6fa43cc16d555f9c925e43baa3de8f and https://github.com/HDFGroup/hdf5/commit/d8af09dd8f064c97c4120b2a5d1cfd1103526d07 for the upcoming 1.14.4 release. Feel free to reopen if this is not the case.
