### ISSUE TITLE
arm64-v8a,run ctest,H5TEST-cache_logging run Segmentation fault 

### ISSUE THREAD

**Issue by albert20081010** [HDFGroup/hdf5#3397]
**Describe the bug**
RK3568(arm64-v8a,clang build release),env: 

    export AS=${OHOS_SDK}/native/llvm/bin/llvm-as
    export CC=${OHOS_SDK}/native/llvm/bin/aarch64-linux-ohos-clang
    export CXX=${OHOS_SDK}/native/llvm/bin/aarch64-linux-ohos-clang++
    export LD=${OHOS_SDK}/native/llvm/bin/ld.lld
    export STRIP=${OHOS_SDK}/native/llvm/bin/llvm-strip
    export RANLIB=${OHOS_SDK}/native/llvm/bin/llvm-ranlib
    export OBJDUMP=${OHOS_SDK}/native/llvm/bin/llvm-objdump
    export OBJCOPY=${OHOS_SDK}/native/llvm/bin/llvm-objcopy
    export NM=${OHOS_SDK}/native/llvm/bin/llvm-nm
    export AR=${OHOS_SDK}/native/llvm/bin/llvm-ar
    export CFLAGS="-DOHOS_NDK -fPIC -D__MUSL__=1"
    export CXXFLAGS="-DOHOS_NDK -fPIC -D__MUSL__=1"
    export LDFLAGS=""

log out:
```
65/2230 Testing: H5TEST-cache_logging
65/2230 Test: H5TEST-cache_logging
Command: "/usr/local/bin/cmake" "-D" "TEST_EMULATOR=" "-D" "TEST_PROGRAM=/data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/bin/cache_logging" "-D" "TEST_ARGS:STRING=" "-D" "TEST_EXPECT=0" "-D" "TEST_SKIP_COMPARE=TRUE" "-D" "TEST_OUTPUT=cache_logging.txt" "-D" "TEST_LIBRARY_DIRECTORY=/data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/bin" "-D" "TEST_FOLDER=/data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/test/H5TEST" "-P" "/data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/config/cmake/runTest.cmake"
Directory: /data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/test/H5TEST
"H5TEST-cache_logging" start time: Aug 07 13:59 UTC

Output:
----------------------------------------------------------
-- Require TEST_EXPECT to be defined
-- COMMAND:  /data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/bin/cache_logging 
-- COMMAND Result: Segmentation fault
-- Output :
Testing basic metadata cache logging functionality.
Testing metadata cache log api calls                                  
CMake Error at /data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/config/cmake/runTest.cmake:124 (message):
  Failed: Test program
  /data/local/lycium/main/hdf5/hdf5-hdf5-1_14_1-2/arm64-v8a-build/bin/cache_logging
  exited != 0.



<end of output>
Test time =   0.51 sec
----------------------------------------------------------
Test Failed.
"H5TEST-cache_logging" end time: Aug 07 13:59 UTC
"H5TEST-cache_logging" time elapsed: 00:00:00
```

**Expected behavior**
H5TEST-cache_logging run passed .

**Platform (please complete the following information)**
 - HDF5 version :hdf5-1_14_1-2
 - OS and version: OpenHarmony4.0.8.1
 - Compiler and version
 - Build system (e.g. CMake, Autotools) and version: cmake version 3.26.3
 - Any configure options you specified:
 ```
 cmake  -DOHOS_ARCH=$ARCH -B$ARCH-build -S./ -DH5_LONG_TO_LDOUBLE_SPECIAL_RUN="advanced" -DH5_LONG_TO_LDOUBLE_SPECIAL_RUN__TRYRUN_OUTPUT="advanced" \
    -DH5_LDOUBLE_TO_LONG_SPECIAL_RUN="advanced" -DH5_LDOUBLE_TO_LONG_SPECIAL_RUN__TRYRUN_OUTPUT="advanced" -DH5_LDOUBLE_TO_LLONG_ACCURATE_RUN="advanced" \
    -DH5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT="advanced" -DH5_LLONG_TO_LDOUBLE_CORRECT_RUN="advanced" -DH5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT="advanced" \
    -DH5_DISABLE_SOME_LDOUBLE_CONV_RUN="advanced" -DH5_DISABLE_SOME_LDOUBLE_CONV_RUN__TRYRUN_OUTPUT="advanced" -DHDF5_BUILD_CPP_LIB=ON -L
```
 - MPI library and version (parallel HDF5)

**Additional context**

**Comment by derobins** [comment]
I don't suppose you could run the cache_logging test in a debugger and get us a backtrace?

**Comment by hyoklee** [comment]
Hi, @albert20081010!

Thank you for the bug report.

Can you try the latest HDF5 (develop branch)?

For me, gcc cross compiler passes the test:

https://my.cdash.org/tests/144890408

If develop version of HDF5 still fails, I think the issue is with OHOS clang compiler.

**Comment by hyoklee** [comment]
@albert20081010 , I also built the latest HDF5 with OpenHarmony SDK on my mac:

```
cmake·-DCMAKE_TOOLCHAIN_FILE=/Users/hyoklee/Library/Huawei/Sdk/openharmony/9/native/build\
/cmake/ohos.toolchain.cmake·\$
······-DOHOS_ARCH=arm64-v8a·\$
······-DBUILD_SHARED_LIBS:BOOL="OFF"·\$
······-DBUILD_STATIC_LIBS:BOOL="ON"·\$
······..$
```

The test passed on my debian:latest aarch64 Docker:
```
root@8d0a7ce18fe5:/# ./cache_logging
Testing basic metadata cache logging functionality.
Testing metadata cache log api calls                                   PASSED
All Metadata Cache Logging tests passed.
```
