### ISSUE TITLE
Error of hdf5 make with ifx and mpi

### ISSUE THREAD

**Issue by hurricane642** [HDFGroup/hdf5#3399]
**Describe the bug**
Dear developers, 
While building hdf5 version 1.14.2 inside a Docker image, an unexpected error occurred. The configuration was successful, but the operation failed when executing the `make -j 8` command.

**Expected behavior**
Make operation error when trying to build parallel hdf5 using Intel's new compilers

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): hdf5-1.14.2
 - Docker base image: intel/oneapi-hpckit:2023.2.1-devel-ubuntu22.04 
 - Compiler and version: mpiicx, mpiicpx, mpiifx, version 2021.10 (latest)
 - Any configure options you specified:     
```
    CC=mpiicx CXX=mpiicpx FC=mpiifx ./configure --enable-parallel --enable-build-mode=production \
    --prefix=/opt/hdf5 --enable-fortran --enable-static --enable-shared --with-pic \
    CFLAGS=-O3 FFLAGS=-O3 CXXFLAGS=-O3 && \
```

**Additional context**
The final message which I obtain:
```
ifx: command line warning #10006: ignoring unknown option '-rpath'
ifx: command line warning #10006: ignoring unknown option '-rpath'
ifx: error #10236: File not found: '/opt/hdf5/lib'
ifx: command line warning #10006: ignoring unknown option '-soname'
ifx: error #10236: File not found: 'libhdf5_fortran.so.310'
make[3]: *** [Makefile:1058: libhdf5_fortran.la] Error 1
make[3]: Leaving directory '/opt/hdf5-1.14.2/fortran/src'
make[2]: *** [Makefile:963: all] Error 2
make[2]: Leaving directory '/opt/hdf5-1.14.2/fortran/src'
make[1]: *** [Makefile:901: all-recursive] Error 1
make[1]: Leaving directory '/opt/hdf5-1.14.2/fortran'
make: *** [Makefile:729: all-recursive] Error 1
```
Configure file and config.log attached as well
[config.zip](https://github.com/HDFGroup/hdf5/files/12399347/config.zip)

**Comment by hyoklee** [comment]
This may help you to debug the issue: https://github.com/HDFGroup/hdf5/pull/2977/commits/5c03a07285c9fc445abafcc621fb7bdc19f788a1

**Comment by hurricane642** [comment]
Great, thank you, @hyoklee , it works great!
