### ISSUE TITLE
Add missing row for the ROS3 VFD in table

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#3415]
https://github.com/HDFGroup/hdf5/blob/81fc47cc06dd162940b39b99b25c3708db026b0a/doxygen/examples/tables/propertyLists.dox#L378

**Comment by byrnHDF** [comment]
Both propertyLists.dox and fileDriverLists.dox are missing entries.

**Comment by byrnHDF** [comment]
The doxygen description for H5Pget_driver() in H5Ppublic.h should be reviewed as well.

**Comment by byrnHDF** [comment]
Fixed by #3517
