### ISSUE TITLE
Should plugins free the incoming buffer with POSIX `free()` or `H5free_memory()`

### ISSUE THREAD

**Issue by robertu94** [HDFGroup/hdf5#348]
According to the documentation, if a filter plugin does not operate in place, that `*buf` should be freed using `free` however, on my linux system, this causes a segfault.  I found a comment in the release notes that I should use `H5free_memory` to free any memory allocated by HDF5.  Could this documentation be updated?

https://github.com/HDFGroup/hdf5/blob/2ea165efd095d8876639814dc615dd01a2ec34e6/src/H5Zpublic.h#L503

**Comment by derobins** [comment]
Fixed in develop, will propagate to other maintenance branches
