### ISSUE TITLE
h5py action fails tests

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#3480]
============ 9 failed, 704 passed, 29 skipped, 2 warnings in 11.18s ============
Summary of the h5py configuration
---------------------------------

h5py    3.9.0
HDF5    1.15.0
Python  3.10.12 (main, Sep  1 2023, 01:13:50) [GCC 12.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.25.2
cython (built with) 0.29.36
numpy (built against) 1.25.2
HDF5 (built against) 1.15.0

**Comment by ajelenak** [comment]
Where can I see the test failures?

**Comment by hyoklee** [comment]
@ajelenak , you can see from [here](https://github.com/HDFGroup/hdf5/actions/runs/6043828095/job/16401499691)

Please pay attention to this error:
```
>       with File(fname, mode='r', page_buf_size=pbs-1) as f:

spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-12.3.0/py-h5py-master-gjdiidizjfe33hah7cxp7jvnodyonv33/lib/python3.10/site-packages/h5py/tests/test_file.py:236: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-12.3.0/py-h5py-master-gjdiidizjfe33hah7cxp7jvnodyonv33/lib/python3.10/site-packages/h5py/_hl/files.py:567: in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
spack/opt/spack/linux-ubuntu22.04-broadwell/gcc-12.3.0/py-h5py-master-gjdiidizjfe33hah7cxp7jvnodyonv33/lib/python3.10/site-packages/h5py/_hl/files.py:231: in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OSError: Unable to synchronously open file (page buffering is disabled for parallel)
```

You can ignore these errors:
```
- ('earliest', 'latest')
?               ^^^^^^

+ ('earliest', 'v114')
?               ^^^^
```

**Comment by ajelenak** [comment]
Can you run these tests from a branch of my h5py fork to avoid making more commits to the h5py master?

I recommend switching to the pytest command to run tests. This should avoid the errors about unknown pytest markers.

**Comment by ajelenak** [comment]
Here's the branch with the fix for page buffer cache test failures: https://github.com/ajelenak/h5py/tree/pytest-pb-fix.

To avoid file format version tests, run tests with this command: `pytest -k "not TestNewLibver"`.

**Comment by derobins** [comment]
@hyoklee says this is an h5py problem, not an HDF5 problem. Closing.

**Comment by ajelenak** [comment]
Depends how important it is to run h5py tests using the libhdf5 development branch. The test failures @hyoklee specifically mentioned above are due to h5py not being designed for development libhdf5 code. I have given the pytest command to use to avoid those failing tests.

The other test failures are due to: (1) testing with parallel build of libhdf5 (have provided a fix that needs to be added to h5py), and (2) wrong invocation of the pytest command in this repo's actions.
