### ISSUE TITLE
Unclear which prop-list args are unused in H5Acreate2

### ISSUE THREAD

**Issue by markcmiller86** [HDFGroup/hdf5#3493]
**Describe the bug**

`H5Acreate2()` has args defined as

hid_t H5Acreate2 | ( | hid_t | loc_id,
-- | -- | -- | --
  |   | const char * | attr_name,
  |   | hid_t | type_id,
  |   | hid_t | space_id,
  |   | hid_t | acpl_id,
  |   | hid_t | aapl_id
  | )

The docs say that `acpl` is currently unused. I think there are places in the code that say this. However, there is no table of properites for attribute access in the docs. Only for attribute creation which suggests to me that `acpl` is used and `aapl` is currently not used. I am not able to find any instance of `H5Acreate2()` in tests that pass anything other than `H5P_DEFAULT` for both `acpl` and `aapl`.

I believe the docs and code are in error in saying `acpl` is unused. I think the unused arg is `aapl`.

I started to try to submit a PR and then got lost in finding where the statement `The acpl parameter is currently not used; specify H5P_DEFAULT` actually lives in the sources.

**Comment by jhendersonHDF** [comment]
Thanks for reporting @markcmiller86. Indeed, `aapl_id` is the parameter that is not used; I think this was a copy-paste issue from the docs for H5Acreate1. For future reference, [here](https://github.com/HDFGroup/hdf5/blob/develop/doxygen/aliases#L141) is a link to where the command for generating the `The acpl parameter is currently not used; specify H5P_DEFAULT` line comes from. the `\plist_unused{}` command just substitutes whatever it is passed into there.
