### ISSUE TITLE
t_mpi test fails with OpenMPI 4.1.5, but passes with MPICH 4.1.2

### ISSUE THREAD

**Issue by wreckdump** [HDFGroup/hdf5#3504]
**Describe the bug**
t_mpi test fails with OpenMPI 4.1.5, but passes with MPICH 4.1.2 (both compiled with AMD AOCC 4.1.0). And this affects the `netcdf` parallel related functions. For example, when `nc_open_par()` function from `netcdf` is called, it hangs without any activity.

**Expected behavior**
I expect the hdf5 parallel related tests and functions to work properly.

**Platform (please complete the following information)**
 - HDF5 version : 1.14.2
 - OS and version : Arch Linux 6.4.12-arch1-1
 - Compiler and version : AMD AOCC 4.1.0
 - Build system (e.g. CMake, Autotools) and version : GNU Make 4.4.1, Autoconf 2.71
 - Any configure options you specified : `--enable-parallel` during configuration stage
 - MPI library and version (parallel HDF5) : OpenMPI 4.1.5 (problematic), MPICH 4.1.2 (functional)

**Comment by hyoklee** [comment]
Hi, @wreckdump !

I can't duplicate the error with our develop branch on GitHub Ubuntu-latest Action:

https://github.com/hyoklee/actions/actions/runs/6472049023/job/17571862095

Would you please check if the same error still occurs with develop branch?

For reference, you can try something similar to my GitHub Action workflow:

https://github.com/hyoklee/actions/blob/6d207a453790cde9163787ed6aa593d631319575/.github/workflows/aocc4.yml

**Comment by derobins** [comment]
@hyoklee says it passes tests for him
