### ISSUE TITLE
`H5Pset_external` limited to offsets <= 2GB on Windows

### ISSUE THREAD

**Issue by phil-opp** [HDFGroup/hdf5#3506]
**Describe the bug**

The `H5Pset_external` function takes an `offset` argument of type `off_t`, which is a 32-bit signed integer on Windows. This makes it impossible to link to offsets > 2GB.

Interestingly, the only limitation seems to be the API definition. The implementation already uses a `HDoff_t` type for offsets, which is also 64-bit on Windows.

**Expected behavior**

It should be possible to link to arbitrary offsets on Windows, like it is on Linux. The easiest solution for this would be to accept a 64-bit offset in the API on Windows.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash)
   - df8f7a9029f443e6df0e2644a040a87ef4905607

**Comment by derobins** [comment]
This has been fixed in develop and will appear in HDF5 2.0.0, scheduled for March 2025.
