### ISSUE TITLE
HDF5 1.14.2 distributed with HDFView 3.3.1 without GZIP support

### ISSUE THREAD

**Issue by dsewtz** [HDFGroup/hdf5#3510]
**Describe the bug**
When trying to open an HDF5 dataset with Comperssion GZIP within an HDF5 Group,
HDFView 3.3.1 with HDF5 1.14.2 prduces this error:
An error occured while loading data for the table:
failed to read scalar dataset: Can't open directory for file

**Expected behavior**
HDFView 3.3.0 with HDF5 1.14.0 on Win64 can open HDF5 Dataset within HDF5 Group with Compression GZIP
Since there was no major version bump, I expected that this would still work with 3.3.1/1.14.2

**Platform (please complete the following information)**
 - HDF5 version 1.14.2 (included with binary distribution of HDFView 3.3.1 for win64 in both installer and zip-package)
 - Windows 10 64bit 22H2

**Present in the following prebuilt binary distributions**
from https://www.hdfgroup.org/downloads/hdf5/
- 7b17ab1bca264509a4cd8626097272d60fee94f6de1e62712a82759b2e001e42  HDFViewApp-3.3.1-win10_64-vs17.zip
- bf3ae6f9987156447e77ad5b04c843bf58dc97036f178912b20e5197a8062fec  HDFView-3.3.1-win10_64-vs17.zip
- 34486a061f84f693190b4edc5b92b860b0f3a8ea6e311b140d8bffe2a96137ed  hdf5-1.14.2-Std-win10_64-vs16.zip
- cbf4cc1e15df58340380d10da3bbaa1ac971280eb0ef35072bb927031daa101d  hdf5-1.14.2-Std-win10_64-vs17.zip

**Additional context**
This file can be used to verify:
[compressed_h5.zip](https://github.com/HDFGroup/hdf5/files/12536000/compressed_h5.zip)

**Comment by byrnHDF** [comment]
This is a problem with the HDF5 1.14.2 release on windows. Need to verify if issue is in the releases for other platforms.

**Comment by byrnHDF** [comment]
Regenerated the binaries with compression added.

**Comment by byrnHDF** [comment]
1.14.2 binaries have been fixed. HDFView windows and mac binaries are fixed. There are issues with the linux build machines and this issue will remain until those binaries are produced.

**Comment by byrnHDF** [comment]
All binaries have been updated.
