### ISSUE TITLE
Reference Manual needs to provide a direct access to API Compatibility Macros

### ISSUE THREAD

**Issue by bmribler** [HDFGroup/hdf5#3520]
Currently, accessing API compatibility macros such as H5Literate is not at all obvious.
Consider adding a doxygen table or something that lists the APIs and point to the "API Compatibility Macros " link.

**Comment by byrnHDF** [comment]
Turns out that there already is a link at the top of the H5L module called "Link Traversal"

**Comment by byrnHDF** [comment]
Added a small note that indicates what functions are located in a subgroup of the H5L module. See #3530.

**Comment by byrnHDF** [comment]
#3530 addressed this issue
