### ISSUE TITLE
Parallel HDF5 gets stuck on an open file call with two MPI processes

### ISSUE THREAD

**Issue by nischild** [HDFGroup/hdf5#3522]
Using Parallel HDF5 I try to open an hdf5 file but the open file call does not returns and the program gets stuck.

Minimal Example:
```C++
int main(int argc, char* argv[]) {
  MPI_Init(&argc, &argv)
  hid_t propertyListOpen = H5Pcreate(H5P_FILE_ACCESS);
  H5Pset_fapl_mpio(propertyListOpen, MPI_COMM_WORLD,
                              MPI_INFO_NULL);
  std::cout << "Open file test"<< std::endl;
  auto fileID =
      H5Fopen("myH5File.h5", 
              H5F_ACC_RDWR, propertyListOpen);
  std::cout << "File opened test"<< std::endl;
  H5Pclose(propertyListOpen);
  H5Fclose(fileID);
  MPI_Finalize();
```

Output:
```sh
$> /usr/lib64/mpi/gcc/openmpi4/bin/mpirun -n 2 ./a.out
MPI_Initialized
MPI_Initialized
Open file test
Open file test
```
The `H5Fopen` call never seems to return. This only happens for 2 MPI processes. For a different number of processes I could not yet recover the same problem. Using `h5dump myH5File.h5` I can output the content of the file to terminal.

**Platform (please complete the following information)**
 -  Version 1.12.2 HDF5
 - OpenSuse Tumbleweed
 - g++ (SUSE Linux) 13.2.1 20230803 [revision cc279d6c64562f05019e1d12d0d825f9391b5553]
 - CMake 
 - Open MPI 4.1.5.0.42b829b3b319

**Additional context**
The files that should be opened are downloaded from a gitlab repository but have the required access rights (u+rw).

**Comment by wreckdump** [comment]
I had a similar problem. Regardless of the number of the process, my parallel related function call would hang.

As it turns out the problem was from OpenMPI version 4.1.5. I can not pin point what or how, but I solved the issue by using MPICH instead of OpenMPI. If you don't want to use MPICH try using older version of OpenMPI.

**Comment by wreckdump** [comment]
You should also try testing the HDF5 parallel build. In my case, t_mpi test, which is one of the parallel function tests, was failing with OpenMPI 4.1.5.

**Comment by nischild** [comment]
> You should also try testing the HDF5 parallel build. In my case, t_mpi test, which is one of the parallel function tests, was failing with OpenMPI 4.1.5.

The HDF5 Version that I used above was the parallel HDF5 package of OpenSUSE Tumbleweed based on MPI.


I can confirm that if I replace OpenMPI with MVAPICH the problem disappears. So it probably is an OpenMPI bug not a HDF5 bug. But I can not investigate this further since I can not debug the internals of the HDF5-Functions that I call above.
