### ISSUE TITLE
Export of the `NDEBUG` flag in `HDF5_DEFINITIONS` CMake variable

### ISSUE THREAD

**Issue by Algiane** [HDFGroup/hdf5#3526]
**Describe the bug**
I am contributing to a software with lot of dependencies that uses CMake and as building system. Trying to build this software in CMake `Debug` mode I realized that CMake is always adding the `-DNDEBUG` definition to the compiler flags.

After investigation, this `-DNDEBUG` flag is propagated from the definitions exported by hdf5 in its `HDF5_DEFINITIONS` CMake variable toward one of the software dependency, then toward the software (see [here](https://github.com/GEOS-DEV/GEOS/issues/2631#issuecomment-1711673820)).

**Expected behavior**

  - Using CMake, I would like to be able to build my software without adding the `-DNDEBUG` compiler flag while linking against the hdf5 library built in `Release` mode (so with `-DNDEBUG` compiler flag).

  - As it is not possible for the user to discriminate the definitions that are necessary to build against a library from the definitions that are not (typically the `NDEBUG`one), I think that the HDF5_DEFINITIONS CMake variable should only contain the definitions used by hdf5, without which a project calling the hdf5 libraries would not be able to call the API functions without errors. So it should not contain the `NDEBUG` definition.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): hdf5-1.12.1
 - OS and version: Ubuntu-2022
 - Compiler and version: g++ 11.4.0
 - Build system (e.g. CMake, Autotools) and version: CMake 3.22.1
 - Any configure options you specified : 
     - hdf5 is built in Release mode (`-O3 -DNDEBUG`)
     -  The software I use is built in Debug mode
 - MPI library and version (parallel HDF5) : no object

**Additional context**
The software I am contributing uses and has dependencies that use a CMake overlay, [`blt`](https://github.com/LLNL/blt), to manage its CMake process. I don't have the hand on this overlay and as the generic macros that it defines are used to manage various library dependencies, it is not possible to choose to not import the defs exported by one library (for the other libraries it may be necessary to recover these definitions).

Thank you by advance for your help,

**Comment by byrnHDF** [comment]
So are you trying to force the HDF5 release libraries to use debug or is the HDF5 definition forcing you to use NDEBUG on your software?

**Comment by byrnHDF** [comment]
Also I'm having trouble locating the "HDF5_DEFINITIONS" in the published binary files.

**Comment by byrnHDF** [comment]
Since Oct 2019 we no longer force NDEBUG in the defines and defer to CMake itself (Unless specifically requested with a build option)

**Comment by Algiane** [comment]
Hi,

Thanks for your prompt replies.

To precise my initial issue: `HDF5_DEFINITIONS` is forcing me to use `NDEBUG` on my software. I use the `configure` script to build `hdf5`.
I have seen that the the `NDEBUG` flag is exported in the `lib/libhdf5.settings` (`C_FLAGS` variable) and `bin/hd5cc` (`H5BLD_CFLAGS` variable) files during the hdf5 installation.

The CMake doc states that the `FindHDF5`module fills the `HDF5_DEFINITIONS` variable with the *Required compiler definitions for HDF5* (`https://cmake.org/cmake/help/latest/module/FindHDF5.html`) so I suspect that CMake uses the `C_FLAGS` variable of the `lib/libhdf5.settings` file. I will try to confirm that (there is a possibility that CMake leaves the HDF5_DEFINITIONS variable empty and that the `blt` layer exports a variable with the same name).

I have seen that the `libhdf5.settings`  file also contains the `H5_C_FLAGS` variable with compilation flags. These flags do not end up in the `HDF5_DEFINITIONS` so maybe the `NDEBUG` flag should be in the `H5_C_FLAGS` and not in the `C_FLAGS` of the setting file?

Best

**Comment by byrnHDF** [comment]
Oh, you are building hdf5 with autotools! That is why you do not see them in the CMake built binaries. And CMakes FindHDF5 module will work differently.  With a CMake built HDF5 there will be config files that CMake can use without intepretation. FindHDF5 module has to inspect and interpret a HDF5 built with autotools.

**Comment by tbeltzun** [comment]
@Algiane, maybe we should transition to `CMake` (we have an opened issue in the TPLs: https://github.com/GEOS-DEV/thirdPartyLibs/issues/211).

**Comment by Algiane** [comment]
I have just tested the cmake build of hdf5 and indeed, it does allow to get rid of the `NDEBUG` flag.

@tbeltzun: I will propose a PR to switch to the CMake build of hdf5 in Geos TPLs.
@byrnHDF: Thanks a lot for your help, for me this issue can be closed.

Best
