### ISSUE TITLE
H5Dread fails in multithread application

### ISSUE THREAD

**Issue by DominicWindisch** [HDFGroup/hdf5#3542]
**Describe the bug**
When reading data from a file in the multithreaded application, the program fails after a short time with the errors:
```
HDF5-DIAG: Error detected in HDF5 (1.14.2) thread 0:
  #000: C:\...\hdf5-1.14.2\src\H5D.c line 1061 in H5Dread(): can't synchronously read data
    major: Dataset
    minor: Read failed
  #001: C:\...\hdf5-1.14.2\src\H5D.c line 1008 in H5D__read_api_common(): can't read data
    major: Dataset
    minor: Read failed
  #002: C:\...\hdf5-1.14.2\src\H5VLcallback.c line 2097 in H5VL_dataset_read_direct(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #003: C:\..\hdf5-1.14.2\src\H5VLint.c line 2357 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value
```

This is the block of code reading the data: 

Initialization: 
```
ds_data_ = H5Dopen(HDF5File_, datasetName_.c_str(), H5P_DEFAULT);
if(ds_data_ == H5I_INVALID_HID) { return false; }
sp_data_ = H5Dget_space(ds_data_);
if(sp_data_ == H5I_INVALID_HID) { return false; }
// get dimensions
auto ndims_data = H5Sget_simple_extent_ndims(sp_data_);
if(ndims_data != 3) { return false; }
hsize_t dims_data[3], maxdims_data[3];
if(ndims_data != H5Sget_simple_extent_dims(sp_data_, dims_data, maxdims_data)) {	return false; }

imageHeight_ = dims_data[0];
imageWidth_ = dims_data[1];
imageCount_ = dims_data[2];

hsize_t dims_msp[3];
dims_msp[0] = imageHeight_;
dims_msp[1] = imageWidth_;
dims_msp[2] = 1; // set such that the memory space will always hold one frame
msp_data_ = H5Screate_simple(ndims_data, dims_msp, NULL);
if(msp_data_ == H5I_INVALID_HID) { return false; }

return true;
```
Called in a loop with incrementing `offset_data_[2]`:
```
// load main dataset
if(H5Sselect_hyperslab(sp_data_, H5S_SELECT_SET, offset_data_, NULL, count_data_, NULL) < 0)
{
	throw std::runtime_error("risa::cuda::HDF5Loader: Error setting up data space for dataset.");
}
if(H5Sselect_hyperslab(msp_data_, H5S_SELECT_SET, offset_msp_, NULL, count_data_, NULL) < 0)
{
	throw std::runtime_error("risa::cuda::HDF5Loader: Error setting up memory space for dataset.");
}
if(H5Dread(ds_data_, type_data_, msp_data_, sp_data_, H5P_DEFAULT, dataBuffer_) < 0)
{
	throw std::runtime_error("risa::cuda::HDF5Loader: Error when reading data from dataset.");
}
/* do stuff with the data */
```

It happens every time, but always after a different time.

**Expected behavior**
Data should be read from the hdf5 file. 

**Platform (please complete the following information)**
 - HDF5 version: 1.14.2
 - Windows 10
 - nvcc 11.8.89
 - cmake 3.26.4
 - Build options:  
   -DHDF5_ENABLE_THREADSAFE:BOOL=ON", 
   -DHDF5_ENABLE_PARALLEL:BOOL=OFF"
   -DHDF5_BUILD_CPP_LIB:BOOL=OFF",  
   -DHDF5_BUILD_FORTRAN:BOOL=OFF",  
   -DHDF5_BUILD_HL_LIB:BOOL=OFF"
 - OpenMP 2.0

**Additional context**
The exact same code runs fine on Ubuntu 22.04 with HDF5 1.15.1 (same build options).

**Comment by DominicWindisch** [comment]
Some additional info: The code I've shown was part of a DLL with statically linked HDF5 libraries. After switching to dynamic linking, the code works as expected.

**Comment by derobins** [comment]
Thread-safety and static don't work on Windows. We have to do some per-thread cleanup and teardown in DllMain, which we obviously can't do in a non-dll static library.

**Comment by derobins** [comment]
We will fix the build system so that configuration fails.

**Comment by nowgain-nowpain** [comment]
> Thread-safety and static don't work on Windows. We have to do some per-thread cleanup and teardown in DllMain, which we obviously can't do in a non-dll static library.

Does this mean I cannot use hdf5 in multiple threaded application even each thread is reading/writing a different file? I have a small app which uses a taskflow framework to create tasks and run the tasks concurrently. In each task, it either creates a hdf file or reads from a  hdf5 file. However, when I ran on Windows, it keeps throwing at different places, the one I observed very frequently failed is from H5FL_fac_malloc(). when the task finishes and try to destroy the hdf5 objects. 

Thanks.

**Comment by hofmannu** [comment]
I think that is still the case. I get the same error when trying to do this. despite that flag, the library is really not thread safe even when trying to do super simple things such as reading from different files with different threads it produces a complete mess, is impossible to properly debug and has no clear documentation on this. All one can rely on is either a) hardly readable source code or b) some forum entries and mailing lists...

**Comment by qkoziol** [comment]
While I understand your frustration, this isn't true.  The HDF5 library can be built to be completely threadsafe.  On Windows it requires being built as a DLL, due to the limitations of multithreading on Windows.  As Dana said, the thread-local variables and other information needed to actually be threadsafe are only possible with calls that rely on DLL behavior.  On Linux and MacOS, threadsafe builds can be either static or dynamic libraries.

**Comment by hofmannu** [comment]
maybe it would make sense to block compiling hdf then if windows and static and threadsafe are all true? at the moment it seems to compile for that unsupported combination?
