### ISSUE TITLE
Doxyfile  doxygen compile time options warning

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#3558]
These options are only available if doxygen itself was built with the feature. hdf5 uses the defaults for these and they should just be removed.

[3115/3879] cd /Users/runner/work/hdf5/hdf5/hdfsrc/hl && /usr/local/bin/doxygen /Users/runner/work/hdf5/hdf5/build/ci-StdShar-Clang/Doxyfile
warning: Tag 'CLANG_ASSISTED_PARSING' at line 925 of file '/Users/runner/work/hdf5/hdf5/build/ci-StdShar-Clang/Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'CLANG_OPTIONS' at line 933 of file '/Users/runner/work/hdf5/hdf5/build/ci-StdShar-Clang/Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag 'CLANG_DATABASE_PATH' at line 943 of file '/Users/runner/work/hdf5/hdf5/build/ci-StdShar-Clang/Doxyfile' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.

**Comment by derobins** [comment]
These have all been removed in develop and hdf5_1_14
