### ISSUE TITLE
hdf5 error when cross compiling for arm64-windows

### ISSUE THREAD

**Issue by jimwang118** [HDFGroup/hdf5#3585]
**Describe the bug**
I am the maintainer of vcpkg and when I use vcpkg to install hdf5 on arm64-windows triplet I get an error.
```
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_IOEO_EXITCODE (advanced)
For details see F:/upvcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LDOUBLE_TO_LONG_SPECIAL_RUN (advanced)
   H5_LDOUBLE_TO_LONG_SPECIAL_RUN__TRYRUN_OUTPUT (advanced)
For details see F:/upvcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LONG_TO_LDOUBLE_SPECIAL_RUN (advanced)
   H5_LONG_TO_LDOUBLE_SPECIAL_RUN__TRYRUN_OUTPUT (advanced)
For details see F:/upvcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LDOUBLE_TO_LLONG_ACCURATE_RUN (advanced)
   H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT (advanced)
For details see F:/upvcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LLONG_TO_LDOUBLE_CORRECT_RUN (advanced)
   H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT (advanced)
For details see F:/upvcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
```

**Expected behavior**
Installation is normal

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash) 1.14.0
 - OS and version windows 10
 - Compiler and version  msvc
 - Build system (e.g. CMake, Autotools) and version cmake
 - Any configure options you specified
 - MPI library and version (parallel HDF5)

**Additional context**
You can reproduce this using the following steps:
1. git clone vcpkg
2. .\bootstrap-vcpkg.bat
3. ./vcpkg install hdf5:arm64-windows

**Comment by dg0yt** [comment]
@jimwang118 The vcpkg contributors know about the hdf5 cross-build issues... Did you try to update hdf5 first? There was #1203 and https://github.com/HDFGroup/hdf5/pull/3104. 1.14.0 is before this.

**Comment by jimwang118** [comment]
> @jimwang118 The vcpkg contributors know about the hdf5 cross-build issues... Did you try to update hdf5 first? There was #1203 and #3104. 1.14.0 is before this.

I tried updating locally, but still got the same cross-compilation error.

**Comment by dg0yt** [comment]
So these changes are not in 1.14 branches or releases. 
I did an attempt to backport them, but there are still other `try_run` tests.

BTW you should change the title to "for arm64-windows". I assume you are "under x64-windows", given the cross-compiling mode.

**Comment by derobins** [comment]
Can you see if https://github.com/HDFGroup/hdf5/pull/3683 fixes the problem for you?

**Comment by jimwang118** [comment]
> Can you see if #3683 fixes the problem for you?

I tested it locally using the PR you submitted, and now I get the following error.

```
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_IOEO_EXITCODE (advanced)
For details see F:/vcpkg/buildtrees/hdf5/arm64-windows-dbg/TryRunResults.cmake
```
[TryRunResults.txt](https://github.com/HDFGroup/hdf5/files/12913859/TryRunResults.txt)
[config-arm64-windows-dbg-err.log](https://github.com/HDFGroup/hdf5/files/12913851/config-arm64-windows-dbg-err.log)

**Comment by derobins** [comment]
I think that right now you'll have to specify cache values for other things that we test using try_run. I'll work on replacing those, but it might be 1.14.4 before that work is done. We'll see how the week goes.

**Comment by emmenlau** [comment]
Thanks a lot @derobins for looking into this! I have tested hdf5 1.14.3 right now and the issue persists. It would be great to know what values would be required to get a build for Android arm64. Probably people ave done this before, but I could not find the (few) cmake settings anywhere on the web that would be required to get hdf5 configured :(
