### ISSUE TITLE
Add Emscripten builds to releases

### ISSUE THREAD

**Issue by bmaranville** [HDFGroup/hdf5#3615]
**Is your feature request related to a problem? Please describe.**
I would like to have Emscripten added to the list of architectures for which the library is pre-built and distributed with releases, such as osx12 and ubuntu-2204

**Describe the solution you'd like**
If the hdf5 library was built with emscripten at every release and the binary package attached as a release artifact

**Describe alternatives you've considered**
I am currently doing this myself for a selected set of HDF5 versions here: https://github.com/usnistgov/libhdf5-wasm - I would like it if this architecture was officially supported and I didn't build it myself. (I'm not particularly good at CMake)

**Additional context**
I recently changed my build process to use the provided CPack configuration from HDF5, and it seems to work well.  I believe this could be built almost as easily as the packages for the other architectures.

**Comment by derobins** [comment]
This would be interesting, but requires more discussion. Moving to the 'discussion' section.
