### ISSUE TITLE
Deprecated API functions can segfault with non-Native connectors

### ISSUE THREAD

**Issue by mattjala** [HDFGroup/hdf5#3620]
Old API functions  assume that the native VOL is being used, and cast the object data received from `H5VL_object_data` to a native type like `H5X_t` in a way that often causes invalid memory accesses later.

A specific example from [this issue encountered with the REST VOL](https://github.com/HDFGroup/vol-rest/pull/77#issuecomment-1741500166): when calling `H5Oget_info_by_name1`, a return of type `RV_object_t*` is later cast by `H5VL_native_get_file_struct` to `H5F_t*`, which causes a segfault on later attempts to access the shared pointer.

Since support for 1.10 is already dropped, and support for 1.12 is about to be dropped, this only needs to be dealt with in 1.14. There are a few possible solutions:
- Leave the deprecated functions as they are, because they shouldn't be used in 1.14+ anyway.
- Add checks that the native VOL is being used to any deprecated functions that work with objects.
- Remove the deprecated functions entirely.

**Comment by fortnern** [comment]
`H5Oget_object_by_info1` doesn't exist, and `H5Oget_info1` doesn't have this problem as far as I can tell. What is an example of a function that shows this problem?

**Comment by fortnern** [comment]
I think the issue is the call to `H5VL_native_token_to_addr()` in `H5O__get_info_old()`. We should fix this so it works properly with non-native VOLs.
