### ISSUE TITLE
Merge changes from PR #340 "Fixed various clang -Wformat-security warnings" to support branches

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#363]
Merge #340 needed to hdf5_1_12, hdf5_1_10, and hdf5_1_8 after passing all test configurations in daily test cycle

**Comment by byrnHDF** [comment]
merge to 1.12 in #421

**Comment by byrnHDF** [comment]
merge to 1.10 in #424

**Comment by byrnHDF** [comment]
merge to 1.8 in #432

**Comment by byrnHDF** [comment]
Completed
