### ISSUE TITLE
Merge changes from PR #361 "Fixed many -Wreserved-id-macro warnings by fixing header guard spelling" to support branches

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#368]
Merge #361 needed to hdf5_1_12, hdf5_1_10, and hdf5_1_8 after passing all test configurations in daily test cycle

**Comment by lrknox** [comment]
Changes merged to hdf5_1_12 in PR #412

**Comment by byrnHDF** [comment]
Changes merged to 1.10 in PR #419 
Changes merged to 1.8 in PR #418

**Comment by byrnHDF** [comment]
Completed - DT passed.
