### ISSUE TITLE
Need to merge "Fix for HDFFV-11109 - Copy MPI comm and info object into output FAPL from H5F_get_access_plist #342" to support branches

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#373]
@jhendersonHDF - to which of hdf5_1_12, hdf5_1_10, hdf5_1_8 should this be merged?

**Comment by jhendersonHDF** [comment]
@lrknox I will need to do some quick testing to see which of the branches has the same issue. I imagine 1.12 will definitely need it, but I need to see if the problem exists in 1.10 as well. I don't think 1.8 should need it. I will create the PRs after testing.
