### ISSUE TITLE
bin/trace does not work properly with /*out*/ comments

### ISSUE THREAD

**Issue by fortnern** [HDFGroup/hdf5#3733]
Some or all API functions that have arguments with `\*out*\` comments, commonly used to indicate that an argument functions as an output, are given incorrect trace macros. Most or all of these arguments are mapped to `x` in the trace macro, no matter the actual type of the argument. Since `x` is only supposed to map to `void` (not `void *`) or `va_arg`, this is clearly a bug.

**Comment by derobins** [comment]
Example:

H5Pget_actual_selection_io_mode(hid_t plist_id, uint32_t *actual_selection_io_mode /*out*/) (from H5Pdxpl.c)

**Comment by derobins** [comment]
The bin/trace script is pretty clear about doing this, so it's not an accident.

FWIW, this hack to bin/trace gives the desired output as discussed in #2974 

```
diff --git a/bin/trace b/bin/trace
index c620b80536..d2c460bf57 100755
--- a/bin/trace
+++ b/bin/trace
@@ -308,7 +308,9 @@ sub rewrite_func ($$$$$) {
     # Split arguments.  First convert `/*in,out*/' to get rid of the
     # comma and remove lines beginning with a '#', then split the arguments
     # on commas.
-    $args =~ s/(\/\*\s*in),\s*(out\s*\*\/)/$1_$2/g;     # Get rid of comma in 'in,out'
+    $args =~ s/\/\*\s*in\s*\*\///g;     # Get rid of /*in*/
+    $args =~ s/\/\*\s*out\s*\*\///g;    # Get rid of /*out*/
+    $args =~ s/\/\*\s*in,\s*out\s*\*\///g; # Get rid of /*in,out*/
     $args =~ s/H5FL_TRACK_PARAMS//g; # Remove free list macro
     $args =~ s/\n#.*?\n/\n/g;        # Remove lines beginning with '#'
     my @args = split /,[\s\n]*/, $args;
```


`H5TRACE2("e", "ix", plist_id, actual_selection_io_mode);`

becomes

`H5TRACE2("e", "i*Iu", plist_id, actual_selection_io_mode);`

Aside from the immediate regex hack, we'd have to clean up more stuff in that script.

**Comment by qkoziol** [comment]
I'll work on it after my current project

**Comment by derobins** [comment]
BTW, I'm planning on taking the Perl scripts out of autogen.sh. Instead, I'll have a quick GitHub action that will run the scripts and fail if `git diff` shows changes. We should be doing this for the HL library parser, too. We can discuss at one of the Thursday meetings.

**Comment by qkoziol** [comment]
I agree that they shouldn't be in autogen.sh, but I don't think the only place they should be triggered is with a github action (although I like the idea of having one set up the way you describe).

Maybe a "pre-commit" script that runs the trace script and the code formatter?

**Comment by derobins** [comment]
The TRACE macros will be removed in 1.14.4
