### ISSUE TITLE
Can't compile with `HDF5_EXTERNALLY_CONFIGURED=ON` (cmake)

### ISSUE THREAD

**Issue by Krzmbrzl** [HDFGroup/hdf5#3780]
**Describe the bug**
Compilation fails when using `HDF5_EXTERNALLY_CONFIGURED=ON` due to the `test` subdirectory being correctly excluded, but `utils/test` being incorrectly included. `swmr_check_compat_vfd.c` includes `h5test.h` and thus depends on the `test` directory having been added.

**Additional context**
A workaround is to explicitly set `BUILD_TESTING` to `OFF`. However, given that the mechanism with `HDF5_EXTERNALLY_CONFIGURED` exists, it should be taken into account at this point as well.

**Comment by Krzmbrzl** [comment]
Actually, the issue persists with other parts of the code as well. It seems that pretty much every subdirectory has its own `test` directory, which is not "guarded" with `HDF5_EXTERNALLY_CONFIGURED` :eyes:

**Comment by byrnHDF** [comment]
> Actually, the issue persists with other parts of the code as well. It seems that pretty much every subdirectory has its own `test` directory, which is not "guarded" with `HDF5_EXTERNALLY_CONFIGURED` 👀

I agree, other add_subdirectory test locations should include this check.
