### ISSUE TITLE
Investigate handling exceptions gracefully in the HDF5 library

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#3784]
H5detect was incorporated into the HDF5 library in 1.14.3. Since h5detect purposely causes exceptions,  this may cause issues with applications using HDF5 with compilers which halt the program when it encounters those exceptions. One such compiler is the NAG fortran compiler.

We should look into handling those exceptions more gracefully to avoid a halting trigger.

**Comment by derobins** [comment]
Fixed before 1.14.3
