### ISSUE TITLE
H5VLnative lacks doxygen documentation

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#3789]
Notably, 

H5VLnative_addr_to_token (hid_t loc_id, haddr_t addr, H5O_token_t *token)
H5VLnative_token_to_addr (hid_t loc_id, H5O_token_t token, haddr_t *addr)

don't have any documentation associate with them.

**Comment by derobins** [comment]
These two functions have been Doxygen-ified. We still need to the a lot of developer-header-level work, though.
