### ISSUE TITLE
Merge changes from "Patches from vtk #358" to support branches

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#384]
Merge #358 needed to hdf5_1_12, hdf5_1_10, and hdf5_1_8 after passing all test configurations in daily test cycle.
(commit c29e1b9)

**Comment by lrknox** [comment]
Changes merged to hdf5_1_12 in PR #412

**Comment by byrnHDF** [comment]
Changes merged to 1.10 in PR #419 
Changes merged to 1.8 in PR #418

**Comment by byrnHDF** [comment]
Completed - DT passed.
