### ISSUE TITLE
zlib.h missing in binary MSI installer for Windows

### ISSUE THREAD

**Issue by tbeu** [HDFGroup/hdf5#3860]
**Describe the bug**
The zlib.h is not (no longer) distributed with the MSI installers for Windows. I see that zconf.h is distributed, which somehow indicates that zlib.h should also be distributed.

**Expected behavior**
zlib.h should be distributed (as was the case for 1.8.12 installer).

**Platform (please complete the following information)**
 - HDF5 version 1.12.1 - 1.14.3
 - OS and version Win 10
 - Compiler and version MSVC
 - Build system (e.g. CMake, Autotools) and version CMake 3.27

**Comment by byrnHDF** [comment]
The compression lib APIs are not exposed by HDF5. The zconf.h file should not be distributed.

**Comment by tbeu** [comment]
Thanks for the reply. In that case also libaec.h and szlib.h should not be distributed though it might break existing user workflows (as it did with missing zlib.h).

**Comment by derobins** [comment]
Fixed
