### ISSUE TITLE
MSYS2 GitHub Action fails for clang64 environment

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#3876]
**Describe the bug**

MSYS2 clang64 environment generates the following "undeclared function" error for `alarm`, `asprintf`, and `vasprintf`

Here's `vasprintf` example output:
```
D:/a/actions/actions/hdf5/src/H5Eint.c:654:9: error: call to undeclared function 'vasprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  654 |     if (HDvasprintf(&tmp, fmt, ap) < 0)
      |         ^
D:/a/actions/actions/hdf5/src/H5private.h:868:34: note: expanded from macro 'HDvasprintf'
  868 | #define HDvasprintf(RET, FMT, A) vasprintf(RET, FMT, A)
      |                                  ^
D:/a/actions/actions/hdf5/src/H5Eint.c:654:9: note: did you mean 'vsprintf'?
D:/a/actions/actions/hdf5/src/H5private.h:868:34: note: expanded from macro 'HDvasprintf'

  868 | #define HDvasprintf(RET, FMT, A) vasprintf(RET, FMT, A)

      |                                  ^

D:/a/_temp/msys64/clang64/include/stdio.h:522:15: note: 'vsprintf' declared here

  522 |   int __cdecl vsprintf(char * __restrict__ _Dest,const char * __restrict__ _Format,va_list _Args) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;

      |               ^

1 error generated.
```

**Expected behavior**
Build without any extra option in cmake.

**Platform (please complete the following information)**
 - HDF5 version: develop
 - OS and version: windows-latest
 - Compiler and version: clang17
 - Build system (e.g. CMake, Autotools) and version: CMake + Ninja
 - Any configure options you specified: -G Ninja
 - MPI library and version (parallel HDF5): n/a

**Additional context**

Other 3 environments are fine.
See #3861.

**Comment by derobins** [comment]
The Autotools and CMake can both build w/ MinGW + MSYS2 now, for mingw32/64, ucrt64, and clang64. The Autotools build passes tests, CMake does not. We will investigate the CMake failures for the HDF5 2.0.0 release and create separate issues for broken tests.
