### ISSUE TITLE
Group creation properties are not propagated to the intermediate groups

### ISSUE THREAD

**Issue by radistmorse** [HDFGroup/hdf5#3945]
**Describe the bug**
When creating the group with link property set to create the intermediate groups, one would assume that the group creation properties would be propagated to all the created groups, but it is not so. This is the minimal reproduction example.

```c
#include <assert.h>
#include "hdf5.h"

int main(void)
{
        hid_t linkProps, groupProps, file, group;
        unsigned crOrder;
 
        linkProps = H5Pcreate(H5P_LINK_CREATE);
        groupProps = H5Pcreate(H5P_GROUP_CREATE);
        
        H5Pset_create_intermediate_group(linkProps, 1);
        H5Pset_attr_creation_order(groupProps, H5P_CRT_ORDER_TRACKED);
        
        file = H5Fcreate("test.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
        
        H5Gcreate2(file, "test/test", linkProps, groupProps, H5P_DEFAULT);
        
        group = H5Gopen2(file, "test", H5P_DEFAULT);
        groupProps = H5Gget_create_plist(group);
        H5Pget_attr_creation_order(groupProps, &crOrder); 
        
        /* this assert will fail */
        assert(crOrder == H5P_CRT_ORDER_TRACKED);

        return 0;
}
```

**Expected behavior**
The intermadiate groups being created with the same creation properties.

**Comment by derobins** [comment]
We should fix this, though it might require some property list changes for when we create a dataset.

**Comment by radistmorse** [comment]
Yes, I thought to include the dataset case as well, but since dataset doesn't have group creation properties at all, this would be more of a feature request (also, breaks API). For group creation this seems more obvious.  If a single function call creates several groups, it's unintuitive to create these groups with different properties.
