### ISSUE TITLE
mpi_f08 error freeing mpi_info type returned by h5pget_fapl_mpi_f

### ISSUE THREAD

**Issue by michalakes** [HDFGroup/hdf5#3951]
**Describe the bug**
The mpi_info descriptor returned by h5pget_fapl_mpi_f (https://docs.hdfgroup.org/hdf5/develop/group___f_h5_p.html#ga7e27d00061a651c885c6b69a86892303) is an older MPI-1 style integer descriptor that is not being freed correctly by the MPI-2 MPI_INFO_FREE routine (we have `use mpi_f08` in our Fortran code). 

The Fortran 2008 interface to MPI_INFO_FREE specifies type(MPI_INFO)  (https://www.open-mpi.org/doc/v3.0/man3/MPI_Info_free.3.php#sect8) rather than an integer argument so that passing the integer descriptor returned by h5pget_fapl_mpi_f generates a compile-time error:

> `There is no matching specific subroutine for this generic subroutine call.   [MPI_INFO_FREE]`

If we declare a variable mpiinfo of type(MPI_INFO), call MPI_INFO_CREATE(mpiinfo), then assign the value of the descriptor returned by h5pget_fapl_mpi_f to mpiinfo%mpi_val, we can then pass mpiinfo to MPI_INFO_FREE and the code compiles. However, the MPI_INFO_FREE command returns an non-zero error code indicating that MPI_INFO_FREE failed.

We note that the page for H5Pget_fapl_mpio (https://docs.hdfgroup.org/hdf5/develop/group___f_a_p_l.html#ga5d9e4b9f27791ccf19484a898f3fd6fa) states explicitly that it is our responsibility to free the duplicate MPI communicator and mpi_info objects returned by H5Pget_fapl_mpio:

> "Since the MPI communicator and Info object are duplicates of the stored information, future modifications to the access property list will not affect them. It is the responsibility of the application to free these objects."

We have had problems at run-time when the system runs out of handles for unfreed MPI communicators. We wish to avoid any unexpected issues with handles for unfreed MPI_INFO descriptors as well.  For MPI communicators, setting comm%mpi_val with the integer handle returned by H5Pget_fapl_mpio_f and calling MPI_COMM_FREE to free the comm object does work. That is, it returns zero for error code. It just doesn't work for MPI_INFO handles.

**Expected behavior**
MPI_INFO_FREE should return a zero error code when called with an MPI_INFO handle returned by H5Pget_fapl_mpio_f

**Platform (please complete the following information)**
 - HDF5 version **1.12.1**
 - OS and version **RHEL8**
 - Compiler and version **ifort 2021.6.0**
 - Build system (e.g. CMake, Autotools) and version
 - Any configure options you specified
 - MPI library and version (parallel HDF5) **Intel MPI, 2021.6.0**

**Additional context**
Can provide a reproducer if desired

**Comment by michalakes** [comment]
Here is an update: we discovered that the "handle" being returned for the mpiinfo%mpi_val argument is MPI_INFO_NULL, which is probably why the MPI_FREE_INFO routine is returning an non-zero error code when it tries to free the mpiinfo type instance.  A workaround is to check for MPI_INFO_NULL before freeing:

> if (mpiinfo%mpi_val \= MPI_INFO_NULL)
>    call mpi_info_free( mpiinfo, ierr )
> end if

Respectfully suggest adding a note in the documentation for H5Pget_fapl_mpio advising that it's possible for the routine to pass back a null handle for the MPI_INFO argument and that users should check for that condition before trying to free it. Developers who dutifully check error codes returned from library routines will be spared some mystery :)

**Comment by brtnfld** [comment]
Thanks for the report, I should be able to update the API for MPI-3, mpi_f08 compatibility. I'll update the Fortran documentation as well.

**Comment by brtnfld** [comment]
I added support for MPI_F08 and HDF5 Fortran APIs using MPI info and comm. It will be in the next 1.14 release.
