### ISSUE TITLE
Cross-compiling failing using vcpkg from linux (Ubuntu 20.04) to windows

### ISSUE THREAD

**Issue by neoceph** [HDFGroup/hdf5#3973]
**Describe the bug**
can't cross compile hdf5 using vcpkg from linux to windows

**Expected behavior**
`vcpkg install hdf5:x64-mingw-dynamic`
executing the above would successfully compile hdf5 library for windows from ubuntu.

**Platform (please complete the following information)**
 - HDF5 version 1.14.2
 - OS and version: Ubunu 20.04
 - Compiler and version: MinGW gcc/g++ v9.3

**Additional context**
Copying the error log below.

CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_IOEO_EXITCODE (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LDOUBLE_TO_LONG_SPECIAL_RUN (advanced)
   H5_LDOUBLE_TO_LONG_SPECIAL_RUN__TRYRUN_OUTPUT (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LONG_TO_LDOUBLE_SPECIAL_RUN (advanced)
   H5_LONG_TO_LDOUBLE_SPECIAL_RUN__TRYRUN_OUTPUT (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LDOUBLE_TO_LLONG_ACCURATE_RUN (advanced)
   H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_LLONG_TO_LDOUBLE_CORRECT_RUN (advanced)
   H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   H5_DISABLE_SOME_LDOUBLE_CONV_RUN (advanced)
   H5_DISABLE_SOME_LDOUBLE_CONV_RUN__TRYRUN_OUTPUT (advanced)
For details see /home/nirjhor/Software/vcpkg/buildtrees/hdf5/x64-linux-windows-dynamic-dbg/TryRunResults.cmake

**Comment by hyoklee** [comment]
Hi, @neoceph ! Thanks for testing HDF5 using vcpkg on Ubuntu.

I'm trying to replicate your error but I can't even install hdf5 package due to szip:

```
The following packages will be built and installed:
    hdf5[core,szip,zlib]:x64-mingw-dynamic@1.14.2
  * szip:x64-mingw-dynamic@2.1.1#12
  * vcpkg-cmake:x64-linux@20[23](https://github.com/hyoklee/actions/actions/runs/8258227944/job/22590080794#step:2:24)-05-04
  * vcpkg-cmake-config:x64-linux@2022-02-06#1
  * zlib:x64-mingw-dynamic@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Detecting compiler hash for triplet x64-mingw-dynamic...
Restored 0 package(s) from /home/runner/.cache/vcpkg/archives in 13.1 us. Use --debug to see more details.
Installing 1/5 vcpkg-cmake:x64-linux@2023-05-04...
Building vcpkg-cmake:x64-linux@2023-05-04...
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 55.4 ms.
Elapsed time to handle vcpkg-cmake:x64-linux: 79.3 ms
vcpkg-cmake:x64-linux package ABI: f9f38ce541b041bebc3e51030d3e3b72ba113708090c1e70a92d0e73965e02d6
Installing 2/5 vcpkg-cmake-config:x64-linux@2022-02-06#1...
Building vcpkg-cmake-config:x64-linux@2022-02-06#1...
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: /home/runner/work/actions/actions/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 2.45 ms.
Elapsed time to handle vcpkg-cmake-config:x64-linux: 18.2 ms
vcpkg-cmake-config:x64-linux package ABI: 9b7ea[25](https://github.com/hyoklee/actions/actions/runs/8258227944/job/22590080794#step:2:26)2d2a059acc11b8[27](https://github.com/hyoklee/actions/actions/runs/8258227944/job/22590080794#step:2:28)b2b185e3e4351072bd8e9ae6d13cd9633d4fb9e63
Installing 3/5 szip:x64-mingw-dynamic@2.1.1#12...
Building szip:x64-mingw-dynamic@2.1.1#12...
warning: -- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/runner/work/actions/actions/vcpkg/triplets/community/x64-mingw-dynamic.cmake
-- Downloading https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz -> szip-2.1.1.tar.gz...
-- Extracting source /home/runner/work/actions/actions/vcpkg/downloads/szip-2.1.1.tar.gz
-- Applying patch fix-linkage-config.patch
-- Applying patch mingw-lib-names.patch
-- Using source at /home/runner/work/actions/actions/vcpkg/buildtrees/szip/src/szip-2.1.1-15a12784d5.clean
-- Configuring x64-mingw-dynamic
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/runner/work/actions/actions/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v
    Working Directory: /home/runner/work/actions/actions/vcpkg/buildtrees/szip/x64-mingw-dynamic-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /home/runner/work/actions/actions/vcpkg/buildtrees/szip/config-x64-mingw-dynamic-dbg-CMakeCache.txt.log
      /home/runner/work/actions/actions/vcpkg/buildtrees/szip/config-x64-mingw-dynamic-rel-CMakeCache.txt.log
      /home/runner/work/actions/actions/vcpkg/buildtrees/szip/config-x64-mingw-dynamic-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/szip/portfile.cmake:[30](https://github.com/hyoklee/actions/actions/runs/8258227944/job/22590080794#step:2:31) (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)


error: building szip:x[64](https://github.com/hyoklee/actions/actions/runs/8258227944/job/22590080794#step:2:65)-mingw-dynamic failed with: BUILD_FAILED
```

Would you share your tips for installing hdf5 using vcpkg on Ubuntu?

**Comment by hyoklee** [comment]
@neoceph , thanks for testing with vcpkg!

I could duplicate your error with ubuntu 22.04 and hdf5 1.14.3 as well.

**Comment by hyoklee** [comment]
@neoceph , I could make it work with [hdf5-1.14.4 snapshot](https://gamma.hdfgroup.org/ftp/pub/outgoing/joe/HDFGroup-hdf5-hdf5-1_14_4.tar.gz) and my [vcpkg hdf5 patch](https://github.com/hyoklee/vcpkg).

Here's a complete [workflow](https://github.com/hyoklee/actions/actions/runs/8271743821/workflow) that uses the snapshot and patch.

However, there are [221 test failures](https://my.cdash.org/viewTest.php?onlyfailed&buildid=2519502).

**Comment by neoceph** [comment]
@hyoklee, I tried and can confirm it worked at my end too. Hopefully, you guys would be able to take care of the test failures and release it with 1.14.4. Waiting for that patiently!

Great work!
