### ISSUE TITLE
HDF5 fails to compile with -Werror=lto-type-mismatch

### ISSUE THREAD

**Issue by equaeghe** [HDFGroup/hdf5#3987]
**Describe the bug**
When compiling with lto enabled (`-flto=auto`) and related warnings for issues that then become problematic upgraded to errors (`-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`), HDF5 fails to compile. I get the following error:

```
H5Eff.F90:167:43: error: type of 'h5eget_minor_c' does not match original declaration [-Werror=lto-type-mismatch]
  167 |     hdferr = h5eget_minor_c(error_no, name)
      |                                           ^
H5Ef.c:182:1: note: type mismatch in parameter 3
  182 | h5eget_minor_c(int_f *error_no, _fcd name, size_t_f *namelen)
      | ^
H5Ef.c:182:1: note: 'h5eget_minor_c' was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gfortran returned 1 exit status
compilation terminated.
```

**Expected behavior**
HDF5 compiles.

**Platform**
 - HDF5 version: 1.14.3
 - OS and version: Gentoo Linux
 - Compiler and version: GCC 13.2.1_p20240113
 - Build system (e.g. CMake, Autotools) and version: Automake 1.16.5
 - Any configure options you specified: disable-static, disable-doxygen-errors, enable-deprecated-symbols, with-zlib, enable-hl, enable-fortran (unclear if this gives a complete picture)
 - MPI library and version (parallel HDF5): MPI not enabled

**Additional context**
Downstream bugs: https://bugs.gentoo.org/922800, https://bugs.gentoo.org/862723

**Comment by brtnfld** [comment]
Fixing, as long as I'm there, I'm adding H5E:

H5EREGISTER_CLASS_F
H5EUNREGISTER_CLASS_F
H5ECREATE_MSG_F
H5ECLOSE_MSG_F
H5EGET_MSG_F
H5EPUSH_F

**Comment by brtnfld** [comment]
Removed the use of troublesome C stub, PR #4049
