### ISSUE TITLE
Portal links from RELEASE.txt are broken.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#3991]
These links are broken:

https://portal.hdfgroup.org/display/HDF5/HDF5
https://portal.hdfgroup.org/display/HDF5/Release+Specific+Information

Added extension: broken links in the entire HDF5 library

**Comment by loricooperhdf** [comment]
Here's the full text: 

> Links to HDF5 documentation can be found on The HDF5 web page:
> 
>      https://portal.hdfgroup.org/display/HDF5/HDF5
> 
> Changes from Release to Release and New Features in the HDF5-1.16.x release series
> can be found at:
> 
>      https://portal.hdfgroup.org/display/HDF5/Release+Specific+Information

| Description | Wayback | My Recommendation |
| ---- | ---- | ---- |  
| Documentation | [Old](https://web.archive.org/web/20231001151908/https://portal.hdfgroup.org/display/HDF5/HDF5/) | https://portal.hdfgroup.org/hdf5/v1_14/index.html  | 
| Release Specific Information | [Old](https://web.archive.org/web/20230130043055/https://portal.hdfgroup.org/display/HDF5/Release+Specific+Information) | ??? | 

@bmribler, @byrnHDF What do you think we should do for the release specific information? We could make a statement about how that information can be found in the repositories?

**Comment by hyoklee** [comment]
These links are also broken in [doc/parallel-compression.md](https://github.com/HDFGroup/hdf5/blob/develop/doc/parallel-compression.md):

- https://portal.hdfgroup.org/display/HDF5/Chunking+in+HDF5
- http://portal.hdfgroup.org/display/HDF5/Improving+IO+Performance+When+Working+with+HDF5+Compressed+Datasets

**Comment by hyoklee** [comment]
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/HDFGroup/hdf5%24+portal.hdfgroup.org/display&patternType=keyword&sm=0

Credit: @lkurz

**Comment by ajelenak** [comment]
@hyoklee Can this issue be closed?

**Comment by bmribler** [comment]
> @bmribler, @byrnHDF What do you think we should do for the release specific information? We could make a statement about how that information can be found in the repositories?

@loricooperhdf, @byrnHDF  Right, we need to provide such information elsewhere and a statement of its location.  Perhaps, in the place where we say "Previous releases..."?

**Comment by derobins** [comment]
> @hyoklee Can this issue be closed?

Not yet. The release-specific information link is still broken.

**Comment by bmribler** [comment]
> > @hyoklee Can this issue be closed?
> 
> Not yet. The release-specific information link is still broken.

The link is almost available.  I just need to fix a bunch of formats and then it can be published, hoping this evening.

**Comment by bmribler** [comment]
@hyoklee Please check out the new release specific information page on:
https://portal.hdfgroup.org/documentation/index.html
The new item is:
 [Release Specific Information](https://portal.hdfgroup.org/documentation/hdf5-docs/release_specific_info.html) - *** UNDER CONSTRUCTION ***
If it's acceptable for now, I'll fix the link in RELEASE.txt.  Thanks!

**Comment by bmribler** [comment]
I just found out that markdown internal links don't work.  For example, on https://portal.hdfgroup.org/documentation/hdf5-docs/release_specifics/sw_changes_1.12.html, none of the internal links work.  They worked in VS Markdown editor but not in a web browser.  The issue was filed here: https://github.com/marktext/marktext/issues/2469.  It also mentioned the PR that was supposed to fix the issue, at the bottom of the conversation, but the PR is still Open.

**Comment by loricooperhdf** [comment]
@derobins should these be kept in the repository or on the portal? I thought doxygen/repository ("with the code") was more appropriate for this type of information.

**Comment by loricooperhdf** [comment]
> I just found out that markdown internal links don't work. For example, on https://portal.hdfgroup.org/documentation/hdf5-docs/release_specifics/sw_changes_1.12.html, none of the internal links work. They worked in VS Markdown editor but not in a web browser. The issue was filed here: [marktext/marktext#2469](https://github.com/marktext/marktext/issues/2469). It also mentioned the PR that was supposed to fix the issue, at the bottom of the conversation, but the PR is still Open.

@bmribler I put in an HTML replacement for the first link as an example, if you want to duplicate it and use that instead of creating separate documents.

**Comment by bmribler** [comment]
> @bmribler I put in an HTML replacement for the first link as an example, if you want to duplicate it and use that instead of creating separate documents.

Thanks @loricooperhdf, I finished them and, yes, I did it that way, didn't create separate documents.  Cleaner.
