### ISSUE TITLE
External link and file-locking disabled issue

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#4011]
[thomas.vincent](https://forum.hdfgroup.org/u/thomas.vincent)
[4d](https://forum.hdfgroup.org/t/external-link-and-file-locking-disabled-issue)
Hi,

We stumbled into an unexpected behavior when opening a hdf5 file with file locking disabled and accessing an external link: The file containing the external link is accessed with file locking enabled.

We were expecting that by default the external link files would be opened with the same file locking as the main file, i.e., the file locking would be “inherited” like it is the case for the read/write mode.

This script reproduces the issue: accessing data in the main file works but not in the external link file:
[link_locking_issue.py](https://forum.hdfgroup.org/uploads/short-url/z8ixrwlIOgJIQEgtpzwR4dNaurg.py) (757 Bytes)

The main file is opened by passing locking=False to h5py.File (which calls H5Pset_file_locking to disable file locking in the file access property list passed to open the file).
Then h5py opens the external link with a default file access property list, and so with file locking:
See https://github.com/h5py/h5py/blob/6b512e5edf80f6660e0f07c704ab59faa733008b/h5py/_hl/group.py#L357 and https://github.com/h5py/h5py/blob/6b512e5edf80f6660e0f07c704ab59faa733008b/h5py/_hl/base.py#L129-L135

I’m raising this issue here rather than in the h5py repository, because even if this might be fixable in h5py, I was expecting that libhdf5 would at least by default inherit the file access property list (or some of it) from the main file when accessing an external link (related to [External links & VFDs](https://forum.hdfgroup.org/t/external-links-vfds/9056)).

To try and propose a fix for this issue to h5py, I looked at retrieving the file locking value from the opened file id’s access property list in order to use it for opening external links.
However it seems the file locking value is not set in the access property list retrieved from the opened file. This script reproduce the issue:

[fapl_locking_issue.py](https://forum.hdfgroup.org/uploads/short-url/mCNZxntGk8VNdZmAJCR88QX1MzY.py) (513 Bytes)

Any idea how to tackle this issue? What is the proper way to handle file access property list?

Best,
Thomas

**Comment by jhendersonHDF** [comment]
Addressed in https://github.com/HDFGroup/hdf5/commit/46f7aa75fd09b5a61ea62e917634abe45ec41476
