### ISSUE TITLE
Replace deprecated Fortran 'include mpif.h' with 'USE mpi'

### ISSUE THREAD

**Issue by cniethammer** [HDFGroup/hdf5#4032]
**Describe the bug**
With MPI 4.1 the use of the `mpif.h` include file has been deprecated. Codes should transition to `USE mpi` or `USE mpi_f08`.

**Expected behavior**
HDF5 code, documentation, and examples should use the Fortran `USE mpi` or `USE mpi_f08` interface instead of the deprecated `include mpif.h`.

For proposed updates to the HDF sources see PR #4031 

**Additional context**
For the interested see section 19.1.4 of the MPI 4.1 standard on page  793 (https://www.mpi-forum.org/docs/)

**Comment by brtnfld** [comment]
Complete by PR #4031 merge.
