### ISSUE TITLE
Unable to read from S3 on Mac

### ISSUE THREAD

**Issue by jayceslesar** [HDFGroup/hdf5#4037]
**Describe the bug**
`h5ls --vfd=ros3 --s3-cred="(,,)" "https://s3.amazonaws.com/hdfgroup/data/hdf5demo/tall.h5"` results in `Error: Read-Only S3 VFD is not enabled`

**Expected behavior**
It displays the file

**Platform (please complete the following information)**
Mac (ARM chip)
❯ h5ls --version
h5ls: Version 1.14.3

**Comment by derobins** [comment]
Did you build HDF5 with ros3 VFD support?

**Comment by jayceslesar** [comment]
I just installed from brew -- Is it not included in that build?

**Comment by derobins** [comment]
It is not turned on by default since we try to avoid library dependencies (the S3 VFD depends on libcurl). You would have to build HDF5 yourself.

We'll try to improve the error message, but I'm going to go ahead and close this since it's known behavior.

**Comment by jayceslesar** [comment]
Thank you for clarifying! Id be happy to check that out as a feature if it makes sense. Only a problem for local testing as I can definitely automate building this in my orgs CI -- my use case was using the h5ls command on some data in S3 but I was able to get around that by doing 
```py
class H5ls:
    """Helper class to discover keys in an HDF5 File."""

    def __init__(self) -> None:
        """Initialize the class."""
        # Store an empty list for dataset names
        self.names: list[str] = []

    def __call__(self, name: str, h5obj: h5py.Dataset | h5py.Group) -> None:
        """Discover the file at the current level and filter to what we care about."""
        # only h5py datasets have dtype attribute, so we can search on this
        if hasattr(h5obj, "dtype") and name not in self.names:
                self.names.append(name)
```

along with the `visititems` attribute. Also happy to beef up docs on the python side of things if we think that is useful.
