### ISSUE TITLE
Tests Fail on RISC-V Platform During make check

### ISSUE THREAD

**Issue by U2FsdGVkX1** [HDFGroup/hdf5#4056]
**Describe the bug**
I encountered issues when running the test suite on a RISC-V platform. Specifically, two tests related to data compression fail during the `make check` process.

**Steps to Reproduce**
1. Configure the HDF5 build with following options.
2. Run `make -j64`.
3. Run `make check`.
4. Observe the failures in the following tests:
   - `Verifying output from ../../src/h5repack/h5repack -v -f /dset_deflate:*FAILED*`
   - `Verifying h5dump output -f GZIP=1 -m 1024 *FAILED*`
![1](https://github.com/HDFGroup/hdf5/assets/11484206/fbac4593-4c5e-4ad1-a6bc-08753bb96952)
![2](https://github.com/HDFGroup/hdf5/assets/11484206/5a90cfec-2337-476c-8126-d1097e46117c)

**Platform (please complete the following information)**
 - HDF5 version: 1.14.3
 - OS and version: Fedora 39 RISC-V
 - Compiler and version: gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)
 - Build system (e.g. CMake, Autotools) and version: 3.27.7
 - Any configure options you specified: `../configure --prefix=/usr --disable-static --disable-sharedlib-rpath --enable-build-mode=production --enable-hl --enable-cxx --enable-fortran --enable-java --with-pic --with-zlib --with-szlib`

**Comment by derobins** [comment]
This isn't a real library problem. It's failing due to the different compression ratio being picked up as "different" in a way that inappropriately fails the test. We have filtering for most things like this. Looks like we'll have to update the filters.

**Comment by derobins** [comment]
btw, CMake will probably pass these tests since it has more comprehensive filters.

**Comment by byrnHDF** [comment]
The issue is that the zlib of the test system and the zlib used by the HDF system produce slightly different compression ratios. The intent of the test is to make sure the compression was correctly applied. It seems that the test needs to be more involved to verify that the compression was correctly implemented. (Maybe allow a certain amount of delta in the values)

**Comment by rwmjones** [comment]
Note it's never correct to assume zlib output is the same.  There are multiple ways to zlib-compress a file even at the same compression level.  We have found that zlib works differently on different CPU architectures.  Also Fedora now uses zlib-ng not zlib.

**Comment by byrnHDF** [comment]
True. It just means that the test has to be more involved in checking that kind of situation then simply doing a compare.
Again the intent is to verify that compression correctly worked. We need to enhance tests to allow for variances.

**Comment by byrnHDF** [comment]
Also, simply ignoring the values makes the test almost useless as it ignores the intent.
