### ISSUE TITLE
7 VDS Example Tests Fail on Big Endian Machines

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5#4069]
**Describe the bug**

CTest fails on big endian machines.
They are 7 VDS example tests.

**Expected behavior**

All tests pass.

**Platform (please complete the following information)**
 - HDF5: develop branch
 - OS and version: 3.10.0-1160.36.2.el7.ppc64
 - Compiler and version: gcc
 - Build system (e.g. CMake, Autotools) and version: ctest-3.29.0-rc2

**Additional context**

https://my.cdash.org/viewTest.php?onlyfailed&buildid=2511204

**Comment by derobins** [comment]
These tests fail because the tests use H5T_NATIVE_INT for the dataset's type, which we then diff with the output from a little-endian machine. It's easily fixed by specifying a little-endian type for the dataset.

**Comment by derobins** [comment]
Fixed in #4070
