### ISSUE TITLE
version 1.14.3 under windows and CMAKE does not build with ZLIB 

### ISSUE THREAD

**Issue by jbensabat** [HDFGroup/hdf5#4075]
Hello 
I am trying to build hdf5 using cmake.
i download the file CMake-hdf5-1.14.3.zip  and tried building it with the batch file build-vs2022-64.bat
i builds correctly but without ZLIB 
how can I make work with ZLIB (I tried to put info in the HDf5Options.cmake file) but that did not help
any help would really be appreciated.
best
jac

**Describe the bug**

**Expected behavior**

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash)
 - OS and version
 - Compiler and version
 - Build system (e.g. CMake, Autotools) and version
 - Any configure options you specified
 - MPI library and version (parallel HDF5)

**Additional context**

**Comment by derobins** [comment]
Hi!

Support questions should be asked on the HDF Group Forum: 

https://forum.hdfgroup.org/
