### ISSUE TITLE
Fix the URL for the registered filters link in documentation and filters

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#4168]
http://www.hdfgroup.org/services/contributions.html

is now

https://portal.hdfgroup.org/documentation/hdf5-docs/registered_filter_plugins.html

**Comment by byrnHDF** [comment]
While the existing link does still resolve it indicates that it is not current.

**Comment by byrnHDF** [comment]
This is only partially fixed by 4129, plugin filter library needs fixed and then example references will need updated.

**Comment by bmribler** [comment]
We've decided to move these to the plugin repo.

**Comment by byrnHDF** [comment]
Completed by hdf5_plugins/#96 and hdf5/#4180
