### ISSUE TITLE
H5version.h: No such file or directory

### ISSUE THREAD

**Issue by EdrisBorne** [HDFGroup/hdf5#4177]
I am trying to build the latest version of HDF5 and create static library to be used in riscv-gnu-toolchain. I first configure it like:

`./configure --prefix=$RISCV_GNU_COMPILER --host=riscv64-unknown-linux-gnu`

then I ran make but I got the following error, 
 ```
 CC       H5.lo
In file included from H5private.h:23,
                 from H5.c:21:
H5public.h:31:10: fatal error: H5version.h: No such file or directory
   31 | #include "H5version.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1865: H5.lo] Error 1
```

could you please tell me how to solve this?

**Comment by derobins** [comment]
Hi,

You need to run autogen.sh to generate some files that autoreconf won't generate.

Also, technical support questions should be asked on the forum:

https://forum.hdfgroup.org/

We mainly use GitHub issues for reporting bugs.
