### ISSUE TITLE
Merge changes from PR #380 "Use do-while trick to force H5Epush_ret() to require trailing semi" to support branches

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#422]
Merge #380 needed to hdf5_1_12, hdf5_1_10, and hdf5_1_8 after passing all test configurations in daily test cycle

**Comment by byrnHDF** [comment]
Merge to 1.12 #438    Merged 3/5/2021
Merge to 1.10 #439    Merged 3/5/2021
Merge to 1.8 in #432    Merged 3/5/2021
