### ISSUE TITLE
Undefined-shift error in H5T_is_numeric_with_unusual_unused_bits

### ISSUE THREAD

**Issue by tbeu** [HDFGroup/hdf5#4293]
**Describe the bug**

H5T.c:6732:20: runtime error: shift exponent 64 is too large for 32-bit type 'unsigned int'
	    # 0 0x8bf9cc in H5T_is_numeric_with_unusual_unused_bits [hdf5/src/H5T.c:6732](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5T.c#L6732):20
	    # 1 0x790abf in H5O__dtype_decode_helper [hdf5/src/H5Odtype.c:818](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Odtype.c#L818):9
	    # 2 0x78af61 in H5O__dtype_decode [hdf5/src/H5Odtype.c:1403](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Odtype.c#L1403):9
	    # 3 0x78af61 in H5O__dtype_shared_decode [hdf5/src/H5Oshared.h:73](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Oshared.h#L73):34
	    # 4 0x7b0c9c in H5O_msg_read_oh [hdf5/src/H5Omessage.c:486](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Omessage.c#L486):5
	    # 5 0x7b0904 in H5O_msg_read [hdf5/src/H5Omessage.c:430](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Omessage.c#L430):30
	    # 6 0x64924b in H5D__open_oid [hdf5/src/H5Dint.c:1697](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Dint.c#L1697):51
	    # 7 0x64924b in H5D_open [hdf5/src/H5Dint.c:1501](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Dint.c#L1501):13
	    # 8 0x648c1b in H5D__open_name [hdf5/src/H5Dint.c:1436](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5Dint.c#L1436):25
	    # 9 0x9f4e2b in H5VL__native_dataset_open [hdf5/src/H5VLnative_dataset.c:331](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5VLnative_dataset.c#L331):25
	    # 10 0x9d8848 in H5VL__dataset_open [hdf5/src/H5VLcallback.c:1946](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5VLcallback.c#L1946):30
	    # 11 0x9d8669 in H5VL_dataset_open [hdf5/src/H5VLcallback.c:1978](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5VLcallback.c#L1978):30
	    # 12 0x63438c in H5D__open_api_common [hdf5/src/H5D.c:362](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5D.c#L362):25
	    # 13 0x634146 in H5Dopen2 [hdf5/src/H5D.c:402](https://github.com/HDFGroup/hdf5/blob/dded9372c229124044a6f163106999e718c8861e/src/H5D.c#L402):22

**Additional context**

Reported for dded9372c229124044a6f163106999e718c8861e.

**Comment by jhendersonHDF** [comment]
Thanks @tbeu, will take a look. It's likely that function can't operate in the general case without running up against undefined behavior.

**Comment by tbeu** [comment]
Fix confirmed: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67734#c3 Thanks.
