### ISSUE TITLE
Merge changes from PRs #425, 427, 428 to support branches.

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#435]
Merge needed to hdf5_1_12, hdf5_1_10, and hdf5_1_8 as appropriate for PRs #425, 427, 428 after passing all test configurations in daily test cycle

#425 Fixes various warnings noticed on Windows
#427 Fixed clang-tidy readability-misleading-indentation warnings 
 #428 Fixed clang-tidy readability-redundant-control-flow warnings

**Comment by lrknox** [comment]
PR #425 Fixes various warnings noticed on Windows was merged to hdf5_1_12 along with #427 Fixed clang-tidy readability-misleading-indentation warnings and #428 Fixed clang-tidy readability-redundant-control-flow warnings in PR #460.

#427 Fixed clang-tidy readability-misleading-indentation warnings and #428 Fixed clang-tidy readability-redundant-control-flow warnings were also merged to hdf5_1_10 in PR #462.

PR #425 Fixes various warnings noticed on Windows needs merging to hdf5_1_10.  Assigning this to Dana.

None have been merged to hdf5_1_8 pending further discussion.

**Comment by seanm** [comment]
@lrknox @derobins  sounds like this is mostly done?

**Comment by byrnHDF** [comment]
Will rely on branch compare as this is 1.5 years old.
