### ISSUE TITLE
Hyperlink still uses _ for tar files

### ISSUE THREAD

**Issue by HathewayWill** [HDFGroup/hdf5#4396]
https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.4/hdf5-1.14.4.tar.gz

**Comment by derobins** [comment]
Why is this important?

**Comment by HathewayWill** [comment]
In the notes from the release the author stated that _ were issues.  This is just a continuation of that to stream line everything into correct format

@derobins

**Comment by derobins** [comment]
Is there a link to a document that specifies acceptable file names for the package manager that is upset?
