### ISSUE TITLE
Commit 8b3ffde causes hdf5 build issues with some option combinations

### ISSUE THREAD

**Issue by uleysky** [HDFGroup/hdf5#4448]
Hdf-1.14.4.2 does'nt build after ./configure --enable-fortran --enable-cxx --enable-parallel --enable-unsupported. See Gentoo bug https://bugs.gentoo.org/930143.  Reverting commit 8b3ffdef3099d2699ec71a5f855966132b3d3c25 fixes this.

**Comment by derobins** [comment]
We can put this hack back in, but why is your build system emitting stray -l entries?

**Comment by uleysky** [comment]
I can’t answer because I haven’t found where and how the postdeps variable is generated. I can only say that it has something to do with the combination of all four options; if you remove any of them, everything works.

**Comment by derobins** [comment]
Should be fixed w/ #4501, which restores the sed line

**Comment by derobins** [comment]
This will appear in the 1.14.4-3 patch release
