### ISSUE TITLE
h5ls cores on toss4 system @llnl compiled with IntelOne API

### ISSUE THREAD

**Issue by markcmiller86** [HDFGroup/hdf5#4471]
I am attaching a tar file with as much info as I can provide.
 
There is no urgency here. I am reporting on an FYI basis.
 
This is happening on LLNL’s rztrona and I believe HDF5-1.14.0 was compiled with IntelOne API as the gdb-session file suggests.
 
On LLNL’s CZ, I think any toss4 system with IntelOneAPI compilers should be able to reproduce.

[h5ls-core.tgz](https://github.com/HDFGroup/hdf5/files/15272641/h5ls-core.tgz)

**Comment by lrknox** [comment]
Core dump observed on Quartz when running h5ls -vld domain0.silo/MESH with h5ls built from HDF5 1.14.0 with OpenMPI 4.1.2 / intel/2023.2.1-magic / cmake/3.26.3 modules.  The same command with h5ls built from HDF5 1.14.1 and 1.14.2 release tags and hdf5_1_14 and develop branches produces this output:

quartz1916{knox8}229: ../build/bin/h5ls -vld domain0.silo/MESH
Opened "domain0.silo" with sec2 driver.
MESH                     Type
    Attribute: silo scalar
        Type:      struct {
                   "ndims"            +0    native int
                   "nnodes"           +4    native int
                   "nzones"           +8    native int
                   "facetype"         +12   native int
                   "coord_sys"        +16   native int
                   "planar"           +20   native int
                   "group_no"         +24   native int
                   "time"             +28   native float
                   "dtime"            +32   native double
                   "zonelist"         +40   9-byte null-terminated ASCII string
                   "min_extents"      +49   [3] native double
                   "max_extents"      +73   [3] native double
                   "coord0"           +97   15-byte null-terminated ASCII string
                   "coord1"           +112  15-byte null-terminated ASCII string
                   "coord2"           +127  15-byte null-terminated ASCII string
                   "label0"           +142  2-byte null-terminated ASCII string
                   "label1"           +144  2-byte null-terminated ASCII string
                   "label2"           +146  2-byte null-terminated ASCII string
                   "units0"           +148  3-byte null-terminated ASCII string
                   "units1"           +151  3-byte null-terminated ASCII string
                   "units2"           +154  3-byte null-terminated ASCII string
               } 157 bytes
        Data:
               {ndims=3, nnodes=1000, nzones=729, facetype=100, coord_sys=120, planar=124, group_no=-1, time=0,
                dtime=0, zonelist="zonelist", min_extents=[0,0,0], max_extents=[2.66666666666667,3,3],
                coord0="/.silo/#000001", coord1="/.silo/#000002", coord2="/.silo/#000003", label0="X", label1="Y",
                label2="Z", units0="cm", units1="cm", units2="cm"}
    Attribute: silo_type scalar
        Type:      native int
        Data:
               510
    Location:  1:14912
    Links:     1
    Type:      shared-1:14912native int
    
    Output from HDF5 1.14.0 with the segfault was the same except for the last line (after Links:    1).
    It appears the problem was fixed before the HDF5 1.14.1 release, somewhere between December 2022 and May 2023
