### ISSUE TITLE
[1.14.4.2 regression] H5Lexists(): unable to synchronously check link existence

### ISSUE THREAD

**Issue by jschueller** [HDFGroup/hdf5#4472]
**Describe the bug**

since the 1.14.4.2 update the following code sample exits with error from the H5Lexists function:

```
#include <H5Cpp.h>
#include <iostream>

int main()
{
  H5::H5File h5File_;
  try
  {
    h5File_ = H5::H5File("/tmp/zou.h5", H5F_ACC_TRUNC);
  }
  catch (const H5::Exception &)
  {
    return 1;
  }
  const htri_t exist = H5Lexists(h5File_.getId(), "1", H5P_DEFAULT);
  std::cout << "H5Lexists="<<exist<<std::endl;
}
```

 (ok with 1.14.3 and previous versions)

it returns the following output:
```
HDF5-DIAG: Error detected in HDF5 (1.14.4-2) thread 0:
  #000: H5L.c line 1207 in H5Lexists(): unable to synchronously check link existence
    major: Links
    minor: Can't get value
  #001: H5L.c line 1172 in H5L__exists_api_common(): can't set object access arguments
    major: Links
    minor: Can't set value
  #002: H5VLint.c line 2677 in H5VL_setup_name_args(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #003: H5VLint.c line 1733 in H5VL_vol_object(): invalid identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
H5Lexists=-1
```

**Expected behavior**
H5Lexists should return 0 (the file does not exist)

**Platform (please complete the following information)**
 - HDF5 version 1.14.4.2
 - OS: Archlinux
 - GCC 13.2.1
 - Autotools
 - --enable-cxx
 - no MPI library

**Additional context**

I noticed that its ok if I initialize the h5File_ variable in one line instead of using the default ctor then reassign it (in my real code h5File_ is an attribute of a class so I have to use some default ctor)
```
int main()
{
  H5::H5File h5File_ = H5::H5File("/tmp/zou.h5", H5F_ACC_TRUNC);

  const htri_t exist = H5Lexists(h5File_.getId(), "1", H5P_DEFAULT);
  std::cout << "H5Lexists="<<exist<<std::endl;
}
```

bisecting results in b69c6fcbf62, (#3306), in particular the new Group::operator= /cc @seanm  @bmribler @derobins

**Comment by bmribler** [comment]
Thanks!  I'll check it out.
