### ISSUE TITLE
Missing packages of v1.14.4 at ftp

### ISSUE THREAD

**Issue by tbeu** [HDFGroup/hdf5#4486]
Packages of hdf 1.14.4 are missing at https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/. Would be appreciated if they get available there. Thanks.

**Comment by lrknox** [comment]
We are planning another patch release, 1.14.4-3, probably next week.  When that is available we will add the package to  https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14.

**Comment by tbeu** [comment]
Seems 1.14.4.3 is tagged now.

**Comment by tbeu** [comment]
Will the CMake-hdf5-1.14.4.* resources als be added again? Thanks.

**Comment by tbeu** [comment]
Any news on the CMake resources? Thanks again.

**Comment by lrknox** [comment]
The files that were in the CMake-hdf5-* files are now available from github.  See section "II. Quick Step Building HDF5 Libraries with CMake Script Mode" in release_docs/INSTALL_CMake.txt for files to download and build instructions.

**Comment by tbeu** [comment]
Oh, what an unexpecetd break in naming, tagging and versioning scheme and deployment location. Used to be  hdf5-1_14_3.tar.gz, but now it is  hdf5-1.14.4-3.zip, so with dots instead of underscore and another build version beside the patch version. 😕
