### ISSUE TITLE
Add option for page buffer cache size to command-line tools

### ISSUE THREAD

**Issue by ajelenak** [HDFGroup/hdf5#4508]
**Is your feature request related to a problem? Please describe.**
Performance when accessing cloud optimized HDF5 files greatly benefits when using page buffer cache. Currently, CLI tools, like h5dump or h5ls, do not have an option to set page bugger cache size.

**Describe the solution you'd like**
Add an option for all CLI tools to set page buffer cache.

**Describe alternatives you've considered**
There are no alternatives I am aware of.

**Comment by byrnHDF** [comment]
PR #4562 adds this option to tools

**Comment by byrnHDF** [comment]
merged to develop
