### ISSUE TITLE
C++ wrapper tests build issue on aarch64 due to _Float16 type

### ISSUE THREAD

**Issue by jhendersonHDF** [HDFGroup/hdf5#4517]
**Describe the bug**
HDF5 1.14.4 (and the develop branch) cannot be built on aarch64 when C++ is enabled due to the C++ tests including H5private.h and failing when encountering the `_Float16` type. More context in #4495 and #4507. Reported by @wswsmao.

**Expected behavior**
HDF5 can be built on aarch64 with C++ enabled

**Platform (please complete the following information)**
- HDF5 version - HDF5 1.14.4 / develop (b6b7f547be5af0f95518a2a86b5fc287b4be158f)
- OS and version - unspecified aarch64
- Compiler and version - unspecified g++
- Build system - CMake / Autotools

**Additional context**
HDF5's C++ wrapper tests should be refactored to reduce the usage of private header files from the C library and avoid including H5private.h.

**Comment by jebos** [comment]
This issue also causes that you can not build the library (c++) for IOS. Using AppleClang with arm64 runs in the exact same issue. Disabling float16 (which is disabled in cmake configure) does not help.

**Comment by jhendersonHDF** [comment]
Hi @jebos, is the failure you're seeing what's reported in #4578? If so, it shouldn't be related to this issue but rather due to missing `getcwd` on IOS.

**Comment by jebos** [comment]
You are right, first i thought so since the error seemed in the same area and architecture. But it's not related.

**Comment by byrnHDF** [comment]
The CI for macos-14 has disabled the C++ option until a resolution is found.
