### ISSUE TITLE
H5DRead_f Bug while compilation

### ISSUE THREAD

**Issue by ErikP94** [HDFGroup/hdf5#4557]
**Problem**
I can't compile a minimal Fortran example with HDF5. The Problem is one specific function call -  h5dread_f: 

I compiled with:
gfortran -o hdf5_test hdf5_test_min.f90 -I/usr/local/hdf5/include/ -L/usr/local/hdf5/lib/ -lhdf5_fortran -lhdf5

```
hdf5_test_min.f90:64:67:

   64 |   call h5dread_f(dataset_id, dtype_id, C_Loc(element_read(1)), err)
      |                                                                   1
Error: There is no specific subroutine for the generic ‘h5dread_f’ at (1)
```

The minimal example contains a simple process, in which dummy data is created, then written to a hdf5 file (which works) and then the data shall be read.
Please note, that the h5dwrite_f function call works.
I suspect, that the input arguments are okay, since the same example works under MacOS and also because the h5dwrite_f call works.

**Platform**
 - HDF5 version1.14.0 (same issue with 1.14.4)
 - Ubuntu 22.04.3
 - GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
 - I built hdf5 with cmake and make, i also specified fortran2003

**Comment by ErikP94** [comment]
Here is a minimal example to reproduce the (maybe?) bug.
[hdf5_test_min.f90.txt](https://github.com/user-attachments/files/15785327/hdf5_test_min.f90.txt)

**Comment by brtnfld** [comment]
Since it is expecting something to be returned, try passing a  variable of type(C_PTR) instead:

```
TYPE(C_PTR) :: f_ptr
f_ptr = C_LOC(element_orig(1))
call h5dread_f(dataset_id, dtype_id, f_ptr, err)
```

**Comment by ErikP94** [comment]
Hi @brtnfld, thanks for the quick reply. This indeed seems to solve my problem!

**Comment by brtnfld** [comment]
Glad it works now.
