### ISSUE TITLE
h5pfc does not include module paths on mac when HDF5 is built with CMake

### ISSUE THREAD

**Issue by brtnfld** [HDFGroup/hdf5#4559]
**Describe the bug**
The h5pfc wrapper does not include the module paths and requires the user to include the path

**Expected behavior**
h5pfc should not require the user to input HDF5 paths

**Platform (please complete the following information)**
 - HDF5 version -- develop
 - OS and version -- OSX 14.5
 - Compiler and version -- gfortran 14.1
 - Build system (e.g. CMake, Autotools) and version -- CMake
 - Any configure options you specified
 - MPI library and version (parallel HDF5) mpich 4.2.1

**Comment by byrnHDF** [comment]
The pc file does have the module path:
`exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
moddir=${prefix}/mod

Name: hdf5_fortran
Description: HDF5 (Hierarchical Data Format 5) Software Library
Version: 1.15.0

Cflags: -I${includedir}
Fflags: -I${moddir}
Libs: -L${libdir}  -lhdf5_fortran
Requires: hdf5 = 1.15.0
Libs.private:  -lhdf5_fortran 
Requires.private: hdf5 = 1.15.0
`

**Comment by byrnHDF** [comment]
What it doesn't have is the shared/static extension.

**Comment by byrnHDF** [comment]
fixed by #4593
