### ISSUE TITLE
Use TestExpress feature in all tests

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#4576]
Currently, these tests use the test scale 0-3 where 0 is most extensive and 3 the minimal. TestExpress default is 3.

-----------------------------

test/btree2.c:    ExpressMode = GetTestExpress();

test/cache.c:    express_test = GetTestExpress();

test/cache_api.c:    express_test = GetTestExpress();

test/cache_image.c:    express_test = GetTestExpress();

test/earray.c:    ExpressMode = GetTestExpress();

test/farray.c:    ExpressMode = GetTestExpress();

test/fheap.c:    ExpressMode = GetTestExpress();

test/h5test.h:H5TEST_DLL int         GetTestExpress(void);

test/objcopy.c:    ExpressMode = GetTestExpress();

test/objcopy_ref.c:    ExpressMode = GetTestExpress();

test/tsohm.c:    if (GetTestExpress() > 1)

test/tsohm.c:    if (GetTestExpress() > 1)

test/testframe.c:GetTestExpress(void)

testpar/t_2Gio.c:    express_test = GetTestExpress();

testpar/t_shapesame.c:    local_express_test = GetTestExpress();

testpar/t_shapesame.c:    local_express_test = GetTestExpress();

testpar/t_shapesame.c:        printf("    express_test = %d.\n", GetTestExpress());

testpar/t_filters_parallel.c:    test_express_level_g = GetTestExpress();

testpar/t_cache.c: *         by GetTestExpress() across all processes.  Return this

testpar/t_cache.c: *                 GetTestExpress() across    all processes.

testpar/t_cache.c:    express_test = GetTestExpress();

**Comment by byrnHDF** [comment]
Almost every test treats it as a boolean - usually 0 == 1 is ON and val > 1 is OFF

Also almost every test has it as a local variable in the main function, and a couple may pass it into test functions.

**Comment by derobins** [comment]
The testing framework has been fixed, but we'll need people to go through and decide appropriate levels.
