### ISSUE TITLE
CMake Error: get_filename_component called with incorrect number of arguments

### ISSUE THREAD

**Issue by tbeu** [HDFGroup/hdf5#4671]
**Describe the bug**
```
CMake Error at CMakeFilters.cmake:109 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  CMakeLists.txt:917 (include)
```

**Expected behavior**
CMake should not fail during configuration

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): 9fd4fd0b586fc99fea6eafd9038b22bcb73bb9c3
 - OS and version; Win10
 - Compiler and version: VS2017
 - Build system (e.g. CMake, Autotools) and version: CMake 3.24.2
 - Any configure options you specified: `-DHDF_BUILD_HL_LIB:BOOL="0" -DH5EX_BUILD_TESTING:BOOL="0" -DHDF5_ENABLE_SZIP_ENCODING:BOOL="0" -DONLY_SHARED_LIBS:BOOL="1" -DZLIB_LIBRARY_DEBUG:FILEPATH="c:\Projekte\zlib\win64\Debug\zlibstaticd.lib" -DTEST_SHELL_SCRIPTS:BOOL="0" -DHDF5_ENABLE_ALL_WARNINGS:BOOL="1" -DBUILD_STATIC_LIBS:BOOL="0" -DHDF5_TEST_TOOLS:BOOL="0" -DHDF5_TEST_PARALLEL:BOOL="0" -DHDF5_TEST_CPP:BOOL="0" -DHDF5_TEST_SERIAL:BOOL="0" -DBUILD_TESTING:BOOL="0" -DHDF5_TEST_EXAMPLES:BOOL="0" -DHDF5_ENABLE_TRACE:BOOL="1" -DHDF5_TEST_SWMR:BOOL="0" -DHDF5_TEST_FORTRAN:BOOL="0" -DZLIB_LIBRARY_RELEASE:FILEPATH="c:\Projekte\zlib\win64\Debug\zlibstaticd.lib" -DHDF5_TEST_JAVA:BOOL="0" -DHDF5_USE_ZLIB_STATIC:BOOL="1" `
 - MPI library and version (parallel HDF5)

**Additional context**
I tried to test for #4111 and pulled 9fd4fd0b586fc99fea6eafd9038b22bcb73bb9c3. However CMake configure failed with the above error message. If I partially revert #4655 to avoid the function `get_filename_component` configuration works again.

```diff
diff --git a/CMakeFilters.cmake b/CMakeFilters.cmake
index 52d65e59e4..33ea23af9d 100644
--- a/CMakeFilters.cmake
+++ b/CMakeFilters.cmake
@@ -104,12 +104,7 @@ if (HDF5_ENABLE_Z_LIB_SUPPORT)
         set (H5_ZLIB_HEADER "zlib.h")
         set (H5_ZLIB_INCLUDE_DIR_GEN ${ZLIB_INCLUDE_DIR})
         set (H5_ZLIB_INCLUDE_DIRS ${H5_ZLIB_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIR})
-        # The FindZLIB.cmake module does not set an OUTPUT_NAME
-        # on the target. The target returned is: ZLIB::ZLIB
-        get_filename_component (libname ${ZLIB_LIBRARIES} NAME_WLE)
-        string (REGEX REPLACE "^lib" "" libname ${libname})
-        set_target_properties (ZLIB::ZLIB PROPERTIES OUTPUT_NAME zlib-static)
-        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ZLIB::ZLIB)
+        set (LINK_COMP_LIBS ${LINK_COMP_LIBS} ${ZLIB_LIBRARIES})
       endif ()
     else ()
       if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT" OR HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
```

**Comment by glennsong09** [comment]
This issue should be fixed now with #4613.
