### ISSUE TITLE
HDF5 threadsafe is not threadsafe

### ISSUE THREAD

**Issue by hofmannu** [HDFGroup/hdf5#4689]
**Describe the bug**
I am trying to load two different files from two different threads with HDF5 1.14.3 and the threadsafe option enabled but the execution crashes with 

```
HDF5-DIAG: Error detected in HDF5 (1.14.3) thread 0:
  #000: <path>\H5D.c line 1061 in H5Dread(): can't synchronously read data
    major: Dataset
    minor: Read failed
  #001: <path>\H5D.c line 1008 in H5D__read_api_common(): can't read data
    major: Dataset
    minor: Read failed
  #002: <path>\H5VLcallback.c line 2097 in H5VL_dataset_read_direct(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #003: <path>\src\H5VLint.c line 2356 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value
```

If i enforce file reading to finish from one thread before the other one starts, everything works.

**Expected behavior**
threadsafe means that I should be capable to perform this operation.

**Platform (please complete the following information)**
 - HDF5 version: 1.14.3
 - OS and version: Win 11, Win Server 2019, basically any
 - Compiler and version: MVSC 17.10
 - Build system (e.g. CMake, Autotools) and version: independent
 - static linkage
 - parallel disabled

**Additional context**
I think this super basic procedure of reading different files from multiple threads should be supported by any library used in 2024 for file reading.

**Comment by jhendersonHDF** [comment]
Hi @hofmannu, could you post the build options you used with CMake when building? In the HDF5 1.14.2 release, static thread-safe Windows builds would print out a warning message but still succeed even though they wouldn't be thread-safe. In the 1.14.3 release, this was changed so that static thread-safe Windows builds should fail.

**Comment by hofmannu** [comment]
sorry, my bad. i used conan package manager for building and they silently remove the threadsafe option when there is the wrong configuration (see https://github.com/conan-io/conan-center-index/blob/master/recipes/hdf5/all/conanfile.py line 68ff). thank you for your reply :).

not entirely sure but I think this will hence produce a valid conan package with the threadsafe option even though the non thread safe version was built?
