### ISSUE TITLE
H5Pset_filter() Undocumented Behavior When Passing 0 and NULL for cd_nelmts and cd_values[] Respectively

### ISSUE THREAD

**Issue by skyFzz** [HDFGroup/hdf5#4697]
**Describe the bug**
I called the function `H5Pset_filter()` with 0 and NULL for cd_nelmts and cd_values[], respectively. The filter was applied successfully to all the datasets. But when I used 'h5dump -H -p' to display the h5 file, there is an array of integers called `PARAMS` following after the line of the compression filter's name. Since I have not passed any auxiliary data, I was incapable of interpreting what these values mean, as they are probably the default behavior for `H5Pset_filter()`.

**Expected behavior**
I expect `PARAMS` would be empty, or have some default values that are explained in the API.

**Platform (please complete the following information)**
 - HDF5 version (if building from a maintenance branch, please include the commit hash): 1.14
 - OS and version: Linux owens-login04.hpc.osc.edu 3.10.0-1160.118.1.el7.x86_64 GNU/Linux
 - Compiler and version: gcc-compatibility/8.4.0
 - Build system (e.g. CMake, Autotools) and version: CMAKE 3.30
 - Any configure options you specified
  ~/.local/bin/cmake -DCMAKE_INSTALL_PREFIX=$HDF5_HOME \
                   -DHDF5_ENABLE_PARALLEL=ON \
                   -DHDF5_ENABLE_THREADSAFE=ON \
                   -DALLOW_UNSUPPORTED=ON \
                   -DHDF_BUILD_FILTERS=ON \
                   -DCMAKE_C_COMPILER=mpicc \
	                 -DHDF5_ENABLE_DEBUG_APIS=ON \
                   ..
 - MPI library and version (parallel HDF5): icc (ICC) 19.0.5.281 20190815

**Additional context**
This is the output when SZ3 filter is applied and 0 and NULL is used for cd_nelmts and cd_values[]:
```
FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32024
               COMMENT SZ3 compressor/decompressor for floating-point data.
               PARAMS { 1 7 0 4194304 }
            }
 }
```
This is the output of ZFP:
```
FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32013
               COMMENT H5Z-ZFP-1.1.1 (ZFP-1.0.1)
               
               PARAMS { 269504785 91252346 67108848 -1048576 -527925248 493487 }
            }
}
```

**Comment by byrnHDF** [comment]
h5dump relies on the return of H5Pget_filter2 as to the va;ue in cd_nelmts. In order to fill out the values they must exist. If they don't exist then they can't be filled in, so h5dump creates them.
Then the internal call fills the values with the values in the H5Z_filter_info_t structure, which was retrieved from the filter pipeline. These values are set in the H5Z_set_local_func_t function from the UD filter plugin.

Looking at the H5Pset_filter function -- I don't think you can set cd_values to NULL. You can set cd_nelmts to 0 and zero out the cd_values array.

**Comment by skyFzz** [comment]
Thanks Byrn for the clarification.
