### ISSUE TITLE
Built-in SZIP Filter Was Failed Applying Through H5Pset_szip() But GZIP And NBIT Are Working

### ISSUE THREAD

**Issue by skyFzz** [HDFGroup/hdf5#4718]
**Describe the bug**
I tried to use Szip filter on my datasets by calling `ret = H5Pset_szip(COMPRESS_INFO.dcpl_id, H5_SZIP_EC_OPTION_MASK, 8);`. It failed to retrieve the filter info. The same calling procedures on Gzip and N_bit filters were successful and the documentation stated that they are all built-in filter which does not require external libraries. But I don't know why only Szip failed.
 
```
1   HDF5-DIAG: Error detected in HDF5 (1.14.1-2) MPI-process 0:
  1   #000: /hdf5/src/H5Pdcpl.c line 2911 in H5Pset_szip(): can't get filter info
  2     major: Invalid arguments to routine
  3     minor: Bad value
  4   #001: /hdf5/src/H5Z.c line 1692 in H5Z_get_filter_info(): Filter not defined
  5     major: Data filters
  6     minor: Bad value
  7   #002: /hdf5/src/H5Z.c line 1254 in H5Z_find(): required filter 4 is not registered
  8     major: Data filters
  9     minor: Object not found
```
Also does Szip works on H5Dread?

**Expected behavior**
Expect Szip would work same as Gzip and N_Bit because they are all built in filters unlike external filters which needs extra libraries.

**Platform (please complete the following information)**
 - HDF5 version hdf5-1_14_1-2
 - OS and version Red Hat Enterprise Linux 3.10.0-1160.119.1.el7.x86_64
 - Compiler and version cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
 - Build system (e.g. CMake, Autotools) and version CMake version 3.28.3
 - Any configure options you specified
 - MPI library and version (parallel HDF5) mpicc Version 19.0.5.281

**Comment by byrnHDF** [comment]
required filter 4 is not registered
This indicates that szip was not built with the library. Check the configure logs to be sure that szip was actually built-in, because historically it will just issue a warning and continue. szip and zlib are optional build-ins.

**Comment by skyFzz** [comment]
I just want to make sure I have the correct configuration before rebuild HDF5. This is the macro I need to turn on correct? `HDF5_ENABLE_SZIP_SUPPORT         OFF`

**Comment by byrnHDF** [comment]
Yes, and for seeing more of configure log, add -VV and --log-level=VERBOSE to the configure command line.

From the release_docs/INSTALL_CMake.txt file, for building szip/zlib in-line:
`
   2. If you plan to use Zlib or Szip:
      A. Download the binary packages and install them in a central location.
         For example on Windows, create a folder extlibs and install the
         packages there. Add the following CMake options:
            -DH5_ZLIB_LIBRARY:FILEPATH=some_location/lib/zlib.lib
            -DH5_ZLIB_INCLUDE_DIR:PATH=some_location/include
            -DZLIB_USE_EXTERNAL:BOOL=OFF
            -DH5_SZIP_LIBRARY:FILEPATH=some_location/lib/szlib.lib
            -DH5_SZIP_INCLUDE_DIR:PATH=some_location/include
            -DSZIP_USE_EXTERNAL:BOOL=OFF
         where "some_location" is the full path to the extlibs folder.
         Also the appropriate environment variable must be set;
            set(ENV{ZLIB_ROOT} "some_location")
            set(ENV{SZIP_ROOT} "some_location")

      B. Use source packages from an GIT server by adding the following CMake
         options:
            HDF5_ALLOW_EXTERNAL_SUPPORT:STRING="GIT"
            ZLIB_GIT_URL:STRING="https://some_location/zlib"
            ZLIB_GIT_BRANCH="some_branch"
            SZIP_GIT_URL:STRING="https://some_location/szip"
            SZIP_GIT_BRANCH="some_branch"
         where "some_location" is the URL to the GIT repository and "some_branch" is
         a branch in the repository, usually the default. Also set
         CMAKE_BUILD_TYPE to the configuration type.

      C. Use source packages from a compressed file by adding the following
         CMake options:
            HDF5_ALLOW_EXTERNAL_SUPPORT:STRING="TGZ"
            ZLIB_TGZ_NAME:STRING="zlib_src.ext"
            LIBAEC_TGZ_NAME:STRING="libaec_src.ext"
            TGZPATH:STRING="some_location"
         where "some_location" is the URL or full path to the compressed
         file and ext is the type of compression file. Also set CMAKE_BUILD_TYPE
         to the configuration type during configuration. See the settings in the
         config/cmake/cacheinit.cmake file HDF uses for testing.

      D. Use original source packages from a compressed file by adding the following
         CMake options:
            LIBAEC_TGZ_NAME:STRING="szip_src.ext"
            LIBAEC_TGZ_ORIGPATH:STRING="some_location"

            ZLIB_TGZ_NAME:STRING="zlib_src.ext"
            ZLIB_TGZ_ORIGPATH:STRING="some_location"

            HDF5_ALLOW_EXTERNAL_SUPPORT:STRING="TGZ"
         where "some_location" is the URL and by setting
            ZLIB_USE_LOCALCONTENT:BOOL=OFF
            LIBAEC_USE_LOCALCONTENT:BOOL=OFF
         or full path to the compressed file and ext is the type of compression file.
         Also set CMAKE_BUILD_TYPE to the configuration type during configuration.
         See the settings in the config/cmake/cacheinit.cmake file HDF uses for testing.

         The files can also be retrieved from a local path if necessary
            TGZPATH:STRING="some_location"
         by setting
            ZLIB_USE_LOCALCONTENT:BOOL=ON
            LIBAEC_USE_LOCALCONTENT:BOOL=ON
`

**Comment by skyFzz** [comment]
Could you please also link me to where and how I can obtain a working instruction to download the binary packages of szip? I tried instructions on this page `https://github.com/erdc/szip/blob/master/INSTALL` but failed to obtain szip's source tar ball:
```
$ wget ftp://ftp.hdfgroup.org/lib-external/szip/2.1/src/
--2024-08-16 11:45:50--  ftp://ftp.hdfgroup.org/lib-external/szip/2.1/src/
           => ‘.listing’
Resolving ftp.hdfgroup.org (ftp.hdfgroup.org)... 50.28.50.143
Connecting to ftp.hdfgroup.org (ftp.hdfgroup.org)|50.28.50.143|:21... connected.
Logging in as anonymous ... 
The server refuses login.
Retrying.
```

**Comment by byrnHDF** [comment]
See the  release_docs/INSTALL_CMake.txt in the develop branch on GitHub or the latest 1.14 release source

**Comment by skyFzz** [comment]
Hi Byrn, thanks for all the comments. But after following all the instructions to build szip and rebuild hdf5, I still had the same error:
```
1   HDF5-DIAG: Error detected in HDF5 (1.14.1-2) MPI-process 0:
  1   #000: /hdf5/src/H5Pdcpl.c line 2911 in H5Pset_szip(): can't get filter info
  2     major: Invalid arguments to routine
  3     minor: Bad value
  4   #001: /hdf5/src/H5Z.c line 1692 in H5Z_get_filter_info(): Filter not defined
  5     major: Data filters
  6     minor: Bad value
  7   #002: /hdf5/src/H5Z.c line 1254 in H5Z_find(): required filter 4 is not registered
  8     major: Data filters
  9     minor: Object not found
```

I downloaded szip and installed szip:
```
wget https://github.com/MathisRosenhauer/libaec/releases/download/v1.1.3/libaec-1.1.3.tar.gz
tar -xzf libaec-1.1.3.tar.gz
cd libaec-1.1.3
mkdir build installer
realpath installer
cd build
~/.local/bin/cmake -DCMAKE_INSTALL_PREFIX=/libaec-1.1.3/installer ..
make
make install
```

I rebuilt HDF5:
```
export SZIP_ROOT=/libaec-1.1.3/installer
export HDF5_HOME=/hdf5/installer
~/.local/bin/cmake -DCMAKE_INSTALL_PREFIX=$HDF5_HOME \
                   -DHDF5_ENABLE_PARALLEL=ON \
                   -DHDF5_ENABLE_THREADSAFE=ON \
                   -DALLOW_UNSUPPORTED=ON \
                   -DH5_SZIP_LIBRARY:FILEPATH=/libaec-1.1.3/installer/lib64/libsz.a \
                   -DH5_SZIP_INCLUDE_DIR:PATH=/libaec-1.1.3/installer/include \
                   -DSZIP_USE_EXTERNAL:BOOL=OFF \
                   -DCMAKE_C_COMPILER=mpicc \
	           -DHDF5_ENABLE_DEBUG_APIS=ON \
                   ..
make
make install
```

Which step did I do wrong?

**Comment by byrnHDF** [comment]
Can you post the error or warning from the config concerning szip?
We should probably move this the forum.

**Comment by skyFzz** [comment]
Moved to forum and post pending. This is my username: Zhouhaoling1201.
