### ISSUE TITLE
When HDF5_BUILD_CPP_LIB and HDF5_ENABLE_PARALLEL are both enabled configure fails: Parallel and C++ options are mutually exclusive, override with ALLOW_UNSUPPORTED option

### ISSUE THREAD

**Issue by yurivict** [HDFGroup/hdf5#4874]
**Describe the bug**
Why are these mutually exclusive? What if some project would need to use both C++ and parallel option?

I believe that I saw such project, but can't find it now.

**Comment by byrnHDF** [comment]
That is the purpose of ALLOW_UNSUPPORTED, the user can override the suggested incompatible options.

**Comment by yurivict** [comment]
But the question is then why is this unsupported after so many years?
Is there anything wrong with this combination of options?

**Comment by lrknox** [comment]
I think it is unsupported because HDF5 doesn't have any parallel c++ tests, so it was thought better to not give the impression that it is supported.  Spack wanted both enabled, so the HDF5 spack packages have been configured with ALLOW_UNSUPPORTED since its beginning.

**Comment by yurivict** [comment]
Thank you for this explanation.
