### ISSUE TITLE
hdf5 is broken in cmake

### ISSUE THREAD

**Issue by esaaprillia** [HDFGroup/hdf5#5159]
hdf5 is broken in cmake. This problem has been around for a long time, why until now there has been no fix. I see alpine archlinux voidlinux gentoo and fendora don't use cmake to build hdf5.

**Comment by derobins** [comment]
We build and test HDF5 using CMake as a part of our CI and support for the Autotools is being dropped in HDF5 2.0.0. Can you be more specific about what is not working?

**Comment by esaaprillia** [comment]
```
-- ....All Warnings are enabled
-- Could NOT find ZLIB (missing: ZLIB_DIR)
-- Checking for one of the modules 'zlib'
-- Found ZLIB: /home/runner/work/mosdns/mosdns/sdk/staging_dir/target-aarch64_generic_musl/usr/lib/libz.so (found version "1.3.1")
-- Could NOT find SZIP (missing: SZIP_DIR)
CMake Warning at CMakeFilters.cmake:159 (find_package):
  By not providing "FindSZIP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SZIP", but
  CMake did not find one.

  Could not find a package configuration file provided by "SZIP" with any of
  the following names:

    SZIPConfig.cmake
    szip-config.cmake

  Add the installation prefix of "SZIP" to CMAKE_PREFIX_PATH or set
  "SZIP_DIR" to a directory containing one of the above files.  If "SZIP"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:909 (include)


CMake Warning at CMakeFilters.cmake:201 (message):
  SZIP support in HDF5 was enabled but not found
Call Stack (most recent call first):
  CMakeLists.txt:909 (include)
```

**Comment by derobins** [comment]
You asked for szip support and CMake couldn't find the szip library on your system. This is not an HDF5 bug. It's expected behavior to fail to configure when an invalid configuration is specified.

If you have questions about getting szip to work on your system, we handle community support via the HDF Group forums, so you should ask questions there.

https://forum.hdfgroup.org/
