### ISSUE TITLE
Merge changes from PRs #400, 414, 479, 480, 481, 483, 492, 493, 494, 495, 496 to support branches.

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#537]
#400 More warning fixes                               580008d    22 files changed
#414 Changes found during merge to 1.12  fab95ce      85 files changed
#479 Align with "parallel fence" changes      3dbbd8a    13 files changed
#480 File locks now work on Windows          60e14b8      6 files changed
#481 small edits                                             98acb0a      2 files changed
#483 Adds an implementation                      05bc190      3 files changed
         for nanosleep on Windows
#492 Updates HSYS_GOTO_ERROR to           69f3cde      2 files changed
         emit GetLastError() values on Win32
#493 Updates that allow accum SWMR        e0eb5c6      2 files changed
         tests to work on Windows
#494 Disable long double tests and             99c0f50       5 files changed
         remove CMake flag groups
#495 Misc warning fixes                               df9abfe       9 files changed
#496 Removes support for                           1f3f7fe        3 files changed
         pre-2015 Visual Studio

**Comment by seanm** [comment]
@lrknox were these ever done?

**Comment by byrnHDF** [comment]
Will rely on branch compare as this is 1.5 years old.
