### ISSUE TITLE
Error reading large (> 2GB) datasets w/ MPI-IO

### ISSUE THREAD

**Issue by michael-afanasiev** [HDFGroup/hdf5#549]
Hi everyone,

[Here](https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/l) it seems as if dataset size constraints for MPI-IO driven data transfers have been mitigated via a derived-type solution within HDF5. I am, however, still having trouble reading contiguous arrays >= 2GB as of HDF5 1.12.0. I've tracked this errors down to the following line in `H5FD__mpio_read`:
https://github.com/HDFGroup/hdf5/blob/78fe6751b5a682111e8bc2bf7ce944c55d52ba56/src/H5FDmpio.c#L1192-L1194

When looking at the code for `H5FD__mpio_write`, I can see the derived-type solution implemented:
https://github.com/HDFGroup/hdf5/blob/78fe6751b5a682111e8bc2bf7ce944c55d52ba56/src/H5FDmpio.c#L1475-L1488

Is it possible that the mitigation was applied only to writes with MPI-IO, and not to reads? Happy to work on a PR applying the same thing to reads, but just want to make sure I'm not missing anything.

Cheers,
Mike.

**Comment by jhendersonHDF** [comment]
This was addressed in https://github.com/HDFGroup/hdf5/commit/feda52b08488dbb3e5b2450f6cd63baa98b0e57e for the HDF5 1.12.3 release. Unfortunately, that change never made it into the release notes for that release.
