### ISSUE TITLE
Something is still introspecting `sizeof (long double)` at compile time, breaking macOS Universal Binary builds

### ISSUE THREAD

**Issue by seanm** [HDFGroup/hdf5#566]
Even after I made various fixes, I suspect something is still introspecting `sizeof (long double)` at compile time.

The problem occurs when I build HDF5 as a Universal Binary on macOS (that is, for both x86_64 and arm64 architectures).  On x86_64 `sizeof (long double)` is 16.  On arm64 it is 8.  If I build ***on*** and Intel Mac, then ***run*** the resulting library on a arm64 Mac, it fails at runtime here:

https://github.com/HDFGroup/hdf5/blob/3707675c0376e3866bc6eb7b926c9e7e2f9b3bec/src/H5Tconv.c#L735-L736

which evaluates to `4 != 4 || 16 != 8`.  i.e. `dt->shared->size` is 16 when it should be 8.  I suspect this is because the machine that ***built*** the library is x86_64 where `long double` is 16.

So far I haven't found where this could be happening... could anyone help point me where it might be coming from?

Thanks.

**Comment by seanm** [comment]
I made some progress.  `H5detect` creates a file `H5Tinit.c` and its contents differ based on build machine introspection.

**Comment by qkoziol** [comment]
> I made some progress. `H5detect` creates a file `H5Tinit.c` and its contents differ based on build machine introspection.

Yes, that is its purpose. :-)

**Comment by seanm** [comment]
Indeed. :)

So I guess there are two ideas:

1. Re-evalutate the whole idea of introspecting the build machine. Such introspection of course makes cross-compilation hard/impossible (and Universal Binaries are basically cross-compiling). Perhaps build-time introspection can be replaced with compile-time instead.

2. Detect that there are two architectures listed in `CMAKE_OSX_ARCHITECTURES` and create two `H5Tinit.c` files. Or similarly create a single `H5Tinit.c` that has preprocessor switches that give a final result like:

```
#if __x86_64__
    dt->shared->type = H5T_FLOAT;
    dt->shared->size = 16;
#elif __arm64__
    dt->shared->type = H5T_FLOAT;
    dt->shared->size = 8;
#endif
```

My feeling is that 1 would be better, but 2 would be easier.  Thoughts?

**Comment by seanm** [comment]
Is `H5detect` the only thing that introspects the building machine?

As a test, I modified `H5Tinit.c` by hand to have the `#if / #elif` as above, and now everything seems to be finally working for me as a Universal Binary. So this at least seems to be my last problem!

**Comment by qkoziol** [comment]
Sorry for the delay, this has been a tough week.  :-/

H5detect is indeed the only introspection tool that HDF5 runs.  We do support cross-compiling on other systems, usually by running H5detect by hand and then including the generated H5Tinit.c in the build.  I definitely would like to avoid putting #ifdef's into H5Tinit.c, so we should explore something else, like how the introspection is performed.  I don't think that compile-time introspection will perform well, but it might be OK, with some judicious use of function pointers, etc.

**Comment by seanm** [comment]
>We do support cross-compiling on other systems, usually by running H5detect by hand and then including the generated H5Tinit.c in the build.

That's essentially what I've done for the moment. Except in the case of Universal Binaries, it's not one H5Tinit.c file but two.  I basically took the two of them, and pasted them together into one file with this structure:

```
#if __x86_64__
    contents of H5Tinit.c for Intel
#elif __arm64__
    contents of H5Tinit.c for ARM
#endif
```

(The files are identical except for the `long double` parts.)

>H5detect is indeed the only introspection tool that HDF5 runs.

OK, good. And indeed I haven't found any other issues after hacking past H5Tinit.c.

> I don't think that compile-time introspection will perform well, but it might be OK, with some judicious use of function pointers, etc.

Did you mean 'run-time' in that sentence?  I'm not proposing run-time checks, but rather compile-time.  Something analogous to parts of https://github.com/HDFGroup/hdf5/pull/470/commits/9403e7d47d1e2878d6a4a1a9b7b84caa6df3ab8f ex: why build an executable to calculate `H5_SIZEOF_UINT32_T` when you can just use `sizeof(uint32_t)` directly and let the compiler evaluate it at compile-time?  Maybe something similar could be done to eliminate the need for H5Tinit.c entirely...

**Comment by seanm** [comment]
@qkoziol any thoughts over the months how to deal with this?

**Comment by seanm** [comment]
@qkoziol is it possible to contract HDFGroup to fix this?  i.e. I'm willing to pay, depending on price of course.

**Comment by epourmal** [comment]
@seanm I'll bring this up with developers. No payment is needed but good ideas are :-)

**Comment by seanm** [comment]
@epourmal thanks!

@byrnHDF I just checked, and `__aarch64__` is also defined on Mac (as is `__arm64__`), so that code in `H5pubconf.h.in` is fine and won't benefit from any `__aarch64__` to `__arm64__` change).

It's been months since I looked at this in detail, but re-reading things here, the issue is more with the `H5Tinit.c` file created by `H5detect`.  `H5detect` assumes there is one answer for questions like "how big is `long double`?" and it puts that one answer into `H5Tinit.c`.

**Comment by gnuoyd** [comment]
On Mon, Oct 25, 2021 at 08:40:06AM -0700, Sean McBride wrote:
> @epourmal thanks!
> 
> @byrnHDF I just checked, and `__aarch64__` is also defined on Mac (as is `__arm64__`), so that code in `H5pubconf.h.in` is fine and won't benefit from any `__aarch64__` to `__arm64__` change).
> 
> It's been months since I looked at this in detail, but re-reading things here, the issue is more with the `H5Tinit.c` file created by `H5detect`.  `H5detect` assumes there is one answer for questions like "how big is `long double`?" and it puts that one answer into `H5Tinit.c`.

Is there any reason not to perform the type-layout detection during
library initialization instead of during the build?  In that way
detection will be guaranteed to run on the target architecture.

H5detect does not appear to derive any information that cannot be found
out during target configuration (endianness), compilation (alignment),
or else from processor manuals (floating-point storage layout).  The
run-time detection may be useful as a fallback, but it's risky because
it may invoke undefined behavior.

Dave

**Comment by seanm** [comment]
> Is there any reason not to perform the type-layout detection during library initialization instead of during the build? In that way detection will be guaranteed to run on the target architecture.

As you say, that should work.  I guess an argument against it is that it would be doing at runtime something that can be known at compile time.  But as it would be run once, it's not such a waste.

>H5detect does not appear to derive any information that cannot be found out during target configuration (endianness), compilation (alignment), or else from processor manuals (floating-point storage layout). The run-time detection may be useful as a fallback, but it's risky because it may invoke undefined behavior.

Indeed I recall `H5detect` performing undefined behaviour as flagged by UBSan.  IMHO, ideally, `H5detect` should just go away.

**Comment by seanm** [comment]
Happy New Year all!

Any further thoughts on this issue?

**Comment by gnuoyd** [comment]
On Thu, Jan 06, 2022 at 08:55:40AM -0800, Sean McBride wrote:
> Happy New Year all!
> 
> Any further thoughts on this issue?

I think that h5detect should be replaced entirely, as you mentioned last
year.  In the New C99 Order, type size and natural alignment should be
discoverable at compile time.  The location and width of floating-point
fields (sign, mantissa, exponent) for each target architecture can be
derived from processor manuals and added to a table that's selected at
configure/compile time.  Endianness can be detected at configure/compile
time, too.  What am I forgetting?

Dave

**Comment by seanm** [comment]
> I think that h5detect should be replaced entirely

Agreed.  Who can do this?  I'm (well, my employer is) still willing to contribute some $ to get it done.

>In the New C99 Order, type size and natural alignment should be discoverable at compile time. The location and width of floating-point fields (sign, mantissa, exponent) for each target architecture can be derived from processor manuals and added to a table that's selected at configure/compile time. Endianness can be detected at configure/compile time, too. What am I forgetting?

That sounds like everything.

**Comment by qkoziol** [comment]
This may not work for cross-compiles+cross-execution environment situations, where the build system is different from the targeted runtime system.   This is the benefit of h5detect - you are not just cross-compiling, but you are actually running the binary in the environment where the application will run.

For example, h5detect can be built with a cross-compile, but then must be submitted as an actual job to the HPC job scheduler on some systems, to accurately detect the environment where applications execute.   It's not uncommon to have HPC systems where the "login nodes" are different from the "compute nodes".

If there was a reliable way to be certain that this continues working, then I'd be happy to remove h5detect also. :-)

**Comment by qkoziol** [comment]
As @gnuoyd says, this _could_ be done at runtime, within an application, but the extra overhead of executing it each time would be frustrating for applications to accept, since it could be done once, at configure time.

**Comment by seanm** [comment]
> As @gnuoyd says, this _could_ be done at runtime, within an application, but the extra overhead of executing it each time would be frustrating for applications to accept, since it could be done once, at configure time.

It would take a trivial amount of runtime to determine such things, wouldn't it?

**Comment by gnuoyd** [comment]
On Thu, Jan 06, 2022 at 09:22:17AM -0800, Quincey Koziol wrote:
> This may not work for cross-compiles+cross-execution environment situations, where the build system is different from the targeted runtime system.   This is the benefit of h5detect - you are not just cross-compiling, but you are actually running the binary in the environment where the application will run.

It's not necessary to run h5detect.  It is necessary to cross-compile
for the right target.

If the floating-point format is XYZ in the runtime environment, and I
cross-compiled for a target that uses floating-point format PQR, then
I chose the wrong target.  If the runtime environment does not support
an instruction that my binary uses, then I cross-compiled for the wrong
target.

Dave

**Comment by qkoziol** [comment]
No - the execution environment (i.e. what happens when a floating-point exception occurs, etc) can be different.

**Comment by gnuoyd** [comment]
On Thu, Jan 06, 2022 at 10:56:36AM -0800, Quincey Koziol wrote:
> No - the execution environment (i.e. what happens when a floating-point exception occurs, etc) can be different.

Please give a concrete example.

Dave

**Comment by seanm** [comment]
I'm inclined to agree with @gnuoyd. It seems to me whatever compiler you are using needs to know intimate details of what it's compiling *for*, whether cross compiling or not.

But to bring this back to the core issue... fixing the `sizeof(long double)` case would be sufficient for me.  It seems to be the only thing different between Intel vs ARM Mac.  Getting rid of h5detect entirely would be a bonus, but not necessary.

@qkoziol can you think of any example where a compiler doesn't know, at compile-time, `sizeof(long double)` for the target CPU?

**Comment by qkoziol** [comment]
>> Please give a concrete example.

Actually, this issue needs to work the opposite way - the new way needs to prove that it will work in all existing cases.  The old way doesn't need to prove anything, it already works correctly for all existing cases.

If you'd like to find out what those are, @brtnfld, Suren Byna (@ LBNL) and the DOE weapons lab people (like Lee Ward, Mark Miller, et al) would be the people to talk to about cases where cross-execution of h5detect is required.

**Comment by qkoziol** [comment]
> @qkoziol can you think of any example where a compiler doesn't know, at compile-time, `sizeof(long double)` for the target CPU?

Agree here, yes.

**Comment by seanm** [comment]
>The old way doesn't need to prove anything, it already works correctly for all existing cases.

Uh, no, the old way does ***not*** work for Universal Binary builds on macOS, which is the topic of this ticket :)

>Agree here, yes.

OK great. (Indeed I don't see how a compiler could generate assembly for `long double` use if it didn't know how big it was!)

So let's focus on this then. Can the subset of configure-time introspection that looks at the size of `long double` be excised?  (Removal of other configure-time introspection can be the topic of some other ticket.)

**Comment by qkoziol** [comment]
> > Agree here, yes.
> 
> OK great. (Indeed I don't see how a compiler could generate assembly for `long double` use if it didn't know how big it was!)
> 
> So let's focus on this then. Can the subset of configure-time introspection that looks at the size of `long double` be excised? (Removal of other configure-time introspection can be the topic of some other ticket.)

Agree - focus on fixing this problem separately from the h5detect issue.

**Comment by gnuoyd** [comment]
On Thu, Jan 06, 2022 at 10:56:36AM -0800, Quincey Koziol wrote:
> No - the execution environment (i.e. what happens when a floating-point exception occurs, etc) can be different.

The configuration of floating-point exceptions does not appear to make a
material difference to the H5Tinit.c that is generated.

I see h5detect trying to determine the machine's idea of each type's
native alignment using experimental accesses.  The behavior of those
accesses is undefined in C: it's possible for a C compiler just to elide
them or to do other nasty things.  So the experimental results are not,
strictly speaking, even reliable.

For the sake of discussion, call the type alignment found out by
experiment the "machine alignment."  The machine alignment is recorded
in H5Tinit.c.  Here and there the library uses a type's machine
alignment to decide whether to load/store an unaligned instance "directly" or
to bounce it through an aligned buffer.  E.g., in macro H5T_CONV in
H5Tconv.c:

                    /* Is alignment required for source or dest? */ 
                             \
                    s_mv = H5T_NATIVE_##STYPE##_ALIGN_g > 1 && \
                           ((size_t)buf % H5T_NATIVE_##STYPE##_ALIGN_g || \
                            /* Cray */ ((size_t)((ST *)buf) != (size_t)buf) || \
                            (size_t)s_stride % H5T_NATIVE_##STYPE##_ALIGN_g); \
                    d_mv = H5T_NATIVE_##DTYPE##_ALIGN_g > 1 && \
                           ((size_t)buf % H5T_NATIVE_##DTYPE##_ALIGN_g || \
                            /* Cray */ ((size_t)((DT *)buf) != (size_t)buf) || \
                            (size_t)d_stride % H5T_NATIVE_##DTYPE##_ALIGN_g); \

Thsoe unaligned accesses, too, invoke undefined behavior.

Are there any grounds for bouncing each access through an aligned buffer
using memcpy---not H5MM_memcpy---and letting the compiler sweat the
details.

Dave

**Comment by matham** [comment]
I have been trying to make arm64 wheels for pytables/h5py. To do that I initially made fat wheels by compiling hdf5 fat binaries but ran into issues.

Instead I focused on cross-compiling just for arm64. I was unable to do that neither with camke or configure and neither for 1.12.1 or 1.13.1. I got various errors, but basically it came down to something like in this issue where it was trying to run arm64 code of x86 or it (cmake) recognized it was cross-compiling and that it was not going to be able to run so it errored out.

I was only able to cross-compile after applying [these patches](https://github.com/conda-forge/hdf5-feedstock/commit/2cb83b63965985fa8795b0a13150bf0fd2525ebd) from conda-forge and setting the environment variables as shown there. It would be great if these could be applied somehow for 1.14!

**Comment by byrnHDF** [comment]
So at least for CMake, those patches just codify the process for cross-compiling. I will create a doc based on the small section VI in the release_docs/README_HPC file. 
`1.  HDF5_USE_PREGEN.  This option, along with the HDF5_USE_PREGEN_DIR CMake
    variable would allow the use of an appropriate H5Tinit.c file with type
    information generated on a compute node to be used when cross compiling
    for those compute nodes.`

I am thinking of creating a folder under config named "crosscompile" with pre-generated H5Tinit.c files.

I would think we could figure out how to get autotools/configure to the same.

**Comment by seanm** [comment]
There are a few PRs coming that should help with cross-compiling:

https://github.com/HDFGroup/hdf5/pull/1400

https://github.com/HDFGroup/hdf5/pull/1426

**Comment by matham** [comment]
Thanks these are great to hear! 

Would it make sense to add macos arm64 cross-compiling testing to the github actions? Preferably just arm64 and not just fat binaries because I was able to compile the fat binaries even though the arm64 side was not functional I think!? You wouldn't be able to test the actual binary, but at least the compilation would be tested.

**Comment by seanm** [comment]
Another interesting case is to build as x86_64-only *on* an arm64 Mac. That *can* be run at runtime because of [Rosetta](https://en.wikipedia.org/wiki/Rosetta_(software)).

**Comment by byrnHDF** [comment]
There are two processes during HDF5 config/build needing an alternative; the second is the pregeneration of H5Tinit.c so that h5detect doesn't execute and the first is the sequence of config checks, some of which need to be preset so that config skips the checks. Is there a list of which checks should be overridden?

**Comment by seanm** [comment]
So with #1400 and #1426 merged, it looks like `H5Tinit.c` is down to just one function: `H5T__init_native`, nice!

That function looks like it's related to checking the size of floats, meaning this ticket is not fixed, if I understand right...

**Comment by gnuoyd** [comment]
On Sun, Apr 24, 2022 at 04:18:36PM -0700, Sean McBride wrote:
> So with #1400 and #1426 merged, it looks like `H5Tinit.c` is down to just one function: `H5T__init_native`, nice!
> 
> That function looks like it's related to checking the size of floats, meaning this ticket is not fixed, if I understand right...

That's right, we still need to measure floats.

The other day I dashed off some code that uses C99 features both to
locate the sign, mantissa, and exponent bits and to find out the
exponent bias of a `float` without knowingly invoking undefined
behavior.

To identify padding bits without invoking undefined behavior looks
tricky, but I have some ideas.

Dave

**Comment by Alexander-Barth** [comment]
I am wondering if `H5detect` could not simply generate a C header file (e.g.  `H5Tinit.h`) with all the information about the floating point layout being set as `#define macro_name target_specific_value`. 

For cross-compilation, `H5Tinit.h` could be an empty file and all macro values could be defined as `CFLAGS` (`-Dmacro_name=target_specific_value`). Alternatively, a user could generate `H5Tinit.h` from a custom `H5detect` shell script.

**Comment by gnuoyd** [comment]
On Thu, Aug 04, 2022 at 09:00:07AM -0700, Alexander Barth wrote:
> I am wondering if `H5detect` could not simply generate a C header file (e.g.  `H5Tinit.h`) with all the information about the floating point layout being set as `#define macro_name target_specific_value`. 
> 
> For cross-compilation, `H5Tinit.h` could be an empty file and all macro values could be defined as `CFLAGS` (`-Dmacro_name=target_specific_value`). Alternatively, a user could generate `H5Tinit.h` from a custom `H5detect` shell script.

Hi Alexander,

I think that HDF5 can get rid of H5detect altogether.

Usually three properties of the target platform fix the floating
point (FP) layout: ABI, processor architecture, and endian mode (if
applicable for the processor).  It appears that sometimes a compiler
flag or other property also affects the FP layout, especially if any any
FP is emulated in software.  Nevertheless, every property affecting the
FP layout usually is known at compile time.

The compile-time fixed layout means that developers can look up each
platform's properties in manuals and provide an `H5T.<platform>.c` that
tells the library everything it needs to know about each C99 type on
`<platform>`.  The build can exclusively compile and link whichever
`H5T.<platform>.c` matches the target platform.

I figure that in a day, somebody could collect the information for
`H5T.<platform>.c` files for 32- and 64-bit x86 on Windows, Linux, *BSD,
and macOS, big- and little-endian 32- and 64-bit ARM on Linux, *BSD, and
macOS.  And then there are all of the other architectures.

Now, the `H5T.<platform>.c` files are just one approach.  Another
approach is to perform the floating-point introspection similar to the
way that H5detect does, only 1) doing it during library initialization
and 2) invoking no undefined behaviors.

A hybrid approach is possible.  Platform-specific files would tell the
layout in whole or in part, *and* the library would use introspection to
verify or complete the layout during initialization.

Dave

**Comment by Alexander-Barth** [comment]
@gnuoyd Thank you very much for your detailed feed-back!

The solution that you describe (collecting the information for different OSes/CPUs) would be ideal for projects like Julia and, I guess, for conda-forge too. It would solve several problems that we are currently facing (in fact, in julia the build infrastructure for all C libraries is build on cross-compilation).

Maybe this work would be useful:
https://github.com/musm/hdf5-build-output/tree/master/outputs

The feature request for cross-compilation has been around for quite a long time. Maybe there is some reluctance to maintain such a OS/CPU database.  If this is the case, then this information could also be maintained outside of HDFGroup/hdf5 assuming that the configure process of hdf5 provides a way to inject this information.

The functionality of `H5detect` could be still be kept around of unknown build targets (like specialized HPC kernels, PowerPC, RISC-V, WASM,...) as a fall-back or as a tool to build this database.

**Comment by seanm** [comment]
>I think that HDF5 can get rid of H5detect altogether.

That would be great!

>Nevertheless, every property affecting the FP layout usually is known at compile time.

Personally, I think deciding all this at compile-time makes the most sense.

>I figure that in a day, somebody could collect the information for
`H5T.<platform>.c` files for 32- and 64-bit x86 on Windows, Linux, *BSD,
and macOS, big- and little-endian 32- and 64-bit ARM on Linux, *BSD, and
macOS.

I could for Mac (PowerPC, i386, x86_64, and arm64) and for some flavours of the BSDs too probably.  What information would you need exactly?

**Comment by gnuoyd** [comment]
On Fri, Aug 12, 2022 at 08:19:41AM -0700, Sean McBride wrote:
> >I think that HDF5 can get rid of H5detect altogether.
> 
> That would be great!
> 
> >Nevertheless, every property affecting the FP layout usually is known at compile time.
> 
> Personally, I think deciding all this at compile-time makes the most sense.
> 
> >I figure that in a day, somebody could collect the information for
> `H5T.<platform>.c` files for 32- and 64-bit x86 on Windows, Linux, *BSD,
> and macOS, big- and little-endian 32- and 64-bit ARM on Linux, *BSD, and
> macOS.
> 
> I could for Mac (PowerPC, i386, x86_64, and arm64) and for some flavours of the BSDs too probably.  What information would you need exactly?

Just off the top of my head, we need this:

Identity of each platform: CPU architecture, optional endianness, OS
and/or ABI, plus any platform-specific switches that select different
variant floating-point layouts.

For each of a platform's floating-point types---both the C99 ones and
any platform-specific floating-point types---we need:

* type alignment in bytes
* type size in bytes
* mask for sign bit
* mask for mantissa
* indication whether most significant bit in mantissa is implicit or
  explicit
* mask for undefined or ignored bits---we can derive this from the other
  masks, but if we spell it out we can catch some errors
* mask for exponent
* exponent bias

A useful mask encoding for HDF5 purposes will consist of terms `bit(n)`,
`0`, and `bits(m, n)` separated by `|`, where `m` and `n` are bit
numbers starting from 0, 0 being the least significant bit.  We
can process that by hand or by machine into whatever we may need.
Ordinarily a mask will just have one term, but there are those funny IBM
encodings that need special treatment.  Here are `float`, `double`, and
`long double` on NetBSD/i386:

```
float
                                   4 size
                                   4 alignment
  0x0000000000000000000000000000007f exponent bias

                                mask role

                                   0 unused
                             bit(31) sign
                        bits(30, 23) exponent
                         bits(22, 0) mantissa
                                   0 explicit mantissa msb

double
                                   8 size
                                   4 alignment
  0x000000000000000000000000000003ff exponent bias

                                mask role

                                   0 unused
                             bit(63) sign
                        bits(62, 52) exponent
                         bits(51, 0) mantissa
                                   0 explicit mantissa msb

long double
                                  12 size
                                   4 alignment
  0x00000000000000000000000000003fff exponent bias

                                mask role

                        bits(95, 80) unused
                             bit(79) sign
                        bits(78, 64) exponent
                         bits(63, 0) mantissa
                             bit(63) explicit mantissa msb
```

Linux/x86_64 & NetBSD/amd64:

```
float
                                   4 size
                                   4 alignment
  0x0000000000000000000000000000007f exponent bias

                                mask role

                                   0 unused
                             bit(31) sign
                        bits(30, 23) exponent
                         bits(22, 0) mantissa
                                   0 explicit mantissa msb

double
                                   8 size
                                   8 alignment
  0x000000000000000000000000000003ff exponent bias

                                mask role

                                   0 unused
                             bit(63) sign
                        bits(62, 52) exponent
                         bits(51, 0) mantissa
                                   0 explicit mantissa msb

long double
                                  16 size
                                  16 alignment
  0x00000000000000000000000000003fff exponent bias

                                mask role

                       bits(127, 80) unused
                             bit(79) sign
                        bits(78, 64) exponent
                         bits(63, 0) mantissa
                             bit(63) explicit mantissa msb
```

I have a C99 program that generates these tables without invoking
undefined behavior, but the `long double` results would be worthless if
the unused bits took on arbitrary values as they are allowed to.

Dave

**Comment by seanm** [comment]
>I have a C99 program that generates these tables 

If it would help, I could run that on the various machines / OSes I have at my disposal.

**Comment by gnuoyd** [comment]
On Thu, Aug 18, 2022 at 07:44:36AM -0700, Sean McBride wrote:
> >I have a C99 program that generates these tables 
> 
> If it would help, I could run that on the various machines / OSes I have at my disposal.

Might quickly show where my program has deficiencies. :-) I will try to
attach a .tgz containing the sources.

Dave

**Comment by seanm** [comment]
If you're unable to attach it here, feel free to email it to me.

**Comment by MarkVabulas** [comment]
Please don't forget about the arm64 variant of windows as well.  But architecturally this should use the same information as linux and iOS, in theory, because the hardware should be the same, right?

**Comment by gnuoyd** [comment]
On Fri, Mar 18, 2022 at 06:19:13AM -0700, Allen Byrne wrote:
> I am thinking of creating a folder under config named "crosscompile" with pre-generated H5Tinit.c files.

That's a reasonable stopgap solution, however, I believe we can conserve
effort by completing the effort to remove H5detect.

Dave

**Comment by PhilMiller** [comment]
Is there an open issue or PR tracking the `H5detect` removal effort?

**Comment by seanm** [comment]
>Is there an open issue or PR tracking the H5detect removal effort?

AFAIK, *this* is the issue.

**Comment by derobins** [comment]
Can this issue be closed?

* The long double checks are gone
* AC_RUN_IFELSE in the Autotools has defaults for everything that is left (just szip encoding and checking pthread_attr_setscope)
* H5detect is gone
* H5make_libsettings is gone

Cross compiling should basically just work now. Not sure about universal binaries, though, since I have less experience there.

**Comment by seanm** [comment]
>H5detect is gone

Great!

> Cross compiling should basically just work now. Not sure about universal binaries, though, since I have less experience there.

I'll do some tests... Let's keep this ticket open until I can test...
