### ISSUE TITLE
CMake error on generate: "Cannot find source file hdf5/src/H5Epubgen.h"

### ISSUE THREAD

**Issue by a-ma72** [HDFGroup/hdf5#603]
Hello,

I try to build HDF5 libraries with CMake 3.19.4 on Win10 64bit, MinGW (TDM-GCC).
Set HDF5_GENERATE_HEADERS OFF, since I have not perl installed. 
Configuring works fine, but am not able to generate, due to this error:

```
CMake Error at src/CMakeLists.txt:1199 (add_library):
  Cannot find source file:

    .../hdf5/src/H5Epubgen.h
```

Any tips?

Regards, Andreas

**Comment by byrnHDF** [comment]
The development branches need to generate some source files using perl. These files are provided in the release branches.
