### ISSUE TITLE
Merge readers-writer lock to develop

### ISSUE THREAD

**Issue by qkoziol** [HDFGroup/hdf5#634]
I'd like to merge the readers-writer lock to the develop branch, as part of working with Lee Ward on improving the library's threadsafe concurrency.  I'm planning to update the change that was committed to the 1.12 branch, and submit a PR for it.   Any feedback before I start on this?

**Comment by epourmal** [comment]
Quincey,

We didn't reach an agreement on the approach how to make HDF5 multi-threaded. As you know, we do plan to discuss our concerns and different approach in less than two weeks. 

It would be very beneficial if we finish the work on the HDF5 1.13.0 release and HDF5 VOL connectors first. 

Thank you!

Elena on behalf of The HDF Group developers.

**Comment by qkoziol** [comment]
This is a community contribution and is not connected with any HDF5 work I might be working on during 'company time'.  I am submitting an issue for it as per the 'How to contribute to HDF5' guidelines and workflow.

And, yes, I am aware of the current planning effort - porting this code to the develop branch is intended as a help for that effort.

Please let me know if I should proceed with submitting this contribution.

**Comment by epourmal** [comment]
I suggest you wait until we agree that this is the direction we will be pursuing.


On May 8, 2021, at 9:28 PM, Quincey Koziol ***@***.***> wrote:

﻿

This is a community contribution and is not connected with any HDF5 work I might be working on during 'company time'. I am submitting an issue for it as per the 'How to contribute to HDF5' guidelines and workflow.

And, yes, I am aware of the current planning effort - porting this code to the develop branch is intended as a help for that effort.

Please let me know if I should proceed with submitting this contribution.

**Comment by qkoziol** [comment]
I'm going to pick this up and get started on it again.

**Comment by qkoziol** [comment]
I'm planning to create a PR that brings the lock that John created to the develop branch and uses it for the threadsafe FUNC_ENTER/LEAVE macros, as a baseline for future work in converting H5Dread to be threadsafe (beginning with the limited "no datatype conversion, contiguous layout only, ..." path).

**Comment by epourmal** [comment]
Hi Quincey,

Sure. 

Have you resolved with Dana portability to Windows?

Thank you!

**Comment by derobins** [comment]
John's lock changes were not ported to Windows, but I reorganized the code so it would be straightforward to do so. As long as any changes use our H5TS types and functions instead of pthreads directly, we should be able to eventually port the new thread-safe code to Windows.

**Comment by qkoziol** [comment]
I'll take a look at this and see what the effort is to bring it to develop now

**Comment by qkoziol** [comment]
I have a version which is working, but needs updated against the changes in develop that support the async VOL connector.   Once those are finished, I'll post a draft PR.

**Comment by qkoziol** [comment]
Done!  :-)
