### ISSUE TITLE
File descriptor leak in core VFD file open call

### ISSUE THREAD

**Issue by kalvdans** [HDFGroup/hdf5#635]
Found by manual inspection of code, see
https://github.com/HDFGroup/hdf5/commit/c2a9dcb8977f81ff8e66bfd41c72f106993d3086#r50505954

**Comment by byrnHDF** [comment]
Short version:
H5FDcore.c - functionH5FB__core_open line 804
`    if ((file_image_info.buffer != NULL) && !(H5F_ACC_CREAT & flags)) {
        if (HDopen(name, o_flags, H5_POSIX_CREATE_MODE_RW) >= 0)
            HGOTO_ERROR(H5E_FILE, H5E_FILEEXISTS, NULL, "file already exists")

`
Looks like assigning the HDopen to a variable is needed and then closing it before calling the HGOTO_ERROR?

**Comment by derobins** [comment]
Fixed with #3779
