### ISSUE TITLE
Test failures for H5DIFF-h5diff_830 and MPI_TEST_H5DIFF-h5diff_830

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#659]
1. test always fails with parallel enabled, won't work with parallel and should run only if parallel is not enabled.
2. 17 of 140 H5DIFF-h5diff_830 tests failed in HDF5112 tests and 7 of 25 in HDF5 develop branch tests on 5/18.  Failures were on macOS (bear and bigsur-1), ubuntu, and kituo (centos7).  "No such file or directory" was a frequently occurring message in the failed test output. 

Test will  be disabled until problems are addressed.

**Comment by byrnHDF** [comment]
h5diff has been reworked and all h5diff tests are enabled in testing across platforms
