### ISSUE TITLE
Unresolved links when using ZLIB

### ISSUE THREAD

**Issue by a-ma72** [HDFGroup/hdf5#714]
I built the HDF5 (1.12.0) static library and use it with success. 
Since I activated the GZIP (ZLIB) support I get different issues for two different compilers:

1. MSVC 2015 (Win10, 64bit)
The function `H5Dvlen_reclaim` no longer exists: `error C3861: "H5Dvlen_reclaim": identifier not found`
(But compression works fine)

2. TDM GCC 9.2 (Win10, 64bit)
References to ZLIB remain unresolved: `hdf5/src/H5Zdeflate.c:178: undefined reference to `compress2'`
(Also inflateInit_, inflate and inflateEnd)
But the library (zlibstatic.a) is linked (and prepended to hdf5.a) to the projekt and the listed functions are exports from the library (I used nm.exe to list them).

Any ideas?
Regards, Andreas

**Comment by byrnHDF** [comment]
A number of improvements have been made with compression since this issue and Daily Testing does not indicates any issues.

**Comment by derobins** [comment]
Closing since we don't see these issues with 1.14.x
