### ISSUE TITLE
syntax in hl/c++/src/H5PacketTable.h causes PGI failures compiling ptExampleFL.cpp

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#729]
line 36 of hl/c++/src/H5PacketTable.h:
   PacketTable() : table_id{H5I_INVALID_HID}
should be?
   PacketTable() : table_id(H5I_INVALID_HID)

to fix these errors:
/scr/hdftest/snapshots-hdf5/TestDir/jelly/hdf5/bin/h5c++   -o ptExampleFL /home/hdftest/snapshots-hdf5/current/hl/c++/examples/ptExampleFL.cpp
"/scr/hdftest/snapshots-hdf5/TestDir/jelly/hdf5/include/H5PacketTable.h", line
          37: error: expected a declaration
      {
      ^

"/scr/hdftest/snapshots-hdf5/TestDir/jelly/hdf5/include/H5PacketTable.h", line
          36: error: expected a "("
      PacketTable() : table_id{H5I_INVALID_HID}
                              ^

"/scr/hdftest/snapshots-hdf5/TestDir/jelly/hdf5/include/H5PacketTable.h", line
          36: error: expected a ";"
      PacketTable() : table_id{H5I_INVALID_HID}
                                              ^

**Comment by derobins** [comment]
Fixed in #731
