### ISSUE TITLE
How to really use backwards compatibility macros?

### ISSUE THREAD

**Issue by ax3l** [HDFGroup/hdf5#754]
Hi,

I am trying to build backwards compatible changes upon breaking APIs in 1.12.0.
I read the pages on http://develop.hdf5.info/api-compat-macros.html, which guide to `For new code development, The HDF Group recommends use of the compatibility macro mapped to the latest version of the function.`

So for a breaking change in `H5Oget_info` I implemented:
```C++
#if H5_VERSION_GE(1,12,0)
    status = H5Oget_info(node_id, &object_info, H5O_INFO_NUM_ATTRS);  // that's the compatibility macro
#else
    status = H5Oget_info(node_id, &object_info);
#endif
```
https://github.com/openPMD/openPMD-api/pull/696/files
Ref. and example from https://support.hdfgroup.org/HDF5/doc/RM/RM_H5.html#Library-VersionGE

But now I realize that if someone tells the HDF5 build system to use the `v110` or `v18` API, e.g. building my code against HDF5 1.12.0 with `-DH5_USE_110_API` set, the build fails because `H5Oget_info` gets mapped to `H5Oget_info1(node_id, &object_info)` without dropping the third argument. Isn't the idea of that macro in 1.12.0+ that it can downgrade gracefully?

Is this a bug in the `H5Oget_info` macro or me not understanding how to implement this `#if`?

How can I implement code that
- works with HDF5 1.10
- works with 1.12 breaking changes and
- works with 1.12 and `-DH5_USE_110_API` set

so it does also compile if the build system is, e.g. due to other constrains in complex build environments, instructed to use an older API?

Or the asked another way: if `H5_VERSION_GE` is not the right way to check the HDF5 _API version_, how do I as as an application developer identify the HDF5 _API version_ at compile time?

Can you potentially also add such a 5-line example to the docs for developers like me, please? :)

**Comment by byrnHDF** [comment]
The compatibility macro can be confusing and complicated - there are two use cases;  for those building the library and those building against the library. I believe you are concerned with the second. We have some tests that we will pull out some examples and post here as soon as we can.

**Comment by byrnHDF** [comment]
I think one solution in your usage would be to change the following from:
#if H5_VERSION_GE(1,12,0)
    status = H5Oget_info(node_id, &object_info, H5O_INFO_NUM_ATTRS);  // that's the compatibility macro
to
#if H5_VERSION_GE(1,12,0)
    status = H5Oget_info2(node_id, &object_info, H5O_INFO_NUM_ATTRS);  // use the 1.12 API

**Comment by ax3l** [comment]
Thanks a lot for your help. Yes, I am the developer building against HDF5 :) It looks to me like the docs on compatibility macros are currently more geared towards those building the library.

Yes I was wondering this might be what I should be doing, but cannot find an explicit example on it in the docs:
```C++
#if H5_VERSION_GE(1,12,0)
    H5O_info2_t object_info;
    status = H5Oget_info3(node_id, &object_info, H5O_INFO_NUM_ATTRS);
#else
    H5O_info_t object_info;
    status = H5Oget_info(node_id, &object_info);
#endif
```
(I think there might be no `H5Oget_info2` function and got a compile error if I don't also replace `H5O_info_t` to fixed API types.)

Is it possible that [the official docs](http://develop.hdf5.info/api-compat-macros.html) do not recommend this correctly? We basically do *not* use compatibility macros with that pattern, but the docs state:
```
For new code development, The HDF Group recommends use
of the compatibility macro mapped to the latest version
of the function.
```

**Comment by byrnHDF** [comment]
The HDF5 examples project uses the macros. https://github.com/HDFGroup/hdf5-examples
