### ISSUE TITLE
Undefined/unexpected behavior when passing a freshly allocated buffer or whitespace to h5fget_name_f

### ISSUE THREAD

**Issue by jhaiduce** [HDFGroup/hdf5#825]
h5fget_name_f calls len_trim() on its output buffer to obtain the length. This causes the output buffer to be read, resulting in the following problems:

- If the buffer is filled with whitespace, h5fget_name_f treats it as though the buffer had a length of zero. In my tests this resulted in an "Invalid write" error from Valgrind, so this is apparently triggering an array out of bounds error somehow as well.
- Possibly undefined behavior may result if a freshly-allocated buffer is passed in.

h5fget_name_f should instead call len() which obtains the total buffer length without reading the buffer contents.

**Comment by glennsong09** [comment]
Seems to be fixed by PR https://github.com/HDFGroup/hdf5/pull/972.
