### ISSUE TITLE
[Feature Request] Compression of vlen data

### ISSUE THREAD

**Issue by cwiede** [HDFGroup/hdf5#844]
Personally I would love to see the option to compress variable length data in hdf5 just as other types of data. 

It is pretty much counter-intuitive that gzipping the whole file leads to a compression factor of around 2, but enabling the gzip compression in hdf5 doesn't change the size at all.

**Comment by derobins** [comment]
This is a known limitation of the current HDF5 library. Thank you for the feature request, but I'm going to close this  for now.
