### ISSUE TITLE
H5LT files need rework to eliminate warnings with clang compiler

### ISSUE THREAD

**Issue by lrknox** [HDFGroup/hdf5#854]
Joe Lee added this line to hl/src/H5LTanalyse.c (line 1950):

                                        __attribute__((fallthrough)); 

It fails with MSVC, and the change needs to be made in non-generated H5LT files.

**Comment by derobins** [comment]
Is this still an issue?

**Comment by derobins** [comment]
Clang 14 emits no warnings when compiling the HL library and the __fallthrough__ line was removed.
