### ISSUE TITLE
Branch logic

### ISSUE THREAD

**Issue by woutdenolf** [HDFGroup/hdf5#911]
Could someone explain what the branch logic is of this repo? `1.10/master`, `hdf5_1_10`, `hdf5_1_10_7`, `master`, `develop`, ...

**Comment by epourmal** [comment]
Please see https://github.com/HDFGroup/hdf5/blob/develop/doc/branches-explained.md

Master should be ignored at this time.

**Comment by woutdenolf** [comment]
Perfect, thanks!
