### ISSUE TITLE
Alert users to not change collections in user callbacks while iterating

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5#92]
`H5Iiterate` is a case in point, but all modules should be reviewed.

**Comment by hyoklee** [comment]
https://docs.hdfgroup.org/hdf5/develop/group___h5_i_u_d.html#ga3bc2a11a594bf484cc5dc69ac987d0f4

**Comment by hyoklee** [comment]
Update H5Ipublic.h

**Comment by hyoklee** [comment]
@gheber , what do you mean by "collections" in this issue?

**Comment by gheber** [comment]
Mostly groups (= collections of links), attribute collections of objects, etc. I.e., don't change a group that you are iterating. OK?

**Comment by hyoklee** [comment]
I still don't understand. Please assign this to someone who wrote this function or is familiar with.
