### ISSUE TITLE
Consistent use of qualifiers - use uppercase

### ISSUE THREAD

**Issue by byrnHDF** [HDFGroup/hdf5#937]
There has been PRs created that change the qualifiers on numbers.
i.e.  1.0f to 1.0F

We should be consistent in our usage, the proposal is to use uppercase.

**Comment by seanm** [comment]
And such a change can be done automatically with [clang-tidy](https://clang.llvm.org/extra/clang-tidy/)

If it's agreed to go with uppercase, I can make a patch.

**Comment by byrnHDF** [comment]
It might be useful to at least see how extensive the issue has become or gotten better?

**Comment by seanm** [comment]
https://github.com/HDFGroup/hdf5/pull/1359

**Comment by derobins** [comment]
Fixed in #1359
