### ISSUE TITLE
CMake Error at config/cmake/ConfigureChecks.cmake:312 (file)

### ISSUE THREAD

**Issue by besoft** [HDFGroup/hdf5#969]
CMake GUI 3.21.1 on Windows x64 with Visual Studio 16 2019 as a generator fails to configure. 

The code FILE* pFile = fopen returns null, which results in TRY_RUN  failure. This can be solved by running CMake GUI runs with admin rights. However, for some reason, the file is then unavailable for reading by CMAKE line 312:

```CMAKE 
file (READ "${RUN_OUTPUT_PATH_DEFAULT}/pac_Cconftest.out" PROG_OUTPUT4)
```
My solution for the issue is to 
1. modify the macro C_RUN in config/cmake/ConfigureChecks so that it returns also the content of the standard output:
```CMAKE
macro (C_RUN FUNCTION_NAME SOURCE_CODE RETURN_VAR RETURN_OUTPUT_VAR)
```
...
```
#set (${RETURN_VAR} ${OUTPUT_VAR})
set (${RETURN_OUTPUT_VAR} ${OUTPUT_VAR})
```
2.  change the code so that the values are not printed into a file but into the standard output stream:
`#endif\n\nint main() {\nprintf(\"\\%d\\\;\\%d\\\;\", C_LDBL_DIG, C_FLT128_DIG)\\\;\n\nreturn 0\\\;\n}\n`
3. update lines 311 and 312 to process the values from the standard output stream:
```cmake
C_RUN ("maximum decimal precision for C" ${PROG_SRC} PROG_RES PROG_OUTPUT4)
#file (READ "${RUN_OUTPUT_PATH_DEFAULT}/pac_Cconftest.out" PROG_OUTPUT4)
```

**Comment by jwsblokland** [comment]
@besoft This issue reminds me of the closed issue [HDF5 1.12.1: Unable to compile the parallel version using CMake](https://github.com/HDFGroup/hdf5/issues/833) that I have reported in the past. Maybe the pull request https://github.com/HDFGroup/hdf5/pull/843 mentioned in the issue solves your problem.

**Comment by adbyrne** [comment]
This looks reasonable, however we will need to make the same change in the autoconf configure.
And we should try to extend this for the fortran configuration as well.

**Comment by byrnHDF** [comment]
PR #1089 created

**Comment by byrnHDF** [comment]
The solution has been merged into all branches.

**Comment by btknzn** [comment]
it is nice solution, thanks
