### ISSUE TITLE
File open error on Windows with onedrive

### ISSUE THREAD

**Issue by philrosenberg** [HDFGroup/hdf5#970]
I've been having what at first sight seemed like random write fails with my files. But in the end I tracked them down to a very specific scenario.

I am working in Windows and essentially the bug comes down to the fact that if the file is in my OneDrive folder and has been synced to the cloud and is opened truncated then the call to _open fails and gives an errno of EINVAL. I have created the following minimal code snippet which shows the problem. This code is basically what is used in H5FDsec2.c

```
#include<io.h>
int main()
{
    char path[] = "C:\\Users\\<my_username>\\OneDrive - <my_employer>\\Documents\\file.bin";
    int fh = _open(path, O_RDWR | O_CREAT | O_TRUNC | O_BINARY, _S_IREAD | _S_IWRITE);
    if (fh > 0)
    {
        _write(fh, "somebytes", 9);
        _close(fh);
    }
    else
    {
        int err = errno;
        char* message = strerror(err);
    }
    return 0;
}
```

The above code works as expected when the file doesn't already exist or when it exists but has not yet been synced to the cloud by onedrive. But it fails when the file exists and has already been synced to the cloud by onedrive. Removing O_TRUNC allows the call to succeed, but obviously no longer performs the desired functionality.

As I said, the HDF5 library uses code just like this in the H5FD_sec2_open function which calls HDopen (which is a macro rapper round _open).

I have posted the above snippet on stackoverflow https://stackoverflow.com/questions/68955214/open-fails-with-o-trunc-when-file-exists-and-is-synced-with-onedrive

I appreciate that this behaviour of the _open function may be unexpected or not as documented, so the bug is probably not in the HDF5 library per se, but it might be that you wish to add a workaround.

**Comment by derobins** [comment]
This is not something that can be fixed. Inconsistent files will cause problems when reading metadata from the file. It's up to the user to ensure that files are modified while other processes are reading them. We do have a "single writer / multiple readers (SWMR)" feature, but that only works on filesystems that preserve write ordering (i.e., not networked file systems like NFS and, presumably, OneDrive, Dropbox, etc.).
