### ISSUE TITLE
reproduction notice vs COPYING

### ISSUE THREAD

**Issue by chombourger** [HDFGroup/hdf5#990]
Several files read:

> All information contained herein is, and remains, the property of The HDF
> Group. The intellectual and technical concepts contained herein are 
> proprietary to The HDF Group. Dissemination of this information or
> reproduction of this material is strictly forbidden unless prior written
> permission is obtained from The HDF Group.

and in particular:

- src/H5FDhdfs.c
- src/H5FDhdfs.h
- java/src/hdf/hdf5lib/structs/H5FD_hdfs_fapl_t.java
- java/src/hdf/hdf5lib/structs/H5FD_ros3_fapl_t.java
- tools/libtest/Makefile.am
- tools/libtest/Makefile.in

while `COPYING` states:

> Redistribution and use in source and binary forms, with or without
> modification, are permitted for any purpose

should headers in the aforementioned files be updated to match the intent of the `COPYING` file?

Source and binaries of this package are included in free Linux distributions such as Debian (see https://packages.debian.org/source/stable/hdf5)

**Comment by epourmal** [comment]
Thank you for reporting! Yes, we will fix the headers.
